### ISSUE TITLE
请问，有没有批量检测ssr地址有效性的方法或者软件

### ISSUE THREAD

**Issue by jorismq** [shadowsocksrr/shadowsocksr-csharp#10]
请问，有没有批量检测ssr地址有效性的方法或者软件

**Comment by Akkariiin** [comment]
我也不知道

**Comment by Justsoos** [comment]
ssr c# 客户端本身，加上一点技巧就可以做批量检测。使用 “服务器负载均衡” + “按次序”，再设置一个短间隔发出代理连接请求的 command，比如 while true; proxychains curl baidu.com; sleep 5;done
运行几分钟，然后在ssr c#客户端的服务器记录里就能看到结果了。

还有一个方法是使用sstap，本身就可以作批量检测
