### ISSUE TITLE
希望添加domain fronting（域名欺骗）功能

### ISSUE THREAD

**Issue by yexiongkai** [shadowsocksrr/shadowsocksr-csharp#101]
最近，有很多ssr服务器IP被封，许多用户都遇到了这样的问题。如果添加了domain fronting功能，问题就迎刃而解了。

**Comment by Akkariiin** [comment]
你可能不太理解domain fronting
[这里](https://evi1cg.me/archives/Domain_Fronting.html) 有一篇文章，前半部分大致介绍了什么是domain fronting以及其的原理。

<hr/>

在google等云服务商CDN上使用domain fronting的原理是借用云服务商可信的权威域名来掩盖对真实的被阻止的域名的访问，这是一种形式上与HTTP代理非常相似的网站访问代理模式。
而这种模式存在的关键即在于主动向审查者(攻击者)暴露一个可信的权威域名从而躲过监测。

类似的，SSR混淆协议中的http-simple/post和tls1.2均使用了完全相同的思想，将一个非敏感域名暴露给攻击者来避免流量被阻断。
所以我觉得不存在你所说的这种可能性，IP是否被封也与此无关。
