### ISSUE TITLE
Version 4.9.0 does not support DDNS server domain?

### ISSUE THREAD

**Issue by Mercury2699** [shadowsocksrr/shadowsocksr-csharp#103]
My private server has a DDNS domain, which is ping-able through the network on the testing computer. It works perfectly when I type in the actual IP address in the _Server IP_ box in the _Edit Servers ..._ window. However, it never worked when I used my DDNS domain for the _Server IP_. Does the client soft support non-IP-adress servers? Many thanks if someone could help me out. 

Ran on Windows 10 17134.1, version 4.9.0

**Comment by zkyhzxf** [comment]
Wow，第一次见到有外国人用SSR

**Comment by Akkariiin** [comment]
it support non-IP-adress servers, but need a DNS server to resolve the real IP.
so, please set a DNS server on the setting.

**Comment by Mercury2699** [comment]
![3fb92437-a8c7-4d3b-9110-e451edcff94d](https://user-images.githubusercontent.com/38872649/40157001-a45b5732-596a-11e8-8baf-f329b9363b1b.png)
The image above shows my Global Settings, the Server Statistics and the CMD ping results. I have set the DNS in the Global Settings to 114.114.114.114, which is the China Telecom DNS Server. Note that in the Server Statistics windows there are error counts. It seems that it's not working still. Other DNS servers, such as 218.4.4.4 and 8.8.8.8, were also tested on but all ended with fail. @Akkariiin could you check if there's anything wrong for me? Thanks a lot.

**Comment by Akkariiin** [comment]
exc the ```nslookup yourdomain.com DNSServerIP``` to test the DDNS work well and make sure dns pollution are dont happend.
