### ISSUE TITLE
”更新PAC为绕过大陆IP（慎用）“规则还在更新吗？

### ISSUE THREAD

**Issue by reaCodes** [shadowsocksrr/shadowsocksr-csharp#108]
还有就是，如果PAC设置为”更新PAC为绕过大陆IP（慎用）“，那么代理规则设置为”绕过局域网和大陆“，这样不是多此一举吗，两个地方的设置似乎是一个意思

**Comment by AspirinGeyer** [comment]
所有的规则貌似很久都没有更新了。

**Comment by reaCodes** [comment]
那个大陆IP列表变化大吗，是不是比大陆常用域名稳定一点，范围大一点？

**Comment by Akkariiin** [comment]
没有更新，求PR

**Comment by wushu037** [comment]
@reaCodes 更新pac是更新pac，代理规则是依靠pac的，假设你代理规则设置了绕过大陆，但是pac里没有大陆域名，那他也不绕过
