### ISSUE TITLE
google.com和facebook.com无法访问

### ISSUE THREAD

**Issue by bydx** [shadowsocksrr/shadowsocksr-csharp#109]
https://www.google.com/ncr 和 https://www.facebook.com ，在【系统代理模式：PAC或全局、代理规则：绕过局域网和大陆】的情景下无法访问，更换网络、电脑、节点均无效，只能修改代理规则为全局解决，怀疑是SSR（版本4.9）内部的chn_ip.txt年久失修出了问题，有没有相同症状的童鞋呀？

**Comment by bydx** [comment]
重装软件居然解决了，汗~~~

**Comment by 417788939** [comment]
系统代理模式：全局。代理规则：绕过局域网和大陆。就这两个你不用改。

只能用全局代理规则应该是你浏览器设置问题。你用什么浏览器

**Comment by bydx** [comment]
@417788939 主要使用360极速浏览器，上述两个网址都打不开，但是切换到PAC/全局就可以打开了，在Chrome上测试只有google.com/ncr打不开。

**Comment by 417788939** [comment]
肯定是你IE代理设置问题，我这两个都能打开。
要么就是梯子服务商的锅

**Comment by bydx** [comment]
@417788939 谢谢回复，梯子换过几家了都一样，在360极速上安装switchomega测试后也排除了IE的问题，目前只要修改“绕过局域网和大陆”为“全局”就能解决所有问题，所以我感觉是SSR内置的大陆IP列表有问题，但是别人又没我这毛病，实在是百思不得解。

**Comment by kissPS** [comment]
@bydx 你好 请问解决了吗，我现在也是选全局才能打开facebook，但是google还可以开

**Comment by bydx** [comment]
@kissPS 没有啊，https://www.google.com/ncr 你可以打开？

**Comment by 417788939** [comment]
@bydx 
软件大家都一样，不会是软件的问题。
一个只能打开fb，一个只能打开谷歌。。。明显是个人pc配置问题吧

**Comment by 417788939** [comment]
如果电脑是win10系统就甩锅给win10→_→

**Comment by bydx** [comment]
@417788939 我一台win10一台win7，都有同样的问题…相同点就是都装了360，莫非是360作恶？

**Comment by 417788939** [comment]
@bydx 360全家桶？

**Comment by kissPS** [comment]
@bydx https://www.google.com/ncr 这个可以开，https://www.facebook.com/还是不行，但是https://m.facebook.com 可以，没装过360，没改过配置，系统也没动过，这几天才开始不能上的

**Comment by bydx** [comment]
@417788939 360安全卫士和360极速浏览器

**Comment by bydx** [comment]
@kissPS 我大约两个月前出现这个问题，以前也是完全正常的

**Comment by Justsoos** [comment]
建议换成chrome或firefox再测，如果好用，那就和ssr没任何关系。
流氓360的产品，碰都不想碰一下，更别说在虚拟机测试了。

**Comment by dou4cc** [comment]
@Justsoos 360 被国安控制后已经不流氓了, 广告之类的行为比竞品少很多.

**Comment by Justsoos** [comment]
你的问题初步推断是 dns 污染。自己找一些国内无污染dns设置上，比如 pdomo.me 应该就没问题了。动手能力更强的，自己装dnsproxy，DNSCrypt或者其他反污染本地解析

**Comment by Justsoos** [comment]
@dou4cc  习惯性流氓能赚钱的广告这个相对不算流氓的路子被掐了，岂不是更可怕？

**Comment by dou4cc** [comment]
@Justsoos 360 有国安的后台, 不缺钱, 现在专心搞监控去了.

**Comment by Justsoos** [comment]
别想当然了，赵家后代都分脏不均呢，还能给周鸿祎这个外姓。360也就在公开市场上耍流氓才能发财。

**Comment by bydx** [comment]
@Justsoos 换用Chrome、纯净DNS甚至网络都换了，问题依旧。
按照SSR的设定，Google/Facebook被送去VPS解析了，怎么会有DNS污染的问题呢。

**Comment by Justsoos** [comment]
建议你对比 
chrome://net-internals/#dns
和
dns.google.com
查询结果

**Comment by bydx** [comment]
@Justsoos 

![snipaste_2018-06-14_12-26-41](https://user-images.githubusercontent.com/31297910/41391701-d190edbe-6fce-11e8-90eb-926ffab8cafa.png)
![snipaste_2018-06-14_12-26-35](https://user-images.githubusercontent.com/31297910/41391702-d1cd6c9e-6fce-11e8-8d0a-7179e1ee35f9.png)

然后 chrome://net-internals/#dns 什么都没显示

![snipaste_2018-06-14_12-26-44](https://user-images.githubusercontent.com/31297910/41391700-d150e444-6fce-11e8-95e8-1841ecad6342.png)

感觉和 https://github.com/shadowsocks/shadowsocks/issues/559 非常类似，被这个问题困扰的人还挺多的……

**Comment by Justsoos** [comment]
这不是什么大不了的问题，那个帖子也说了https://github.com/shadowsocks/shadowsocks/issues/559#issuecomment-229376002
是ip解析被错误配置的hosts改错了。这不是ssr的问题。
还是你自己电脑或ssr服务器配错问题

**Comment by Justsoos** [comment]
另外，chrome://net-internals/#dns  这个里面没内容，本身就是大问题。这不应该是ssr的问题

**Comment by hacking001** [comment]
```
请更新 chn_ip.txt
https://github.com/LisonFan/china_ip_list/blob/master/SSR/chn_ip.txt
```

**Comment by flyingwhitewhale** [comment]
我也遇到类似问题过，解决如下：
1）dig www.google.com
发现返回的ip每次不同，有时是SOFTLAYER，经常是国内的电信ip
2）使用“绕过局域网和大陆”的问题根源浮出水面，DNS劫持导致SSR客户端将GOOGLE的IP判断为国内，不通过代理服务器连接，直连GOOGLE，而且是错误的IP，必然失败。
而哪怕DNS劫持返回SOFTLAYER的IP，被判断为国外ip，启动代理服务器连接时，ip错误一样连接不到。

解决方法：改用用户自定义，同时记得SSR文件夹里有定制user.rule

**Comment by bydx** [comment]
@flyingwhitewhal 这个自定义跟PAC差不多了，如果只能这样的话我还是选择pac模式或者浏览器装switchyomega过滤啦，手动添加域名也方便些，只是不太明白域名交给VPS解析还会被劫持？

**Comment by flyingwhitewhale** [comment]
我个人理解chrome+switchyomega下使用ssr客户端，并不像使用https代理强制远程解析，而是会受代理规则影响，只有设置用户自定义或全局才能远程解析，而局域网和大陆选项是调用本地解析，所以dns被劫持。


SSR代理模式定义的是那些流量进入客户端，代理规则定义的是上述流量哪些走代理，如果dns本地解析出来的ip是错误的，哪怕代理模式全局或pac，只要代理规则没指定这些流量走代理，还是连不上的。
总言之：
如果使用chrome+swichyomega，请switch yomega设置1080socks5，ssr客户端代理模式设为直连（影响的是系统代理而非chrome），代理规则设全局，最好设用户自定义，网上有现成维护好的rule可下载。
如果使用firefox，请把ff里代理设socks5，同时勾选dns在代理远程解析，代理规则设局域网和大陆，也可以。

**Comment by bydx** [comment]
@flyingwhitewhale 有道理，所以就是代理模式仅仅决定域名是否进入SSR，判断进入后视代理规则决定解析地点，在绕过规则下由本地解析，自定义/全局规则下由远程解析。影响解析地点的是代理规则，switchyomega类似于PAC模式，不涉及IP解析，应该和本问题无关。

刚刚找到了解决方案，将抗污染DNS（比如Pure DNS）填至此处即可解决。
![snipaste_2018-07-15_13-09-35](https://user-images.githubusercontent.com/31297910/42731212-3e5dcdfc-883b-11e8-8666-7f437f807749.png)
以前一直以为域名交由VPS解析，还纳闷这里空着个DNS是干啥的，现在总算明白了。

不过个人还是觉得用switchyomega过滤方便些，代理模式选择PAC（给下载工具用），代理规则选择全局，这样就不用考虑污染问题了。

感谢各位，完结撒花✿✿✿

**Comment by xieyan110** [comment]
好开心弄好了，重下了个ssr4.9  ，（把ssr的服务器备份一下）
不开ssr，打开360浏览器打开youtube.com，然后无法打开，点网络诊断没有问题，（之前修复后可以打开Google。com关了浏览器第二次却打不开）
打开下载的ssr，点更新pac。应该就好了。

**Comment by xieyan110** [comment]
刚刚又出现了，重启电脑解决了，

**Comment by bydx** [comment]
@xieyan110 
你仔细看过本issue没有？确定跟本issue有关？
另外打不开YouTube用网络诊断是认真的？

**Comment by hacking001** [comment]
更新 chn_ip.txt 以及配置本地 dnscrypt-proxy，这应该能解决这个问题了

**Comment by hacking001** [comment]
@xieyan110 出墙还用 360，够厉害

**Comment by guitarism** [comment]
@bydx 就是按照你这个填写抗污染DNS解决的，也是困扰了我好久这个问题。不错不错啊！但是这是为什么呢，而且只是针对google和facebook，不理解。

**Comment by guitarism** [comment]
@bydx 就是按照你这个填写抗污染DNS解决的，也是困扰了我好久这个问题。不错不错啊！但是这是为什么呢，而且只是针对google和facebook，不理解。

> 
> 刚刚找到了解决方案，将抗污染DNS（比如Pure DNS）填至此处即可解决。
>
> 以前一直以为域名交由VPS解析，还纳闷这里空着个DNS是干啥的，现在总算明白了。
> 
> 不过个人还是觉得用switchyomega过滤方便些，代理模式选择PAC（给下载工具用），代理规则选择全局，这样就不用考虑污染问题了。
>

**Comment by bydx** [comment]
@guitarism 问题解决后我也是直接SSR全局、SO过滤，方便管理规则且再没出过问题，至于为什么针对就没探究了。
