### ISSUE TITLE
手机用电脑的4.8/4.81做代理不能用telegram程序

### ISSUE THREAD

**Issue by huang1982** [shadowsocksrr/shadowsocksr-csharp#11]
版本 4.8  4.8.1 
自己用源码搭建的ssr，手机上装ssrr3.5.1可以正常登入telegram程序
用电脑端版本 4.8/4.8.1 ,电脑能打开版本 web版本的.telegram聊天，但是手机不登入ssrr，用局域网代理模式，用电脑做代理，可以正常访问谷歌，但是telegram刷新不了，一直连接中。。。。。。。。。

**Comment by kkjb** [comment]
You should manually set up the proxy of telegram

**Comment by Akkariiin** [comment]
@kkjb is right !

telegram->设置->数据和存储->代理设置
