### ISSUE TITLE
出啥问题了~今天

### ISSUE THREAD

**Issue by shuaipinghu** [shadowsocksrr/shadowsocksr-csharp#110]
今天下午开始不好用了。请问是什么原因~谢谢

**Comment by GoogleGFW** [comment]
你走错地方了

**Comment by FlyInWind1** [comment]
我帮我们学校老师装vpn，所有ss软件全部失效，当时我电脑没事，然后我这也不行了，一点问题都找不到，就是连不上，像是系统问题。不知道大哥有没有找到解决办法。
