### ISSUE TITLE
新的“本地DNS ”功能，填写格式是怎么样？

### ISSUE THREAD

**Issue by laincat** [shadowsocksrr/shadowsocksr-csharp#113]
原有的 DNS 是远程的吗？

IP:Port, IP:Port, IP:Port, 这样还是？

**Comment by AkaneAkaza** [comment]
进行规则判断的时候，使用DNS（假定这个DNS无污染）
解析服务器域名时，或规则判断结果为直连的时候，使用local DNS解析
填写方式和DNS一样，你的写法可以，port为53时可以省略

这样做是为了一些域名在不同DNS下有不同解析结果时，如果直连，那么使用本地DNS解析会有一个更理想的结果

**Comment by laincat** [comment]
这些 DNS 查询是 并发 吗？还是按先后？

**Comment by AkaneAkaza** [comment]
按填写先后
