### ISSUE TITLE
4.9.0版与switchyome扩展不兼容

### ISSUE THREAD

**Issue by hnc277** [shadowsocksrr/shadowsocksr-csharp#114]
环境：操作系统为win7sp1x64和win10 1803x64，ssr客户端为windows平台4.9.0版，chrome浏览器最新版，扩展程序商店安装的switchyomega 2.5.9版本，其中switchyomega配置为：1.proxy，代理服务器模式，127.0.0.1:1080。2.auto switch，自动切换模式，订阅了github的gfwlist。
问题：刚配置好时可以正常使用，访问www.google.com无任何问题，但过一两分钟后谷歌首页及部分页面会无法访问，提示隐私配置错误，此时查看网页证书发现被莫名替换成了Vmware的证书，出现此问题后重启ssr 4.9.0版本，再访问www.google.com会发现又正常了，此时查看证书也是正确的，但过一两分钟后问题重现。更换4.0.9版ss客户端时不会出现此问题，精力所限未再测试其他代理客户端版本。以上情况在win7和win10系统中均会出现，解决办法也相同，因此个人只好推测是4.9.0版本问题。

**Comment by Akkariiin** [comment]
VMware的证书????
请先排除一下是不是本地的VMware干扰或者抢占了端口

**Comment by hnc277** [comment]
卸载了VMware也一样，而且在安装ssr前一直用的ss，这期间从未出现过此问题，VMware是在ssr之前安装的

**Comment by hnc277** [comment]
仍然使用ssr4.9.0版，在使用switchyomega时，switchyomega配置不变，将ssr的系统代理模式设置为直连，然后代理规则设置为全局，问题解决。
