### ISSUE TITLE
auth_chain_e / f 无法使用

### ISSUE THREAD

**Issue by sunsan05** [shadowsocksrr/shadowsocksr-csharp#115]
路由端上配置了 auth_chain_a-f 都可以使用。

C#客户端配置 auth_chain_e-f不行 ，auth_chain_a/b 可以用。

检查过时间，没有问题，延迟30-40ms。

服务端使用的是 5月30日的  akkariiin/dev

客户端是 C# 4.9版本

**Comment by teraStars** [comment]
我也有同样的问题

**Comment by LoveBK** [comment]
我的也是**e**跟**f**不能用，其他可以，用了**f**后日志会显示下面开头的内容：
**ERROR    auth_chain.py:524 auth_chain_f data uncorrect auth HMAC-MD5 from
WARNING  common.py:250 unsupported addrtype 69, maybe wrong password or encryption method
WARNING  tcprelay.py:521 Protocol ERROR, TCP ogn data
ERROR    tcprelay.py:1097 can not parse header when handling connection from**

**Comment by MxdStudio** [comment]
一样的问题，手机安卓3.5.4客户端连接使用e/f完全正常，但是PC客户端4.9连接相同Server使用e/f会连不上。

经测试，现有PC客户端4.9版本支持到d是可以使用的，但是e/f连不上

**Comment by Akkariiin** [comment]
姐姐好像已经修了

**Comment by LoveBK** [comment]
> 姐姐好像已经修了

你是姐姐？

**Comment by sunsan05** [comment]
emmm，最近的确OK了。

**Comment by Akkariiin** [comment]
姐姐是Akane
