### ISSUE TITLE
请教个关于源代码修改的问题

### ISSUE THREAD

**Issue by miniaoe** [shadowsocksrr/shadowsocksr-csharp#118]
[](url)
![1](https://user-images.githubusercontent.com/21149432/41589060-1cd9e5ee-73e6-11e8-89d7-37da3343a12a.png)

如何去除括号内的IP内容以及括号，MenuViewController.cs 是在这个集修改吗，我没有找到，还望指教下。

**Comment by AspirinGeyer** [comment]
应该是改 `Server.cs +200` 的 `FriendlyName()`
