### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xfangbao** [shadowsocksrr/shadowsocksr-csharp#12]
编辑服务器------高级选项，
选上后取消不掉

**Comment by Akkariiin** [comment]
最新版没有这个问题呀？

**Comment by xfangbao** [comment]
4.8.1
选上以后确定一下，然后再打开取消一下试试。

**Comment by Akkariiin** [comment]
也没有呀，再打开默认是取消的呀。

**Comment by xfangbao** [comment]
你要选上去，填写一个端口号，确定之后，再取消试试。

**Comment by xfangbao** [comment]
填上端口确定以后，这个选项就取消不掉了。

2017-10-28 23:01 GMT+08:00 Akkariiin <notifications@github.com>:

**Comment by Akkariiin** [comment]
这不应该是正常的逻辑吗？不使用这个功能就不显示，使用的话就要显示出来提示用户以免用户被误导。
