### ISSUE TITLE
此项目是否换人接手了

### ISSUE THREAD

**Issue by jeremy0714** [shadowsocksrr/shadowsocksr-csharp#128]
今天在github上发现某pc版本ssr已更新到5.0.3
除了优化了一些小功能外，还加了2个新的协议 auth_akarin_rand ，auth_akarin_spec_a
不知道这里算不算是停止开发了，毕竟大半年已经没有更新了

https://github.com/SoDa-GitHub/shadowsocksrr-csharp/releases

**Comment by jmireles7** [comment]
1，更新在Dev分支
2，SoDa-GitHub 大佬做了Csharp客户端的更新，auth_akarin_rand ，auth_akarin_spec_a  查看commits
https://github.com/shadowsocksrr/shadowsocksr/commit/08b88026e884eac456b0d7dee1d5dbcbf30cebe3

**Comment by Akkariiin** [comment]
否

至于开发慢这是众所周知的原因所致

**Comment by AENeuro** [comment]
请问一下MAC系统有GUI更新吗？

**Comment by huohu4399** [comment]
@Akkariiin  问下大佬   这边的pc客户端   用起来真心顺手   但是   服务器端是否有对应的项目在更新？   还是说  服务器端已经很稳定   只需要维护客户端？  顺便感谢多年来的付出   辛苦了

**Comment by ntgeralt** [comment]
我觉得ssr pc版本 添加订阅逻辑可改进。例如添加订阅要点几次，第一次运行还要选择不走代理才能成功更新；内置的ssr条目失效干扰。

**Comment by Akkariiin** [comment]
@huohu4399 服务器： https://github.com/shadowsocksrr/shadowsocksr
