### ISSUE TITLE
续费以后无法使用，也打不开官网。

### ISSUE THREAD

**Issue by LilyYang1024** [shadowsocksrr/shadowsocksr-csharp#13]
在续费之后无法使用。打开之后不仅仅无法翻墙，甚至连国内网站都无法连接。
端口13714 协议auth_sha1_v4 混淆http_post SSR连接ssr://c2cyMDUuc3NyLnJlOjEzNzE0OmF1dGhfc2hhMV92NDphZXMtMjU2LWNmYjpodHRwX3Bvc3Q6V1VSUU5ESXhOVGMzTXpreC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVwYXc1WXFnNVoyaDVMcU03N3lNUVd4cFUwYyZncm91cD1VMmhoWkc5M2MyOWphM05T

**Comment by kkjb** [comment]
You should check your SSR Provider

**Comment by Akkariiin** [comment]
本项目没有官网，谢谢
