### ISSUE TITLE
关于访问whoer.net,DNS所在国家和IP不一致的疑问

### ISSUE THREAD

**Issue by pinecrane** [shadowsocksrr/shadowsocksr-csharp#131]
关于DNS方面的一点疑问，经过实际使用发现，4.8.0版本客户端在代理规则，代理模式均为全局的时候，通过访问whoer.net，检测到的DNS所在国家和访问者(客户端侧)IP一致，比如服务端是美国IP，那么DNS所在国家显示为美国，相同。使用5.0.0的时候，发现DNS所在国家显示为中国，和服务端IP不一致。这样会导致匿名性不够好，很多境外商家会据此认为是Proxy。同样的实际使用环境下，只是客户端版本不一样，就会出现上述的现象。只是有个疑问发帖，不敢说是后续开发维护中混入的degree,如有冒犯，多多原谅。

**Comment by Akkariiin** [comment]
哪里有5.0.0版？请指给我看：

https://github.com/shadowsocksrr/shadowsocksr-csharp/releases

**Comment by pinecrane** [comment]
哦哦，抱歉了，大佬。
给搞混了都，我把这个Issues地方，当作是那个XXXX搞的后续版本的了。那个另外fork后自己改的版本，在GUI上增加了一个local dns的输入框。我现在就老老实实的用4.8.0好了。谢谢您百忙之中回复。
致歉。
