### ISSUE TITLE
能添加反杀毒软件机制吗

### ISSUE THREAD

**Issue by yexiongkai** [shadowsocksrr/shadowsocksr-csharp#139]
许多用户不知道一些杀毒软件（特别是360）正在后台监控网络，一嗅探到可疑信息就会收集哪些资料
并上传至安全中心
如果添加了这个机制，在杀毒软件运行时ssr就会拒绝运行，从而有效保护敏感信息
如果在ssr运行过程中突然有杀毒软件开始运行，ssr也会停止运行

还有，如果能对本地的数据进行加密就更好了^_^这样可以防范间谍软件

**Comment by Justsoos** [comment]
你到底是来举报360大流氓的，还是要ssr作病毒行为的呢？
前者，惹不起流氓，你还躲不起流氓？
后者，本来就是合理“不合法”的翻墙软件，当然可以光明正大的用，你是想要让它彻底带上病毒，木马属性？然后被恶意利用，再被党国加罪名，抓人封杀？

逻辑搞清爽了，再来发帖。
