### ISSUE TITLE
Google 访问被拒绝

### ISSUE THREAD

**Issue by zhengdafangyuan** [shadowsocksrr/shadowsocksr-csharp#141]
访问Youtube、Facebook正常，有时候访问Google 或者Google Scholor正常无问题，但是经常出现以下拒绝访问的情况：
**Google   Sorry...
We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.**

**这是由于服务器的问题，还是？**

服务器参数和客户端设置： 
服务器 Vultr  新加坡节点，CentOS 7 x64
根据以下教程安装ShadowsocksR和启动BBR.
[《ShadowsocksR一键安装脚本》](https://shadowsocks.be/9.html)
[一键安装最新内核并开启 BBR 脚本](https://teddysun.com/489.html)
在/etc/shadowsocks.json 设置了多端口，多用户模式，分别用了8080， 80， 137， 138，另外local address : 127.0.0.1， local _port : 1081。
method : chacha20
protocol ： auth_sha1_compatible 
obfs ：http_simple_compatible

windows 客户端使用ShadowsocksR-win-4.8.1
代理模式： PAC
代理规则： 绕过局域网和大陆
协议： origin **（使用auth_sha1_v4 无法连接上外网）**
混淆： http_simple

**Comment by Justsoos** [comment]
这是你 ssr 的节点太多人用，或者被google列入机器人黑名单的结果。请换IP，或者换服务商。
