### ISSUE TITLE
老故障，找到了问题关键。启动端口被占用报错--其实来自privoxy端口占用

### ISSUE THREAD

**Issue by Justsoos** [shadowsocksrr/shadowsocksr-csharp#142]
用了快2年的win10 ss，后来ssr csharp，端口从来没换过，今天突然出现了端口占用错误提示。
使用各种方法，包括 tcpview，netstat 都没发现任何其他程序占用此端口。
也不是迅雷的问题。

后来发现，其实是 ssr 和 ss csharp 自带的 privoxy 内第一个本应random listen端口占用，而 ss 和 ssr 的 log 非常奇怪，并没有报告是这个端口被占用，反而直接提示是 ss/ssr 本身占用端口被占用。
也就是下面这个 privoxy 的 conf 配置文件里，第一行这个端口：
```
listen-address 127.0.0.1:56610
show-on-task-bar 0
activity-animation 0
forward-socks5 / 127.0.0.1:1080 .
hide-console
```
在 ssr 里，是` temp/privoxy.conf `文件，ss 里是 `ss_win_temp\privoxy_-1779672432.conf` 类似名字文件，在任务列表里结束 privoxy 的进程，并删掉这个配置文件，重新运行 ss 和 ssr 会重建这个文件，并产生新的 random listen port of privoxy。故障解决。

推测，是ssr 和ss 启动和结束主进程时，并没有杀掉之前运行的 privoxy 进程，并且启动时没有选择新可用端口，造成这个错误。且 log 内返回值并没有真实的反映是 privoxy 占用端口，造成很多人误解 -- 找不到占用端口的程序，却一直报错，无法运行。

https://github.com/shadowsocks/shadowsocks-windows/issues/1472
https://github.com/shadowsocks/shadowsocks-windows/issues/1841
https://github.com/shadowsocks/shadowsocks-windows/issues/241
https://github.com/shadowsocks/shadowsocks-windows/issues/564

**Comment by Justsoos** [comment]
**不建议任何用户使用上面这个链下修改版 SSR**，这个原来叫 SoDa-GitHub fork 的 SSR，此人品质极差，到处骂人，显示自己牛b，其实水平是真的差，名声臭的要死，又改名叫现在的 CGDF-Github/SSRR-Windows 的开发者的 SSRR 修改版。
这个人是个精神分裂的流氓，产品也是流氓。

1，他的开发版 SSRR 会检测你的 windows 进程和注册表，存在隐私泄露风险
2，会疯狂连接你的SSRR节点作探测，可能引发GFW封锁
3，他改出来的几个小改进，技术含量极低，不值得为了这个去冒险。

**Comment by JohnFreeman9** [comment]
> **不建议任何用户使用这个 SSR 修改版**，这个原来叫 SoDa-GitHub fork 的 SSR，此人品质极差，到处骂人，显示自己牛b，其实水平是真的差，名声臭的要死，又改名叫现在的 CGDF-Github/SSRR-Windows 的开发者的 SSRR 修改版。
> 
> **这个人是个反社会的，精神分裂的流氓，产品也是流氓。**
> 
> 1，他的开发版 SSRR 会检测你的 windows 进程和注册表，存在隐私泄露风险
> 2，会疯狂连接你的SSRR节点作探测，可能引发GFW封锁
> 3，他改出来的几个小改进，技术含量极低，不值得为了这个去冒险。
> 
> https://github.com/CGDF-Github/SSRR-Windows/
> https://github.com/SoDa-GitHub/SSRR-Windows/
> 
> 这个人流氓之处在于，他还会频繁改成其他名字，继续来坑人。各位小心！
> #128

事实上你所提到的修改版都已经是SSRR其他人再FORK开发的版本了，不太理解到这边来批评一番的意义何在

**Comment by Justsoos** [comment]
互联网是有记忆的，为流氓行为留点后来人能看到的历史。

**Comment by hhelibeb** [comment]
> **不建议任何用户使用这个 SSR 修改版**，这个原来叫 SoDa-GitHub fork 的 SSR，此人品质极差，到处骂人，显示自己牛b，其实水平是真的差，名声臭的要死，又改名叫现在的 CGDF-Github/SSRR-Windows 的开发者的 SSRR 修改版。
> 
> **这个人是个反社会的，精神分裂的流氓，产品也是流氓。**
> 
> 1，他的开发版 SSRR 会检测你的 windows 进程和注册表，存在隐私泄露风险
> 2，会疯狂连接你的SSRR节点作探测，可能引发GFW封锁
> 3，他改出来的几个小改进，技术含量极低，不值得为了这个去冒险。
> 
> https://github.com/CGDF-Github/SSRR-Windows/
> https://github.com/SoDa-GitHub/SSRR-Windows/
> 
> 这个人流氓之处在于，他还会频繁改成其他名字，继续来坑人。各位小心！
> #128

可以推荐一个能用的版本吗？

**Comment by Steven-Shixq** [comment]
我也出现了这个问题，但通过lz的方法没有成功解决这个问题，最后通过SSR里的设置-->选项设置，然后将本地端口的1080改成一个其他的端口就解决了，比如我的改成8776就好了。希望能帮到有类似问题的小伙伴。

**Comment by yashika** [comment]
我也有类似问题, 是在win10上复现的, 本来一直用的好好的突然就提示端口被占用而且通过检查发现并未被占用. 这种情况其实是因为win10保留动态端口的端口号范围和你设定的端口出现了冲突(内核系统级冲突,普通工具是看不到的), 所以我们要修改动态端口的许可范围, 上调到比如从30000这种不常用端口开始.
使用管理员权限cmd执行如下指令 然后必须重启一次电脑即可 解决冲突问题
netsh int ipv4 set dynamicport tcp start=30000 num=20000

**Comment by GaoJones** [comment]
通过netstat -nao | findstr "XXXXX“ 查看端口并没有被占用，但是你的端口可能被保留了(例如Hyper-V),这个地址解决了我的问题：https://zhuanlan.zhihu.com/p/341274233

**Comment by zwdsly** [comment]
谢谢你，我成功解决了，我的电脑曾经弄过hyperV和Vmware，最近连不上了，用了各种方法都没用，你这个直接药到病除

![Image](https://github.com/user-attachments/assets/34ea2042-2b14-49ab-a799-480b7c7a93e6)
