### ISSUE TITLE
使用5.1.5版本时，明明没有装百度，360，2345软件，还是不让我用，为什么

### ISSUE THREAD

**Issue by zhanghan-7** [shadowsocksrr/shadowsocksr-csharp#144]

**Comment by Justsoos** [comment]
https://github.com/CGDF-Github/SSRR-Windows/issues
你搞错地方了，5.1.5 是这个开发者

**Comment by Justsoos** [comment]
对了，不建议任何用户使用这个原来叫 SoDa-GitHub，到处骂人，显示自己牛b，其实水平是真的差，名声臭的要死，才又改名叫现在的 CGDF-Github/SSRR-Windows 的开发者的 SSRR 修改版。
这个人是个精神分裂的流氓，产品也是流氓。

1，他的开发版 SSRR 会检测你的 windows 进程，隐私泄露风险
2，会疯狂连接你的SSRR节点，可能引发GFW封锁
3，他改出来的几个小改进，技术含量极低，不值得为了这个去冒险。
