### ISSUE TITLE
ssr可以访问谷歌但是访问不了YouTube，换了很多个节点还是一样。

### ISSUE THREAD

**Issue by KWZW** [shadowsocksrr/shadowsocksr-csharp#145]
I know not to welcome outsider but this is my last straw.Please reply to me in Chinese, thank you.

**Comment by Akkariiin** [comment]
??? what your means ?

**Comment by Justsoos** [comment]
本来u2b就不是一个域名服务器需要代理才能正确使用，google一个域名代理就能用。
太小白，最好用傻瓜工具，比如全局代理，要么就学习一下网络知识再说，技不压身

**Comment by shishirong** [comment]
换个DNS试试
