### ISSUE TITLE
tls1.3正式版出来了，应该有望研发基于tls1.3的混淆技术吧？

### ISSUE THREAD

**Issue by DavidDen** [shadowsocksrr/shadowsocksr-csharp#148]
首先感谢社区开发者的努力，让我勉强可以呼吸自由的空气。
Tls1.3虽然基于tls1.2，不过移除了较少使用的弱加密算法，同时提升速度。随着握手次数的减少，是否也能减少特征？这个就尚待研究了。

**Comment by Akkariiin** [comment]
混淆的本质目的是，把SSR协议“装扮”为某种特定的协议，借助这种特定的协议不会被封禁的特性来让SSR协议也不被封禁
