### ISSUE TITLE
能开发基于tls1.3的真正不会被墙的混淆协议吗(使用ESNI扩展)

### ISSUE THREAD

**Issue by yexiongkai** [shadowsocksrr/shadowsocksr-csharp#151]
tls1.3添加了加密sni的支持
https://tools.ietf.org/html/draft-rescorla-tls-esni-00
以防止gfw能区分真假服务器
同时支持了0-rtt延迟(使用psk)
可以大大提高速度
还能更有效地防止被墙
DNS也有了较高的改进

**Comment by yexiongkai** [comment]
cloudflare目前已经支持了ESNI
https://blog.cloudflare.com/encrypted-sni/

**Comment by reece00** [comment]
如果国家真的想墙一个红头下来谁都别想跑。

**Comment by Akkariiin** [comment]
tls1.3 ESNI 是为直接访问提供隐匿性的，试图隐藏目标域名来提供通过CDN间接访问目标服务的能力

ssr 实现的 tls1.2 中params的作用是给墙提供一个强特征，使用虚假的域名来避免被封禁

这两者的设计思路和适用场景是不一样的

**Comment by Akkariiin** [comment]
同样的，我认为如果大规模使用ESNI就会导致所有tls1.3协议被批量封锁，或者出现可以使tls1.3降级到tls1.2的down-level攻击

**Comment by Akkariiin** [comment]
当然我觉得你问了个好问题，欢迎继续提供这样有深度的问题

**Comment by Antairez** [comment]
@Akkariiin 原始params教程都建议使用Cloudflare.com作为混淆参数，您这边提到使用虚假域名才能避免被封禁，请问哪个效果更好呢？

**Comment by Akkariiin** [comment]
“使用虚假的域名来避免被封禁”的意思是，在这里使用的域名不是当前机器真正工作的域名
  
比如说，在自行搭建的，与Cloudflare没有任何关系的VPS上，使用SSRR并设置params为Cloudflare.com
那么这就是一种“虚假的域名”
  
在当前时期，建议在使用tls混淆时，将端口开在443，params填写一个不会被封锁的国际知名服务，例如Microsoft或Cloudflare这类与政府有深度合作的知名企业域名，并且在redirect设置中设置重定向到对应域名的真实主机，这样来将开启了SSRR的服务器主机伪装成一个可信赖的主机，以便骗过主动侦测类型的探针。
