### ISSUE TITLE
[功能建议]增加回调地址

### ISSUE THREAD

**Issue by weianguo** [shadowsocksrr/shadowsocksr-csharp#153]
建议增加1个【填回调地址的地方】，填写后菜单增加【服务器详情】，点击打开网页，将当前服务器配置IP端口等信息POST给回调地址。

这样我将可以返回服务器端流量使用情况，VPS状态等信息，甚至可以重启服务器，VPS续费。

**Comment by Akkariiin** [comment]
黑人???

那么鉴权怎么设计呢？如何保证服务器的这个回调端口不会被恶意攻击呢？
