### ISSUE TITLE
 更新一下吧

### ISSUE THREAD

**Issue by jarodvip** [shadowsocksrr/shadowsocksr-csharp#158]
我看代码还在修复，是否可以更新一下软件呢！谢谢大佬了

**Comment by WilllllChen** [comment]
自己下载了用VS编译下就好

**Comment by wxlg1117** [comment]
git下来最新的dev代码并且手动合并了官方PR中的新增功能那个PR用VS2017编译的主程序exe:
1.「切换服务器时，断开与之前服务器的所有连接」这个特性我在设置中新增了一项，该项默认关闭，打开即激活。
2. 完善部分文本的翻译，更改了英文描述，去掉了那个翻译文本中因为妥协加入的空格。

![qq 20181206123239](https://user-images.githubusercontent.com/9752596/49561625-1a401380-f910-11e8-93d9-2fd38fd31c4f.jpg)

https://drive.google.com/open?id=1C_kz1xgsFsRhzuLLQt6s_n3Uue_I1HAT

需要的人下载官方Release版解压,然后下载此链接文件解压后自己选择2.0或者4.0的debug版或者Release版主程序exe去替换掉官方最新Release的主程序,然后即可食用.

**Comment by ZBSSA** [comment]
> git下来最新的dev代码并且手动合并了官方PR中的新增功能那个PR用VS2017编译的主程序exe:
> 1.「切换服务器时，断开与之前服务器的所有连接」这个特性我在设置中新增了一项，该项默认关闭，打开即激活。
> 2. 完善部分文本的翻译，更改了英文描述，去掉了那个翻译文本中因为妥协加入的空格。
> 
> ![qq 20181206123239](https://user-images.githubusercontent.com/9752596/49561625-1a401380-f910-11e8-93d9-2fd38fd31c4f.jpg)
> 
> https://drive.google.com/open?id=1C_kz1xgsFsRhzuLLQt6s_n3Uue_I1HAT
> 
> 需要的人下载官方Release版解压,然后下载此链接文件解压后自己选择2.0或者4.0的debug版或者Release版主程序exe去替换掉官方最新Release的主程序,然后即可食用.
> 
> @ZBSSA @yexiongkai @jarodvip

十分感谢

**Comment by yexiongkai** [comment]
这个版本的自动更新订阅功能有问题（无法启动）

**Comment by kasuganosoras** [comment]
> 咕咕咕~

是同款鸽子王 Akkariiin！awsl

另外 PAC 老是更新失败怎么破

**Comment by Akkariiin** [comment]
更新了
<hr/>
@kasuganosoras PAC可以自己复制一个新的放进去
