### ISSUE TITLE
希望添加一个显示节点延时的功能

### ISSUE THREAD

**Issue by Funfir3s** [shadowsocksrr/shadowsocksr-csharp#159]
希望大佬能添加一个显示节点延时的功能。

**Comment by yexiongkai** [comment]
这个功能在以下ssr客户端中有
https://github.com/CGDF-Github/SSRR-Windows/releases

**Comment by yexiongkai** [comment]
不过据说这个客户端不是很友好

**Comment by wxlg1117** [comment]
@yexiongkai,大佬,这个客户端没看到有显示节点延时的功能呀,方便截图看一下么?

**Comment by Funfir3s** [comment]
> 不过据说这个客户端不是很友好

这个客户端日常用还是可以的，但是开网页ins加载不了图片，facebook加载不了css（不确定是不是这个），其他的问题还没有发现

**Comment by yexiongkai** [comment]
延迟检测结果在服务器连接统计里
这个客户端在运行后3-6秒自动进行延迟检测
^ - ^

**Comment by yexiongkai** [comment]
以下是原版描述
新增：
本地批量测延迟功能。
测延迟会在程序启动3秒后、6秒内执行。
右击右下角图标，服务器列表中即可看见所有服务器的延迟。
（使用TCP测验迟，可用显示服务器是否被TCP阻断）

**Comment by wxlg1117** [comment]
@yexiongkai,延迟检测结果在服务器连接统计里>>>这个功能不是SSR都有自带的呀,有区别?

**Comment by Funfir3s** [comment]
> @yexiongkai,延迟检测结果在服务器连接统计里>>>这个功能不是SSR都有自带的呀,有区别?

有区别的，有一版本是在右键节点选择的时候，节点前都会有一个延时“xx ms”的提示
