### ISSUE TITLE
编译含有最新commits的dev版本,然后在2012R2服务器系统上运行后提示缺少.net 3.5 ...

### ISSUE THREAD

**Issue by wxlg1117** [shadowsocksrr/shadowsocksr-csharp#160]
git最新代码到本地后双击shadowsocks-csharp.sln用vs 2017打开,然后生成解决方案,复制出bin目录下生成的 2.0和4.0的ShadowsocksR.exe,在装有.net4.5的2012R2系统上打开俩者就提示缺少.net 3.5 ...

releases下载来的4.9.0是正常运行不会提示缺少.net 3.5的

求大佬,怎么解决?

**Comment by dna1982** [comment]
解决方法就是去用 v2ray ……

**Comment by AspirinGeyer** [comment]
2.0 是基于 `.NET Framework 2.0` 构建的，此版本提供给 Windows XP/2003 等默认不安装 `.NET Framework 4.0` 的用户。从 Windows 8 开始 `.NET Framework 3.5` 需要单独安装，从 Microsoft 网站下载并安装即可。

4.0 是基于 `.NET Framework 4.0` 构建的，Windows 7 或者更高版本的用户请使用这个版本。

**Comment by Akkariiin** [comment]
稍后有新版发布
或者可以去这里下载每夜编译版

https://ci.appveyor.com/project/Akkariiin/shadowsocksr-csharp
