### ISSUE TITLE
托盘图标气泡显示当前连接的节点...

### ISSUE THREAD

**Issue by wxlg1117** [shadowsocksrr/shadowsocksr-csharp#161]
记得老版本的时候这个功能还是有的,不知道什么版本后是放弃了该功能还是只是注释了代码?然后该显示就没有了,有大神提示下怎么修改代码找回该功能么?

![qq 20181205144751](https://user-images.githubusercontent.com/9752596/49495327-9f3e1500-f89d-11e8-989e-a142468d53ee.jpg)

**Comment by Akkariiin** [comment]
因为windows限制这个位置显示的字数，如果名字太长会显示不下，所以后来就去掉了

**Comment by Akkariiin** [comment]
当然如果你想要自己改的话，他就在这里
https://github.com/shadowsocksrr/shadowsocksr-csharp/blob/2dc226892b31cf88b4228593cdb4dfcd904ed470/shadowsocks-csharp/View/MenuViewController.cs#L213-L221

**Comment by Akkariiin** [comment]
https://stackoverflow.com/questions/579665/how-can-i-show-a-systray-tooltip-longer-than-63-chars

**Comment by Akkariiin** [comment]
当然我觉得其实可以把服务器名称放在最后一行，然后在63字符的地方trunc掉换成```...```，这样可能比较好一点

**Comment by wxlg1117** [comment]
@Akkariiin ,这个我复制粘帖了一堆代码已经ok,然后我提交给了另外一个fork,那个大神优化并增强:

添加气泡显示当前连接服务器名称或者负载均衡类型;

1.当气泡显示为负载均衡类型时也会自动调用相应的简繁英翻译显示;
2,当气泡显示为当前连接服务器名称时默认显示为 群组名+备注,如果 如果某一个为空则显示为另外一个,如果俩个都为空则第二栏不显示为空白;
3,用了反射设定解除了系统栏工具提示的63字符限制,默认为127字符;

![Snipaste_2019-05-09_06-03-03](https://user-images.githubusercontent.com/9752596/57382893-5db0ed80-71e0-11e9-852c-81afee7f121d.png)


然后提交给了另外一个fork,那个大佬已经

**Comment by Akkariiin** [comment]
试试看
https://ci.appveyor.com/project/AkaneAkaza/shadowsocksr-csharp/builds/24528373/job/wy28xlkbumenj4om/artifacts
