### ISSUE TITLE
影响网络认证

### ISSUE THREAD

**Issue by Fluentlycc** [shadowsocksrr/shadowsocksr-csharp#162]
我用校园网需要认证，然而用了软件之后，开机认证页面无法打开，无法认证，只有当我打开软件才能打开认证页面

**Comment by devount** [comment]
因为该软件会在本地建立一个代理服务器，且在退出软件时会自动清除该代理，但如果你关机时没有正常退出软件，这个代理服务器不会被清除，导致你下次开机且没有打开软件时流量依然走代理，但由于软件没运行，所以也自然无法上网，包括打开认证网页。
解决办法为关机前先退出软件，清除本地代理服务器；或者开机后再打开一次软件，建立代理链接。



devount@qq.com
 
发件人： Fluentlycc
发送时间： 2018-12-05 16:33
收件人： shadowsocksrr/shadowsocksr-csharp
抄送： Subscribed
主题： [shadowsocksrr/shadowsocksr-csharp] 影响网络认证 (#162)
我用校园网需要认证，然而用了软件之后，开机认证页面无法打开，无法认证，只有当我打开软件才能打开认证页面

**Comment by Fluentlycc** [comment]
好的，谢谢，麻烦了。
试了几次果然这样。
QQ邮箱又不能回复，
为自己的无知流下了悔恨的眼泪
