### ISSUE TITLE
shadowsockesr 更新pac报异常

### ISSUE THREAD

**Issue by jekoie** [shadowsocksrr/shadowsocksr-csharp#165]
1.客户端更新  “更新PAC为GFWList“” 时，windows10 系统报错！
2.在 “ShadowsocksR-win-4.9.0\temp\shadowsocks_2018-12.log”  日志下可以看到软件异常信息

info as below:

**[2018-12-25 15:07:28] [Info] Connect raw.githubusercontent.com:443
[2018-12-25 15:07:28] [Info] Connect raw.githubusercontent.com:443
[2018-12-25 15:07:28] [Info] Connect raw.githubusercontent.com:443
[2018-12-25 15:07:28] [Info] Disconnect raw.githubusercontent.com:443
[2018-12-25 15:07:28] [Error] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 连接被意外关闭。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-12-25 15:07:37] [Info] Connect raw.githubusercontent.com:443
[2018-12-25 15:07:37] [Info] Connect raw.githubusercontent.com:443
[2018-12-25 15:07:37] [Info] Connect raw.githubusercontent.com:443
[2018-12-25 15:07:37] [Info] Disconnect raw.githubusercontent.com:443
[2018-12-25 15:07:37] [Info] Connect raw.githubusercontent.com:443**

**Comment by 275761919** [comment]
我的是
```
[2019-02-18 14:28:59] [Error] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by BedivereZero** [comment]
`View\MenuViewController.cs` line 1146:

```c#
private void UpdatePACFromCNIPListItem_Click(object sender, EventArgs e)
{
controller.UpdatePACFromOnlinePac("https://raw.githubusercontent.com/shadowsocksrr/breakwa11.github.io/master/ssr/ss_cnip.pac");
}
```

这里使用的是原项目的地址，所以失败了

**Comment by bianliangpai** [comment]
> `View\MenuViewController.cs` line 1146:
> 
> ```cs
> private void UpdatePACFromCNIPListItem_Click(object sender, EventArgs e)
> {
> controller.UpdatePACFromOnlinePac("https://raw.githubusercontent.com/shadowsocksrr/breakwa11.github.io/master/ssr/ss_cnip.pac");
> }
> ```
> 
> 这里使用的是原项目的地址，所以失败了

@BedivereZero 请问这个问题要如何解决呢？看起来需要重新编译才能更换地址？新的地址是什么呢？

**Comment by bianliangpai** [comment]
[2020-06-03 11:35:39] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.RspHttpHandshakeReceive()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive()
[2020-06-03 11:35:39] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.RspHttpHandshakeReceive()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive()
[2020-06-03 11:35:39] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.RspHttpHandshakeReceive()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive()
[2020-06-03 11:35:39] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.RspHttpHandshakeReceive()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive()
[2020-06-03 11:35:39] [Error] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 连接被意外关闭。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)

我这边在选择“更新PAC为GFWList”时，日志里的报错比较接近，不知道是否属于同一个问题？

**Comment by jekoie** [comment]
不用这个了，用V2Ray了
