### ISSUE TITLE
win10使用SSR从国外连接回国内失败

### ISSUE THREAD

**Issue by zhujinyao822** [shadowsocksrr/shadowsocksr-csharp#166]
开发者您好，我目前在国外，在电脑使用SSR尝试回国（个人需求），但是失败了。请问是什么原因造成的？劳烦您花一点时间帮忙解决一下这个问题，谢谢。

## win10版本
![image](https://user-images.githubusercontent.com/34890562/50595895-47ff8480-0edd-11e9-81cc-bab07c1c4207.png)

## ssr版本
![image](https://user-images.githubusercontent.com/34890562/50596046-d83dc980-0edd-11e9-820f-5ec5b12c82c5.png)

## ssr配置
![image](https://user-images.githubusercontent.com/34890562/50596088-fc010f80-0edd-11e9-9ab5-f6dc744a45eb.png)

## 其他说明
Windows自带防火墙已全关
我试过了PAC模式和全局模式，以及执行过下列更新选项：
![image](https://user-images.githubusercontent.com/34890562/50596163-47b3b900-0ede-11e9-80ac-aefdf99104b3.png)
测IP地址时仍然无法定位到国内

## 期待结果
使电脑ip地址回国

## 特别说明
我在公司的win7电脑使用SSR，同是这一台服务器，使用`PAC模式`，PAC选择`绕过局域网IP`，代理规则选`绕过局域网`，ip可以顺利回国。
我的小米手机使用SSR移动版，同是这一台服务器，代理模式选择`全局模式`，ip可以顺利回国

**Comment by zhujinyao822** [comment]
漏了这个截图，补上
![image](https://user-images.githubusercontent.com/34890562/50596658-f278a700-0edf-11e9-9aa7-2ff40fc967ce.png)

**Comment by ShallowAi** [comment]
开启全局模式后，请将代理规则更改为绕过国外而非默认的绕过国内和局域网。

**Comment by zhujinyao822** [comment]
> 开启全局模式后，请将代理规则更改为绕过国外而非默认的绕过国内和局域网。

我开启全局模式后，将`代理模式`的各项都试过仍然无法成功
![image](https://user-images.githubusercontent.com/34890562/51663124-d8b71500-1ff0-11e9-97fa-8681705f7802.png)

**Comment by Mifan426** [comment]
win10设置里，网络，代理，把手动关上

**Comment by zhujinyao822** [comment]
> win10设置里，网络，代理，把手动关上

你好，我计算机的网络设置是这样的，关了仍然不行
![image](https://user-images.githubusercontent.com/34890562/53694678-407d2e80-3ded-11e9-8dce-bb1811e010e8.png)

**Comment by Justsoos** [comment]
上chrome，关闭prefetch，用SwitchyOmega插件指定代理域名或全局，关掉ssr全局和pac。
再测

**Comment by zhujinyao822** [comment]
> 上chrome，关闭prefetch，用SwitchyOmega插件指定代理域名或全局，关掉ssr全局和pac。
> 再测

尝试了，仍然不行。

网上也找过很多方法，就是不知道为什么手机没有问题，电脑却无法生效。
放弃折腾了，感谢各位提出的方案。

**Comment by Justsoos** [comment]
你那截图开着负载均衡啊，不是要把自己蠢哭？

**Comment by zhujinyao822** [comment]
> 你那截图开着负载均衡啊，不是要把自己蠢哭？

我之后也尝试过关掉负载均衡，仍然是不行。
唉，我的笔记本怕是有毒。

**Comment by Justsoos** [comment]
据我多年经验，把罪过赖到微软头上的翻墙小白，十个有九个半最后都失败了

**Comment by zhujinyao822** [comment]
今天偶然间发现在谷歌浏览器无痕模式下，我的ssr配置生效了，ip地址变了，
经测试发现，是一个叫`穹顶穿越`的谷歌浏览器插件，导致我在开启代理后，ip地址无法发送切换，
![image](https://user-images.githubusercontent.com/34890562/56302198-ddace000-616b-11e9-8b93-11a0f331d7f1.png)

禁用了这个插件就可以生效了

**Comment by geek377148474** [comment]
> 今天偶然间发现在谷歌浏览器无痕模式下，我的ssr配置生效了，ip地址变了，
> 经测试发现，是一个叫`穹顶穿越`的谷歌浏览器插件，导致我在开启代理后，ip地址无法发送切换，
> ![image](https://user-images.githubusercontent.com/34890562/56302198-ddace000-616b-11e9-8b93-11a0f331d7f1.png)
> 
> 禁用了这个插件就可以生效了

我今天也是遇到这个问题，我翻墙了好几台服务器都不成功，最后忘了我之前用过翻墙谷歌插件导致的问题。之前我还会禁用掉，今天总算想起来了，禁用同样会影响到翻墙的工具，改变切换的这个工具，就解决问题了
