### ISSUE TITLE
Disable HTTP proxy before exiting.

### ISSUE THREAD

**Issue by pthfdr-42** [shadowsocksrr/shadowsocksr-csharp#167]
As the title said. When the application is terminated, you should revert the changes made to IE proxy settings.
Most of the users directly shut down the PC without reverting the settings, and when turning the PC back on, it is still configured to use a (non-existent) proxy.
The problem is more serious when you have to use a login page to access the Internet (many college broadbands do this) which demands direct connection.

**Comment by johnx7271** [comment]
I noticed that sporadically the Win-inet setting is not restored upon application exit. I haven't figured out how it happens. I guess it may be related to incorrect treatment with pc hibernation. One clue is, I did not find this issue in the non-ssr version, so by comparing with the code of that version, it may help to figure out why.
