### ISSUE TITLE
关于订阅更新遗漏节点的问题

### ISSUE THREAD

**Issue by CyshallChan** [shadowsocksrr/shadowsocksr-csharp#17]
4.8就有遗漏节点的问题，4.8.1还是遗漏节点诶。

**Comment by idenpa** [comment]
+1 官方从4.4.5之后的版本就有订阅节点只有一部分的这个问题，希望可以修复下，谢谢

**Comment by 1157173310** [comment]
我记得这个应该是链接不符合规范的问题吧，自从ssr更新某一版本后很多原有链接都不能用了

**Comment by AspirinGeyer** [comment]
你看一下你的订阅接口返回的数据中的第一行有没有 `MAX=n` (n 是一个任意的数字)
如果有的话，这是客户端订阅的一个功能，客户端会随机取 n 条。

参考 [Subscribe 服务器订阅接口文档](https://github.com/shadowsocksrr/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)

**Comment by idenpa** [comment]
@AspirinGeyer 看了下这边遗漏的订阅链接 max=26 但是实际上更新的条数比这个要少 并没有超过

**Comment by ssrpanel** [comment]
@idenpa 这个并非客户端的问题，而是订阅地址仅返回那么多条。
