### ISSUE TITLE
访问FACEBOOK，只显示文字，不显示图片，里面的详情页打不开

### ISSUE THREAD

**Issue by XIONGXIONG763284** [shadowsocksrr/shadowsocksr-csharp#170]
访问FACEBOOK，只显示文字，不显示图片，里面的详情页打不开，其他网站可以正常访问，请问这是什么问题呢？
1. 防火墙已关
2.WIN7 64位系统
3.客户端版本：5.1.5
以下图片为LOG，和混淆等信息截图
![log](https://user-images.githubusercontent.com/46477228/50876629-07d26180-1409-11e9-9401-116b6a65e78c.png)
![pac](https://user-images.githubusercontent.com/46477228/50876635-0c971580-1409-11e9-9c86-6148fe207ed7.png)
![default](https://user-images.githubusercontent.com/46477228/50876637-115bc980-1409-11e9-8aa4-7fd02665642a.png)
![default](https://user-images.githubusercontent.com/46477228/50876639-1587e700-1409-11e9-8cbf-60ff1226ad63.png)
![default](https://user-images.githubusercontent.com/46477228/50876645-19b40480-1409-11e9-98fc-57d00f1dea46.png)
![default](https://user-images.githubusercontent.com/46477228/50876647-1d478b80-1409-11e9-9d14-e4bcb23eb730.png)
![default](https://user-images.githubusercontent.com/46477228/50876656-2173a900-1409-11e9-96b4-b14c64d15e42.png)
![default](https://user-images.githubusercontent.com/46477228/50876658-246e9980-1409-11e9-91ac-159f6df0108f.png)
![facebook](https://user-images.githubusercontent.com/46477228/50876689-554ece80-1409-11e9-9d66-7443ddb1d30e.png)

**Comment by uloveme** [comment]
你的版本怎么有5.1.5了，哪下载的

**Comment by uloveme** [comment]
火狐浏览器下载一个拓展，facebook全局代理，我的是老版本，用的
https://github.com/hrimfaxi/autoproxy-ng
新版本switchyomage，这个在chrome上非常好用，哪个域名没有加载，会提示
我不习惯火狐新版本，不知道在火狐新版本上体验如何

**Comment by dayuan819** [comment]
我也不记得哪下载的了，现在我的也不是很稳定

uloveme <notifications@github.com> 于2019年1月18日周五 上午8:17写道：

**Comment by Akkariiin** [comment]
代理规则设置成 绕过局域网 试试看

**Comment by Jothan01** [comment]
> 访问FACEBOOK，只显示文字，不显示图片，里面的详情页打不开，其他网站可以正常访问，请问这是什么问题呢？
> 
> 1. 防火墙已关
>    2.WIN7 64位系统
>    3.客户端版本：5.1.5
>    以下图片为LOG，和混淆等信息截图
>    ![log](https://user-images.githubusercontent.com/46477228/50876629-07d26180-1409-11e9-9401-116b6a65e78c.png)
>    ![pac](https://user-images.githubusercontent.com/46477228/50876635-0c971580-1409-11e9-9c86-6148fe207ed7.png)
>    ![default](https://user-images.githubusercontent.com/46477228/50876637-115bc980-1409-11e9-8aa4-7fd02665642a.png)
>    ![default](https://user-images.githubusercontent.com/46477228/50876639-1587e700-1409-11e9-8cbf-60ff1226ad63.png)
>    ![default](https://user-images.githubusercontent.com/46477228/50876645-19b40480-1409-11e9-98fc-57d00f1dea46.png)
>    ![default](https://user-images.githubusercontent.com/46477228/50876647-1d478b80-1409-11e9-9d14-e4bcb23eb730.png)
>    ![default](https://user-images.githubusercontent.com/46477228/50876656-2173a900-1409-11e9-96b4-b14c64d15e42.png)
>    ![default](https://user-images.githubusercontent.com/46477228/50876658-246e9980-1409-11e9-91ac-159f6df0108f.png)
>    ![facebook](https://user-images.githubusercontent.com/46477228/50876689-554ece80-1409-11e9-9d66-7443ddb1d30e.png)
 你解决你的问题了吗我也是一样问题
