### ISSUE TITLE
请问关于基于IP协议的proxy是否可行

### ISSUE THREAD

**Issue by FAAAAT** [shadowsocksrr/shadowsocksr-csharp#175]
过年这几天两台vps被封了tcp 很心塞。 不甘心查了很多资料  发现IP层支持很多协议。

想问下使用其他协议开发代理的可行性。比如RUDP QUIC SCTP ITU等等等等  而且看起来很多协议和tcp协议的功能都很相近。

就是不知道GFW是不是严格限制了只有TCP和UDP才能连接。。。

**Comment by Akkariiin** [comment]
当然可以试试看，这是个好思路
