### ISSUE TITLE
直连模式是否会影响网络

### ISSUE THREAD

**Issue by bluesky-dark** [shadowsocksrr/shadowsocksr-csharp#176]
使用直连模式（ssr设置）访问网页时有时会提示检测到网络变化（国外更频繁），并且有时加载缓慢，国内外网站都有此现象（用了SwitchyOmega，国内网站显示直接连接），退了ssr此现象就消失
IP地址显示是国内，speedtest测速 下行90mbps 上行21mbps
尝试了重插网线，重新连接网络，断开无线连接，更改dns，清除dns缓存，重启ssr，重启电脑
软件版本4.9.0
[shadowsocks_2019-02.log](https://github.com/shadowsocksrr/shadowsocksr-csharp/files/2855870/shadowsocks_2019-02.log)
（log是temp文件夹里的吗）
另外昨天看国内视频网站视频时频繁缓冲（不知道是不是ISP的问题），访问Google时显示证书问题（不知道是不是服务器的问题）

**Comment by Akkariiin** [comment]
关掉系统代理，关掉负载均衡/服务器自动切换

**Comment by Snylonue** [comment]
也就是说这是服务器的问题了？

**Comment by bluesky-dark** [comment]
更新到4.9.2后似乎好了

**Comment by michaelzs1994** [comment]
> 更新到4.9.2后似乎好了

我现在4.9.2也出现了你一样的问题，哥们。你后来怎么解决的啊，500m的宽带，看视频现在一卡一卡的，崩溃了
