### ISSUE TITLE
不允许所请求的注册表访问权

### ISSUE THREAD

**Issue by piyrw520** [shadowsocksrr/shadowsocksr-csharp#177]
[2019-02-17 18:22:46] ShadowsocksR started on port 1080
[2019-02-17 18:22:46] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main(String[] args)
失败的程序集的区域是:
MyComputer
[2019-02-17 18:22:46] [Info] Connect n55.pw:443
[2019-02-17 18:22:48] [Info] Connect yingyun.me:443
[2019-02-17 18:22:52] ShadowsocksR started on port 1080

用着用着就这样了   

怎么办啊

**Comment by yang316910** [comment]
你的问题解决了吗?我现在也是这样，打开就崩溃

**Comment by piyrw520** [comment]
没有，好像是360的原因。估计要重新装系统才行

yang316910 <notifications@github.com> 于2019年5月4日周六 下午5:38写道：

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/212#issuecomment-491777983
