### ISSUE TITLE
System.UnauthorizedAccessException: 尝试执行未经授权的操作

### ISSUE THREAD

**Issue by Xxf9126** [shadowsocksrr/shadowsocksr-csharp#178]
能够正常更新服务订阅
防火墙都关了
以管理员运行该程序 
启动后日志就报以下错误：
[2019-02-21 11:44:07] [Error] System.UnauthorizedAccessException: 尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Shadowsocks.Controller.SystemProxy.RegistrySetValue(RegistryKey registry, String name, Object value)

使用不了 求大佬解决

**Comment by Xxf9126** [comment]
![image](https://user-images.githubusercontent.com/47099845/53142819-4181b500-35d0-11e9-985f-6738365f475d.png)

**Comment by WindAndTear** [comment]
你这个问题解决了么

**Comment by Akkariiin** [comment]
看起来是没有足够的权限
试试系统代理模式 选 保持当前状态不变
