### ISSUE TITLE
Windows版使用问题

### ISSUE THREAD

**Issue by verdi0n** [shadowsocksrr/shadowsocksr-csharp#179]
使用很久  但是感觉对桌面版及其不友好，我想提点建议。  Windows版软件切换节点不能直接在软件主界面点击确定键 ——这样不起作用，不能切换节点。如果切换还需要右击任务栏在服务器选项中选择节点。
  另一个就是右击任务栏 ——服务器——选择节点的时候不能使用鼠标滚轮，必须上下点击箭头。才能选择。这样对于有很多节点的用户很不友好   切换节点可能需要点击及时下鼠标。
   我不知道这样切实的问题为什么没有人提出来。我从用户的角度说出以上的心里话，同时也希望软件变得更好，希望作者能看见吧 。

**Comment by verdi0n** [comment]
![snipaste_2019-02-23_01-05-01](https://user-images.githubusercontent.com/17640255/53258315-4ac16d80-3707-11e9-97cc-db0b5565e69e.png)
![snipaste_2019-02-23_01-06-36](https://user-images.githubusercontent.com/17640255/53258321-4e54f480-3707-11e9-97d8-e89b461c3b1a.png)

**Comment by Qixingchen** [comment]
请使用中键点击任务栏图标(或者服务器-服务器连接统计)调出服务器记录页面

**Comment by hineH** [comment]
附议。同样希望这样改进。主界面选中希望可用切换服务器。鼠标中键。。。你让我这种鼠标没有中键*surface Arc*用户表示很尴尬啊(

**Comment by wangrush** [comment]
ctrl+左键  和中键效果是一样的

**Comment by hineH** [comment]
> ctrl+左键 和中键效果是一样的

Thanks. 我一直都不知道，火星了。

**Comment by Justsoos** [comment]
原版ss更难用。。。。破娃版ssr算是重大改进，加了一大套监控数据界面。
和ss社区提过，那官僚扯皮劲头… 呵呵，一个社区不如一个开发人员
