### ISSUE TITLE
需求：能否将transfer_log.json移至temp文件夹内？

### ISSUE THREAD

**Issue by ustczzh** [shadowsocksrr/shadowsocksr-csharp#18]
版本4.8.1
需求：能否将transfer_log.json移至temp文件夹内？
应用场景：几台电脑通过坚果云随时同步ShadowsocksR主目录，这样可以保持user-rule.txt和pac.txt同步更新。但同时禁用了temp目录的同步，因为log文件在不断更新。这时，主目录中的transfer_log.json也会不断更新，导致坚果云不停提示“transfer_log.json文件已更新”，而且不同电脑同时使用时，还会产生冲突文件。

其实，transfer_log.json并不影响程序功能，放入temp文件夹内应该没有影响吧？

**Comment by Akkariiin** [comment]
我记得配置文件的加解密会涉及到这个文件

**Comment by ustczzh** [comment]
这个里面好像就是一些流量统计。
{
	"104.xxx.xxx.xx" : {
		"totalUploadBytes" : 8236000,
		"totalDownloadBytes" : 264898269
	},
}

**Comment by Akkariiin** [comment]
#20
