### ISSUE TITLE
[Info] Proxy server AddressAlreadyInUse:一次只能用一個通訊端位址 (通訊協定/網路位址/連接埠)。

### ISSUE THREAD

**Issue by johnnyga001** [shadowsocksrr/shadowsocksr-csharp#180]
在看網頁的時候會跳出:Proxy 伺服器發生錯誤，或是位址不正確。ERR_PROXY_CONNECTION_FAILED

有時侯f5幾次就好,有時候就長時間都不行，

看log就是出現標題的那一句，

有室友也是跟我用同一個server同一個isp,但他完全沒問題。

**Comment by wangrush** [comment]
我的也有一样的问题  我这边是用SwitchyOmega切换下模式就好了

**Comment by Akkariiin** [comment]
是本地有其他程序在竞争这个端口吧？
检查一下同时运行的其他程序，或者换一个本地端口
