### ISSUE TITLE
服务器TLS1.2+导致订阅失败 

### ISSUE THREAD

**Issue by vangork** [shadowsocksrr/shadowsocksr-csharp#181]
更新订阅总是失败，错误“服务器订阅xxxx更新失败”

debug进入此异常，ex.message=“请求被中止: 未能创建 SSL/TLS 安全通道 ”
private void http_DownloadStringCompleted(object sender, DownloadStringCompletedEventArgs e)
        {
            。。。
            catch (Exception ex)
            {
                if (e.Error != null)
                {
                    Logging.Debug(e.Error.ToString());
                }
                Logging.Debug(ex.ToString());
                if (NewFreeNodeFound != null)
                {
                    NewFreeNodeFound(this, new EventArgs());
                }
                return;
            }
        }

造成此问题是由于服务器只支持tls1.2+的https的链接。

解决方案为：在CheckUpdate函数指定加密协议为tls1.2
.net 4.0 为ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
.net 4.5 为ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

public void CheckUpdate(Configuration config, ServerSubscribe subscribeTask, bool use_proxy, bool noitify)
        {
            FreeNodeResult = null;
            this.noitify = noitify;
            try
            {
                WebClient http = new WebClient();
                http.Headers.Add("User-Agent",
                    String.IsNullOrEmpty(config.proxyUserAgent) ?
                    "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36"
                    : config.proxyUserAgent);
                http.QueryString["rnd"] = Util.Utils.RandUInt32().ToString();
                
//指定链接协议
ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
                
               。。。。。。
            }
            catch (Exception e)
            {
                Logging.LogUsefulException(e);
            }
        }

考虑到兼容性，希望作者可以完善代码，fix这个问题。

**Comment by AspirinGeyer** [comment]
从 master 拉取一下最新版的代码，然后在 `.NET Framework 4.5+` 的环境下重新构建应该可以解决这个问题。

**Comment by vangork** [comment]
> 从 master 拉取一下最新版的代码，然后在 `.NET Framework 4.5+` 的环境下重新构建应该可以解决这个问题。
> 
> 目前 release 里面最新的版本还是 2017 年，一些修改没有加进去。

测试了，似乎master分支最新commit没有解决这个问题。另外，这个commit存在托盘图标消失的问题，在win10上是空的，右键依然可以点击设置，在xp上，任务栏则无法找到小飞机，望修复。

**Comment by vangork** [comment]
最新的commit修复内存泄露的地方有bug，MenuViewController.cs这样改可fix：
```
try
            {
                Bitmap icon = new Bitmap("icon.png");
                Icon newIcon = Icon.FromHandle(icon.GetHicon());
                icon.Dispose();
                _notifyIcon.Icon = newIcon;
            }
            catch
            {
                。。。
                Bitmap iconCopy = new Bitmap(icon);
                for (int x = 0; x < iconCopy.Width; x++)
                {
                    for (int y = 0; y < iconCopy.Height; y++)
                    {
                        Color color = icon.GetPixel(x, y);
                        iconCopy.SetPixel(x, y,

                            Color.FromArgb((byte)(color.A * mul_a),
                            ((byte)(color.R * mul_r)),
                            ((byte)(color.G * mul_g)),
                            ((byte)(color.B * mul_b))));
                    }
                }
                Icon newIcon = Icon.FromHandle(iconCopy.GetHicon());
                icon.Dispose();
                iconCopy.Dispose();

                _notifyIcon.Icon = newIcon;
            }
```

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr/releases
