### ISSUE TITLE
编译最新dev版切换代理模式后托盘图标消失

### ISSUE THREAD

**Issue by mxdh** [shadowsocksrr/shadowsocksr-csharp#183]
客户端：最新dev版编译
系统：windows7
切换模式后托盘图标消失，切换回来之后仍然看不见图标
![tim 20190306090628](https://user-images.githubusercontent.com/20399194/53848416-36c31900-3fef-11e9-944e-76265bade7d2.png)

会不会是我编译错了？

[ShadowsocksR.zip](https://github.com/shadowsocksrr/shadowsocksr-csharp/files/2933851/ShadowsocksR.zip)

**Comment by vangork** [comment]
I have the same problem

**Comment by liumingye** [comment]
I have the same problem

**Comment by vangork** [comment]
最新的commit修复内存泄露的地方有bug，MenuViewController.cs这样改可fix：
try
            {
                Bitmap icon = new Bitmap("icon.png");
                Icon newIcon = Icon.FromHandle(icon.GetHicon());
                icon.Dispose();
                _notifyIcon.Icon = newIcon;
            }
            catch
            {
                。。。
                Bitmap iconCopy = new Bitmap(icon);
                for (int x = 0; x < iconCopy.Width; x++)
                {
                    for (int y = 0; y < iconCopy.Height; y++)
                    {
                        Color color = icon.GetPixel(x, y);
                        iconCopy.SetPixel(x, y,

                            Color.FromArgb((byte)(color.A * mul_a),
                            ((byte)(color.R * mul_r)),
                            ((byte)(color.G * mul_g)),
                            ((byte)(color.B * mul_b))));
                    }
                }
                Icon newIcon = Icon.FromHandle(iconCopy.GetHicon());
                icon.Dispose();
                iconCopy.Dispose();

                _notifyIcon.Icon = newIcon;
            }

**Comment by mxdh** [comment]
@vangork 你能创建一个PR吗？
不过作者似乎已经好久没接受PR了。。。
这项目也算早就废了。。。

**Comment by vangork** [comment]
@mxdh 给我个邮箱，我发给你我编译的文件。tls1.2不支持和图标消失的问题，我都fix了。

**Comment by mxdh** [comment]
@vangork a27573@outlook.com

**Comment by vangork** [comment]
@mxdh 只要喜欢 年纪不是问题

**Comment by Akkariiin** [comment]
来个PR呀

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-csharp/pull/186
merged.
