### ISSUE TITLE
星号显示对IPV6无效

### ISSUE THREAD

**Issue by leoxxx** [shadowsocksrr/shadowsocksr-csharp#19]
左边框照样显示，只是在IPV6两边加了括号。

**Comment by Akkariiin** [comment]
能说得更清楚些吗？

**Comment by leoxxx** [comment]
比如：127.0.0.1:1234
左边列表示会显示成*.1:1234
0:0:0:0:0:0:7f00:1:1234
左边列表显示[0:0:0:0:0:0:7f00:1]:1234

**Comment by Akkariiin** [comment]
哦，你是说服务器配置界面隐藏服务器地址的那个逻辑么，好的，会在之后修复
