### ISSUE TITLE
shadowsocks 错误 端口已被占用 1080

### ISSUE THREAD

**Issue by anyclub** [shadowsocksrr/shadowsocksr-csharp#190]
shadowsocks 错误 端口已被占用 1080

重启,重置网络连接等手段均无效

netstat -aon|findstr "1080" 查询为空

问题的产生原因....
同事把插线板线踢到了,然后再次开机就如此了

求解决方案

**Comment by Akkariiin** [comment]
摊手

**Comment by jasonliul** [comment]
https://www.nirsoft.net/utils/cports.html
检查端口占用.

比较可能是硬件厂家的无谓程序, 例如IBM, 占用1080端口.

请勿杯弓蛇影, 疑人盗斧.
