### ISSUE TITLE
4.9.1版本频繁报NullReferenceException

### ISSUE THREAD

**Issue by zyOverture** [shadowsocksrr/shadowsocksr-csharp#191]
这个报错有点多，不过暂时没有感觉到会影响使用，只是反馈一下。

我配置的是系统全局代理 然后代理规则选绕过局域网和大陆 
选项里面勾选了切换服务器自动断连，打印日志。
配置了dns和local dns。
其他的都是默认，没开负载均衡。

[2019-04-20 00:06:58] [Info] Connect mtalk.google.com:5228 via 47.244.138.132:56200
[2019-04-20 00:06:58] [Info] DNS nolock query mtalk.google.com answer 74.125.23.188
[2019-04-20 00:06:58] [Info] Disconnect 74.125.23.188:5228
[2019-04-20 00:07:04] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive3Callback(Int32 recv_size)
[2019-04-20 00:07:04] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive3Callback(Int32 recv_size)
[2019-04-20 00:07:04] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive3Callback(Int32 recv_size)
[2019-04-20 00:07:04] [Info] Connect mobile.pipe.aria.microsoft.com:443 via 47.244.138.132:56200
[2019-04-20 00:07:04] [Info] DNS nolock query mobile.pipe.aria.microsoft.com answer 52.114.132.73
[2019-04-20 00:07:05] [Info] Connect mobile.pipe.aria.microsoft.com:443 via 47.244.138.132:56200
[2019-04-20 00:07:05] [Info] DNS nolock query mobile.pipe.aria.microsoft.com answer 52.114.132.73
[2019-04-20 00:07:06] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive3Callback(Int32 recv_size)
[2019-04-20 00:07:06] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive3Callback(Int32 recv_size)
[2019-04-20 00:07:06] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive3Callback(Int32 recv_size)
[2019-04-20 00:07:10] [Info] Disconnect 52.114.132.73:443
[2019-04-20 00:07:10] [Info] Disconnect 52.114.132.73:443

**Comment by Akkariiin** [comment]
试试4.9.2

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr-csharp/blob/2dc226892b31cf88b4228593cdb4dfcd904ed470/shadowsocks-csharp/Util/Util.cs#L330-L340
看到引发问题的代码了

这个 ret_ipAddress 好像一直是空的

**Comment by Akkariiin** [comment]
看起来是查询失败导致的问题
能提供一下dns填的是什么吗

**Comment by vangork** [comment]
@Akkariiin 我今天也遇到这个问题，debug了一下，这个问题产生的原因是：
如果DNS解析失败，那么以下ret_ipAddress返回为Null:
ret_ipAddress = _QueryDns(host, dns_servers, IPv6_first);

于是执行到这一行的时候调用ret_ipAddress.ToString()会报exception。
Logging.Info($"DNS query {host} answer {ret_ipAddress.ToString()}"); 

个人意见和建议：
不一定是个issue需要fix，但是可以考虑日志记录host，供user参考。

**Comment by Akkariiin** [comment]
@vangork OK,我了解了 感谢~

**Comment by Akkariiin** [comment]
https://ci.appveyor.com/project/Akkariiin/shadowsocksr-csharp/builds/24013791/job/e9hq833g1a8oq2cg/artifacts
可以试试这个版本

**Comment by zyOverture** [comment]
我填写的dns是8.8.8.8,8.8.4.4   然后local dns是114.114.114.114,180.76.76.76
