### ISSUE TITLE
怎么重新生成ssr链接与二维码

### ISSUE THREAD

**Issue by vtroisWhite** [shadowsocksrr/shadowsocksr-csharp#197]
在安装完成ssr的时候，控制台打印的日志中会有ssr链接，就是可以直接通过剪贴板导入的那个链接，同时在根目录也有个二维码。但是在我修改了ssr参数并重启后二维码没有更新，base64加密后的ssr链接也改变了，所以想要问问生成这两个的命令是什么。

**Comment by Akkariiin** [comment]
唔？每个字都认识，合起来没看懂什么意思

**Comment by Akkariiin** [comment]
能提供详细的信息吗？

**Comment by vtroisWhite** [comment]
![image](https://user-images.githubusercontent.com/43694044/56498316-b2dbd680-6533-11e9-81d4-3d614920f096.png)
当我安装完ssr后生成了ssr链接与二维码，但当我修改了密码、协议等参数后链接与二维码该如何重新生成呢

**Comment by Akkariiin** [comment]
我这里好像没有这个功能呀
要不你问问你的一键脚本提供方，这个功能看起来是一键部署脚本提供的

**Comment by niziming** [comment]
我已经问了秋水了,还没回复我
