### ISSUE TITLE
问题反馈+功能讨论

### ISSUE THREAD

**Issue by BlackConnor** [shadowsocksrr/shadowsocksr-csharp#198]
OS：Win7 旗舰版SP1
SSR：4.9.2
潜在问题反馈：
+ `断开当前所有连接`功能似乎无效。点击之后，依然可以浏览某些网站。`绕过局域网和大陆`与`全局`均试过。
+ `自定义生成二维码`功能输入汉字。使用手机扫描显示乱码。
+ `设置客户端密码`功能界面提示缺失，汉化不完整，影响美观。

功能讨论：
+ `自定义生成二维码`使用频率是否较多？是否有存在必要。
+ `设置客户端密码`使用频率是否较多？是否有存在必要。
+ `捐助`功能是否有存在必要。汉化不完整，影响美观。
+ `关于`功能链接失效，是否可以更换原作者新页面。

当然，这一切只是本人对此软件的不成熟讨论，若有冒犯，还望海涵。如果引起不正当言论，本人或者有劳管理人员删除此问题。祝各位事业顺利。

**Comment by Akkariiin** [comment]
断开当前所有连接的作用是，在手动切换服务器时，断开还连接在之前服务器上的连接
这个功能的典型场景是：在浏览网页或者播放YTB时，发现服务器特别慢，然后需要手动切换服务器，但是因为之前的连接还在加载中，或者因为keep-alive导致页面刷新时从用之前的连接；在之前，遇到这个问题时需要手动强制刷新页面或者在统计界面上手动双击断开之前的服务器连接。
如果想要测试这个功能的话，只要看切换服务器的时候网页的加载会不会被中断，就可以知道是不是有在正确工作了。

<hr/>

自定义生成二维码只是测试用，真正使用应该很少用
捐助按钮我懒得删除了
关于也懒得弄，咕咕咕

<hr/>

当然，欢迎大家像这样和平地提出意见
