### ISSUE TITLE
可以设置不自动记录log吗？

### ISSUE THREAD

**Issue by jang-u** [shadowsocksrr/shadowsocksr-csharp#20]
temp目录下的log文件，日期、时间、连接网址...写的一清二楚
怎么能不自动记录日志？
谢谢

**Comment by Akkariiin** [comment]
稍后会调查一下

我记得配置文件的加解密与log文件有关。

**Comment by Akkariiin** [comment]
看看能不能添加移走或者关掉这个log的功能。
合并#18和#20

**Comment by jang-u** [comment]
4.9仍然记录详细log

**Comment by Akkariiin** [comment]
这个feature的优先级比较低，所以不要急

**Comment by Riajyuu** [comment]
@Akkariiin 我现在尝试把软件丢到网盘里面去运行（出于公司跟家里的同步需要）
然后OneDrive就会一直告诉我文件被占用无法同步，用久了我还得手动清理一次，不然浪费空间。。。。

**Comment by Ngakt** [comment]
貌似这个日志是随时写入，不是缓冲写入的，对固态写放大伤害是不是比较大……

**Comment by Riajyuu** [comment]
@Ngakt 
![image](https://user-images.githubusercontent.com/16912240/52542055-f0571180-2dd6-11e9-9bac-f5a5344b357b.png)

**Comment by Ngakt** [comment]
> @Ngakt
> ![image](https://user-images.githubusercontent.com/16912240/52542055-f0571180-2dd6-11e9-9bac-f5a5344b357b.png)

？？好吧，确实是我当时多心叻，固态姑且还是撑用的，，，不过常用的话一个10M甚至9M的LOG文件还是挺难受的，还是希望能关掉

**Comment by Riajyuu** [comment]
```
@echo off
taskkill /f /im ShadowsocksR.exe
taskkill /f /im ../ShadowsocksR.exe
timeout /t 10
del /S /Q *.log
timeout /t 10
start ../ShadowsocksR.exe
```

**Comment by Akkariiin** [comment]
请用最新版
https://github.com/shadowsocksrr/shadowsocksr-csharp/releases
