### ISSUE TITLE
托盘菜单被Windows状态栏遮挡

### ISSUE THREAD

**Issue by xatec** [shadowsocksrr/shadowsocksr-csharp#202]
SSR C# 版本：
https://github.com/shadowsocksrr/shadowsocksr-csharp/commit/2dc226892b31cf88b4228593cdb4dfcd904ed470

操作系统：
Windows10 1903

问题：

在某些特定情况下（不容易复现），“退出”将会被Windows状态栏遮挡，当再次右键托盘图标时，“退出”按钮才会出现。

![https://i.loli.net/2019/04/24/5cbfe5894c58c.png](https://i.loli.net/2019/04/24/5cbfe5894c58c.png)

**Comment by Akkariiin** [comment]
我记得这个是本地程序的问题
其他程序如果有托盘菜单也会出现这个问题

大致原因应该是有其他程序或者注入在explorer.exe中的dll在显示菜单之后唤起/激活了任务栏
以前在win7中就有出现过
