### ISSUE TITLE
关于“帮助\检测更新”等相关建议

### ISSUE THREAD

**Issue by vinswu** [shadowsocksrr/shadowsocksr-csharp#206]
### 几点建议

1、检测更新是否能添加一个链接到shadowsocksrr的下载页面
2、关于、捐助这两个链接还是指定到breakwa11，是否也修正一下

**Comment by Akkariiin** [comment]
不是很想提供自动更新功能
知道的人自然知道哪里能下载到更新
那些只知道买，买完被骗还要来Issue撒野的家伙最好别找过来

反正捐助现在没人收，无所谓改不改
关于我也不想改，没人知道更好，懒得应付上车举报的家伙

**Comment by Akkariiin** [comment]
特别是捐助这个东西
怎么说呢，金钱交易这个东西，不管怎么做，在一定程度上都是可以追溯的
比如前两天electron-ssr这个事情，其实我挺看好electron-ssr的，真是可惜了

**Comment by Riajyuu** [comment]
您似乎理解错了一点 不提供自动更新并无法隔离您希望隔离的那些人 而且 您现有的issue貌似也佐证了这一点。。。。

**Comment by Akkariiin** [comment]
@Riajyuu 现在已经很少了，我很满足了

**Comment by Akkariiin** [comment]
8天才7个，已经很少了
