### ISSUE TITLE
4.9.2版本客户端代理DNS查询时，使用的DNS服务器IP地址是什么？

### ISSUE THREAD

**Issue by cognize2018** [shadowsocksrr/shadowsocksr-csharp#207]
在4.9.2版本中，“选项设置”中有“DNS”和“递归DNS”两个文本框。
经测试，在不填写“DNS”或者递归“DNS”的情况下，无论选择全局模式还是PAC模式，浏览器均无法访问Google，但telegram设置好127.0.0.1:1080的socks5代理后，可以正常使用。
这说明4.9.2版本的DNS可能存在某些问题。
我的问题是，4.9.2版本客户端代理DNS查询时，使用的DNS服务器IP地址是什么？

**Comment by Akkariiin** [comment]
通过代理发起的请求的DNS查询是交给远端服务器进行的，如果有问题很有可能是服务器端的DNS设置有问题导致的
