### ISSUE TITLE
是否有Linux的版本

### ISSUE THREAD

**Issue by Yakumo-Yukari** [shadowsocksrr/shadowsocksr-csharp#208]
目前有Linux的版本的客户端吗

**Comment by hineH** [comment]
C# for Linux 应该不太行吧。
你应该用原版 或者 隔壁python版+electron客户端

**Comment by lxl6125** [comment]
https://github.com/erguotou520/electron-ssr
了解一下？

**Comment by zhiyuanzhai** [comment]
……就这么关闭了
C# for Linux……没学过C#，所以不知道这个有什么难度
Python版和Electron都用过，感觉都差点意思。Python版功能很齐全，但好像是不支持订阅的（还是我没玩明白？），Electron感觉还在预开发的阶段就夭折了，好多功能都跟不上，比如自定义pac，服务器测速之类。
感觉windows上这个C#版就还很舒服
