### ISSUE TITLE
无法在win10预览版中代理http网页

### ISSUE THREAD

**Issue by FanhuaCloud** [shadowsocksrr/shadowsocksr-csharp#21]
预览版版本号：17025.1000
软件版本号：4.8.1
具体效果显示为通过http代理连接http协议的网页时提示以下信息：

> 该网页无法正常运作
> **** 未发送任何数据。
> ERR_EMPTY_RESPONSE

但是使用安卓客户端一切正常

查看了一下日志，日志里面提示

> [2017-11-03 17:50:11] [Error] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:45674
>    在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
>    在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    在 Shadowsocks.Controller.HttpPortForwarder.Handler.ConnectCallback(IAsyncResult ar)

另：
加密方式:rc4-md5
协议：auth_aes128_sha1
混淆：tls1.2_ticket_fastauth

**Comment by Akkariiin** [comment]
请问是什么浏览器？https网页状况如何？
浏览器的代理设置是怎样的？其他不同域名的网页呢？

**Comment by 1157173310** [comment]
浏览器为基于Chromium的浏览器
https网页访问正常
具体表现为shadowsocksrr开了全局模式之后访问http的网页的直接加载不出来，https的网页一切正常
然后用PAC模式访问被墙的http网站暂时没测试

**Comment by 1157173310** [comment]
现在又可以了，我怀疑是系统的问题

**Comment by Akkariiin** [comment]
Temporarily closed
