### ISSUE TITLE
不允许所请求的注册表访问权

### ISSUE THREAD

**Issue by Iamno0b** [shadowsocksrr/shadowsocksr-csharp#212]
[2019-05-01 20:15:46] [Info] Connect raw.githubusercontent.com:443
[2019-05-01 20:15:46] [Info] Disconnect raw.githubusercontent.com:443
[2019-05-01 20:15:46] [Error] connect to update server error
[2019-05-01 20:15:48] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2019-05-01 20:15:58] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2019-05-01 20:15:58] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2019-05-01 20:16:18] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2019-05-01 20:16:21] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2019-05-01 20:16:41] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2019-05-01 20:19:45] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2019-05-01 20:20:02] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2019-05-01 20:20:23] ShadowsocksR started on port 1080

这里是日志文件，用着用着就出现这个问题，打开软件后就算连上也没法用，节点在手机端测试了，可以使用

**Comment by yang316910** [comment]
你的问题解决了吗?我现在也是这样，打开就崩溃

**Comment by GoogleGFW** [comment]
就是修改系统代理失败了呗 你自己系统的问题

用扩展呗

**Comment by Akkariiin** [comment]
改不了系统代理，检查你的防病毒程序，它干了不该干的事情
或者把系统代理模式设置成```保持当前状态不变```

**Comment by yang316910** [comment]
> 就是修改系统代理失败了呗 你自己系统的问题
> 
> 用扩展呗

小飞机打不开咋设置扩展啊，求教程，崩溃了

**Comment by saalaman** [comment]
求一个具体解决方法，我也是这个日志
