### ISSUE TITLE
退出软件后，win10 电脑，无法在上网了，必须要使用这个软件才可以上网

### ISSUE THREAD

**Issue by JianyuC** [shadowsocksrr/shadowsocksr-csharp#214]
场景描述：
1. 购买使用软件后，我退出这个软件，当前电脑就无法在上网了，必须要使用软件才行；

问题：
我怎么在退出你们这个软件后，能正常使用我一起的网络环境，不影响我以前网络呢，现在使用了你们的软件后，我退出你们软件，自己本地就在也上不了网了，请问如何解决

电脑环境
win10 系统

**Comment by mosdeo** [comment]
我也有這個問題。好像是退出以後，windows 內的 proxy 設定無法自己改回來。

**Comment by wxlg1117** [comment]
系统代理模式选了全局模式后,软件退出后不会清理代理设置;

**Comment by WangHongSen** [comment]
手动修改IE局域网设置改回来

**Comment by 417788939** [comment]
代理设置没有改回来……

**Comment by Akkariiin** [comment]
系统代理没关
