### ISSUE TITLE
一个不算bug的bug...

### ISSUE THREAD

**Issue by wxlg1117** [shadowsocksrr/shadowsocksr-csharp#215]
宽度不够,字段没显示完整;
![Snipaste_2019-05-07_21-54-31](https://user-images.githubusercontent.com/9752596/57275191-54d0f680-70d0-11e9-83ce-08738184c07a.png)

PS:配置宽度为178后显示正常

**Comment by Akkariiin** [comment]
请问是配置哪个宽度？

**Comment by Akkariiin** [comment]
干脆调自动了，不知道高分屏会不会又出问题

**Comment by Akkariiin** [comment]
试试看
https://ci.appveyor.com/project/AkaneAkaza/shadowsocksr-csharp/builds/24500000/job/d1kp2tc94xu0th5j/artifacts

**Comment by wxlg1117** [comment]
调自动ok的,我后来也改成自动了 @Akkariiin
