### ISSUE TITLE
 Windows10的Defender把ShadowsocksR-dotnet2.0.exe当作木马删了，不知道啥情况来报告下。。。

### ISSUE THREAD

**Issue by harryzyj** [shadowsocksrr/shadowsocksr-csharp#217]
用的是前几天更新的最新版，这几天一直正常使用，今天在使用中突然就被删了，目前用着4.0没啥事。之前的版本没有过这种情况。
具体报毒是Trojan:Win32/Sonbokli.A!cl
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSonbokli.A!cl&threatid=2147728983
![Snipaste_2019-05-08_01-02-39](https://user-images.githubusercontent.com/33753242/57318632-5aa8f500-712d-11e9-8f57-800abb2b0f76.png)

**Comment by 417788939** [comment]
那是你自己的问题

**Comment by Akkariiin** [comment]
传到这里扫扫看？
https://www.virustotal.com/

**Comment by harryzyj** [comment]
> 传到这里扫扫看？
> https://www.virustotal.com/

https://www.virustotal.com/#/file/c38bf70c16f207f397c575733b23724dd6ca19c35f3383b8929cddd53adad917/detection
绝大部分都没啥问题，本来也没当回事，反馈看看其他人有没遇到，能解决误报最好，或者真的是我电脑本身有病毒感染的吧😄
