### ISSUE TITLE
是不是有后门！！！

### ISSUE THREAD

**Issue by leewi9** [shadowsocksrr/shadowsocksr-csharp#22]
启动后，连接了一个位于国外的ip地址（并不是我的VPS！）

请问，是什么情况？？！！

![image](https://user-images.githubusercontent.com/10832544/32432395-6cf0de00-c312-11e7-8df4-9934051f4afa.png)

**Comment by yfdyh000** [comment]
访问 https://23.57.115.5/ 可见，是微软的服务器。

**Comment by leewi9** [comment]
好笑，连微软的服务器干嘛，明显有鬼吧

**Comment by kkjb** [comment]
23.57.115.5 belongs to akamaitechnologies

**Comment by leewi9** [comment]
what the fuck??!

**Comment by kkjb** [comment]
GFWList Update Function uses the Github, Github uses the Akamai Tech as its CDN.
Please use your mind and you should not use the insulting words

**Comment by leewi9** [comment]
最好是这样

**Comment by dna1982** [comment]
Or what?

**Comment by Itzamana** [comment]
是的, 有后门的, 一旦成功连接到那个IP就会盗你的号, 格式化你的硬盘, 烧你的主板, 爆你的内存, 不光如此, 那个IP也是个肉鸡, 还会通过那个IP转到朝鲜, 直通金三胖的某个小按钮, 从而引发世界大战, 你怕了吗? ![image](https://user-images.githubusercontent.com/20204389/32721685-496b916a-c8a2-11e7-8e41-6f0fe1166399.png)![image](https://user-images.githubusercontent.com/20204389/32721685-496b916a-c8a2-11e7-8e41-6f0fe1166399.png)
