### ISSUE TITLE
大佬  问一下 如果选负载均衡的话 ip地址时不时会变

### ISSUE THREAD

**Issue by LoveFForever** [shadowsocksrr/shadowsocksr-csharp#221]
那么怎么可以固定一个ip地址 还是我设置错误造成ip变

**Comment by mxdh** [comment]
负载均衡本来就是不断切换服务器，ip地址改变是正常的
服务器->优先相同节点连接同一地址可以让一个网站用同一个ip，可以试试

**Comment by LoveFForever** [comment]
> 
> 
> 负载均衡本来就是不断切换服务器，ip地址改变是正常的
> 服务器->优先相同节点连接同一地址可以让一个网站用同一个ip，可以试试

感谢 我去试试看
