### ISSUE TITLE
访问FACEBOOK，只显示文字，不显示图片，里面的详情页打不开

### ISSUE THREAD

**Issue by Jothan01** [shadowsocksrr/shadowsocksr-csharp#222]
之所以写中文，本issue是写给打算写给乱发中文问题的人看的

1. 不欢迎小白，不回答诸如软件如何使用，如何搭建，如何配置，使用速度不快，如何提速等等和软件问题无关的问题，或把开发者当成客服的问题
2. 这里用于反馈软件可能的Bug，软件潜在的问题，和软件功能需求及讨论
3. 同一个issue不得在不同repo重复发，除非你发现发错地方（这种情况下你自行删除错误的issue），否则直接关闭且不回答问题，严重者拉黑名单
4. 建议你把问题事先在其它社区或和其它使用者讨论过，以确认不是密码错误，协议或插件错误，或服务器防火墙没关诸如此类本来应该自己解决的问题
5. 在你确认你需要发问题时，请尽可能提供详细的信息，包括服务端客户端具体版本，及相应log，及相应服务端客户端协议混淆等等的配置。如信息明显过少，则直接close不理踩

确认你读完以上内容后，请删除以上所有内容，然后写下你的问题

Please remove all above then write down your issue

**Comment by Jothan01** [comment]
有大佬能帮忙看看吗？重装系统都试过了，还是fb显示不了图片

**Comment by qw970601338** [comment]
大哥，你有网址吗，我以前购买时的网址进不去了

**Comment by wulinwulin** [comment]
https://www.kxcloud1.xyz/auth/register?code=e760vtK0NeJluBewHDa2tGLCCx8gh5hP
这个是我的梯子网站，注册登陆后记得加QQ群，因为如果官网被封的话群里会提供新的网址，我这个梯子很稳定，速度快，我已经用了挺长时间了

**Comment by qw970601338** [comment]
谢谢，谢谢，找了好久

**Comment by wulinwulin** [comment]
> 谢谢，谢谢，找了好久

没事的   不用谢，我也想赚点推广的钱，这样能降低自己的费用

**Comment by qw970601338** [comment]
你的邀请码多少，邀请码那里有堆乱七八糟的代码，不晓得是不是你的

**Comment by wulinwulin** [comment]
> 你的邀请码多少，邀请码那里有堆乱七八糟的代码，不晓得是不是你的

你打开我给你的网址，你注册就可以了，你仔细看我给你的网址，最后有code=e760vtK0NeJluBewHDa2tGLCCx8gh5hP
这个就是我的邀请码

**Comment by qw970601338** [comment]
已经注册好了，就等发工资购买，哎嘿嘿，谢谢

**Comment by qw970601338** [comment]
祝早日解决你 的问题
