### ISSUE TITLE
关于auth_akarin_spec_a以及auth_akarin_rand

### ISSUE THREAD

**Issue by zjl88858** [shadowsocksrr/shadowsocksr-csharp#224]
这两个协议在https://github.com/shadowsocksrr/shadowsocksr/tree/akkariiin/master
中无法找到，同时master分支上次的更新时间已经是2018年。
现在需要使用https://github.com/shadowsocksrr/shadowsocksr/tree/akkariiin/dev
这个分支进行clone？

**Comment by Akkariiin** [comment]
这两个协议还没有经过完整测试

想试用的话可以在dev上试试看
