### ISSUE TITLE
1080端口被占用

### ISSUE THREAD

**Issue by JonasGao** [shadowsocksrr/shadowsocksr-csharp#225]
这个问题是偶尔发生。另外，这个问题确实很幺蛾子。

首先是报错
![image](https://user-images.githubusercontent.com/4549584/57896306-be949180-7882-11e9-9474-8d75b6e5d7b0.png)

之后使用命令行查找，确实没发现 1080 端口进程
![image](https://user-images.githubusercontent.com/4549584/57896282-9dcc3c00-7882-11e9-8299-01cb43f38068.png)

之后看了另一个 issue 里说用工具。工具查了，也没有找到 1080 端口进程
![image](https://user-images.githubusercontent.com/4549584/57896294-aa509480-7882-11e9-9420-98539f815a2f.png)

每次这种端口占用的问题发生，注销用户重新登入，不能解决。
我这里是重启就可以了。

**Comment by JonasGao** [comment]
补充一下。我是自己 pull 源码（未修改任何代码）。自行编译的版本。所以报错堆栈里可以看到文件路径

**Comment by WildSaCk** [comment]
+1 很玄乎的问题

**Comment by Akkariiin** [comment]
那就别用1080口吧
这个端口经常有玄学问题，部分软件扫描proxy也只扫描这个口
