### ISSUE TITLE
4.9.2版本不支持360安全浏览器

### ISSUE THREAD

**Issue by Whalin-GitHub** [shadowsocksrr/shadowsocksr-csharp#226]
安装此版本后试水后发现IE浏览器可以正常访问Google，但是360安全浏览器却无法访问Google（事先确认360安全浏览器代理设置为IE浏览器设置），听闻此版本适合[360/2345/百度]全家桶用户，所以不清楚是设置问题，还是确实不支持360安全浏览器。希望大神们指点迷津，万分感谢！

**Comment by jasonliul** [comment]
http://forum.ru-board.com/topic.cgi?forum=5&topic=49673&start=180#12
把这些有毒ip段, 全部加入防火墙屏蔽, 再试~~

**Comment by sensune** [comment]
卸载国产浏览器, 安装chrome,firefox

**Comment by Akkariiin** [comment]
我也不知道
我不知道什么是360安全浏览器
