### ISSUE TITLE
【使用问题】请尽快解决

### ISSUE THREAD

**Issue by leeon0213** [shadowsocksrr/shadowsocksr-csharp#229]
你好，我是一个刚购买了半年的ssr使用者，使用的是SSTAP，这几天在使用上遇到了几个问题：
1.我之前正常使用SSTAP，现在代理无法显示了
2.进去之前购买的网站，已经无法获取新的订阅号了
3.若收到请及时联系我的邮箱495563892@qq.com或者联系我的电话13959562126

**Comment by Qixingchen** [comment]
此软件是非卖品 请自行联系购买的商家寻求售后
