### ISSUE TITLE
编译报错“意外的字符‘$’”

### ISSUE THREAD

**Issue by tianyuzhechina** [shadowsocksrr/shadowsocksr-csharp#23]
请问使用Visual Studio Express2012进行编译的时候报错“意外的字符‘$’”是C#6.0的原因么?

**Comment by tianyuzhechina** [comment]
解决了,更新到Update5之后指定安装Install-Package Microsoft.Net.Compilers -Version 1.0.0就可以了

**Comment by AspirinGeyer** [comment]
@Akkariiin @AkaneAkaza 有必要更新一下 README.md 里面的建议环境么？Visual Studio 2012 似乎有点过时了。
