### ISSUE TITLE
[feature request]希望负载均衡增加"按连接数"规则

### ISSUE THREAD

**Issue by xmt328** [shadowsocksrr/shadowsocksr-csharp#230]
之所以有这个需求是因为现在用的机场提供限速的无限流量服务
限速指的是单节点限速,因此负载均衡到每个节点上总体速度在看视频或者多文件下载的时候有所提升
但是现有的负载均衡规则很大概率会只用到其中一半的节点(目前自己用下来平衡比较好的是按次序)
希望作者考虑一下这个需求
thanks

**Comment by Akkariiin** [comment]
你可以试试随机

按连接数不会达到你想要得效果，按次序或者随机更加符合你的需求
