### ISSUE TITLE
不打开本软件，无法正常浏览网页

### ISSUE THREAD

**Issue by girlfriendjin** [shadowsocksrr/shadowsocksr-csharp#236]
在正常网络连接状态下，电脑不打开本软件，正常网络情况下打不开网页（类似360浏览器，显示没有网络），必须打开本软件后才能浏览网页，这个问题怎么解决

**Comment by xiaocao008** [comment]
Internet选项--连接--局域网设置，手动关掉里面的选项就行了

**Comment by girlfriendjin** [comment]
局域网设置关不掉怎么办，取消确定后再打开它还是勾选------------------ 原始邮件 ------------------
发件人: "xiaocao008"<notifications@github.com>
发送时间: 2019年5月27日(星期一) 上午10:20
收件人: "shadowsocksrr/shadowsocksr-csharp"<shadowsocksr-csharp@noreply.github.com>;
抄送: "girlfriendjin"<972477352@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [shadowsocksrr/shadowsocksr-csharp] 不打开本软件，无法正常浏览网页 (#236)



Internet选项--连接--局域网设置，手动关掉里面的选项就行了
 
&mdash;
