### ISSUE TITLE
v4.9.2无法解压

### ISSUE THREAD

**Issue by ruohone** [shadowsocksrr/shadowsocksr-csharp#237]
v4.9.2 win10下载后无法解压

**Comment by Conquerski** [comment]
建议重新下载压缩包，并使用7-zip进行解压

**Comment by sbyg** [comment]
我win7也是，老版本怎么直接升级呢？

**Comment by Conquerski** [comment]
> 我win7也是，老版本怎么直接升级呢？

解压缩替换文件即可，配置文件在gui-config.json。
