### ISSUE TITLE
v4.9.2 疯狂报错 需要代理的页面打不开

### ISSUE THREAD

**Issue by zhangchenkai** [shadowsocksrr/shadowsocksr-csharp#238]
v4.9.2 疯狂报错，不用代理的页面可以正常打开，需要代理的页面打不开chrome显示`ERR_EMPTY_RESPONSE`错误

本来是dns有问题，手动填了一下接口的dns后正常了。
但是重启之后又出现了这种问题。

```
[Info] Connect mail.google.com:443 via xxx.xxx.com:1111
[Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive()
```

**Comment by zhangchenkai** [comment]
所有配置未改动，在换回 https://github.com/shadowsocksr-rm/shadowsocksr-csharp 的v4.7.0.1后，一切正常。

**Comment by jzmswe** [comment]
我是用回4.8.0后，一切正常了。

**Comment by Leegei** [comment]
请问这个客户端没有exe文件吗？

**Comment by zhangchenkai** [comment]
> 请问这个客户端没有exe文件吗？
发布的程序才有exe文件
主分支的：https://github.com/shadowsocksr-rm/shadowsocksr-csharp/releases/tag/4.7.0.1
@jzmswe 提到的：https://github.com/shadowsocksrr/shadowsocksr-csharp/releases/tag/4.8.0

**Comment by jzmswe** [comment]
> > 请问这个客户端没有exe文件吗？
> 
> 发布的程序才有exe文件
> 主分支的：https://github.com/shadowsocksr-rm/shadowsocksr-csharp/releases/tag/4.7.0.1
> @jzmswe 提到的：https://github.com/shadowsocksrr/shadowsocksr-csharp/releases/tag/4.8.0

试了，还是4.7.0.1好用，多谢楼主。

**Comment by JaviYoung** [comment]
同样的问题，可是前两天还都正常使用，今天突然间就不行了，切换多条线路都不行。

**Comment by JaviYoung** [comment]
> 同样的问题，可是前两天还都正常使用，今天突然间就不行了，切换多条线路都不行。

刚刚在其他issue里发现了一个方法，自己试过之后是好用了。
看描述貌似是dns解析的问题
先在命令行中输入ipconfig /flushdns，然后在客户端设置中修改dns 8.8.8.8。

**Comment by zhangchenkai** [comment]
根据ss已有的issue https://github.com/shadowsocks/shadowsocks-windows/issues/1791 
我发现问题跟网络连接的接口有关，跟ssr版本无关：
1. 接口不要使用中文名；
2. 使用校园网拨号的盆友，注意更改连接名字为英文；或者使用系统自带vpn拨号（注意名称使用英文）来代替；

另外，不排除相关issue是由于dns配置问题引起的，请自行参考其他相关issue解决办法。
