### ISSUE TITLE
4.9.2，不少网站翻不了

### ISSUE THREAD

**Issue by chiau9** [shadowsocksrr/shadowsocksr-csharp#246]
BBC是确定翻不了。4.9.0就可以的。

**Comment by Lunaeth** [comment]
[https://s2.ax1x.com/2019/06/16/V70rgU.png](url)自己检查自己的网络环境 开发者不是客服

**Comment by chiau9** [comment]
> [https://s2.ax1x.com/2019/06/16/V70rgU.png](url)自己检查自己的网络环境 开发者不是客服

不用检查了，已退回4.9.0老版，再也没这些烦恼。

**Comment by SHIELD-SKY** [comment]
确实，4.9.2 访问Google学术没有反应，ERR_EMPTY_RESPONSE，  换回4.9.0后就可以了

**Comment by SatsukiUMI** [comment]
同，今天无法访问Facebook。也是报ERR_EMPTY_RESPONSE
