### ISSUE TITLE
4.9.2逻辑问题

### ISSUE THREAD

**Issue by badboy0** [shadowsocksrr/shadowsocksr-csharp#250]
1、当代理规则为绕过局域网和大陆时，右键托盘选择切换全局模式后，全局无效。
2、将代理规则改为全局后，无效，需要重启后，全局模式生效。
3、程序请求访问网站手动设置本地代理1080时，pac规则与选择的代理规则不符。

**Comment by Qixingchen** [comment]
没有明白全局模式指的是什么  
不过值得注意的是 系统代理模式 和 代理规则 是互相独立的

**Comment by SciUnivMoring** [comment]
同意楼上, 不是软件的问题, 而是你没理解

**Comment by jzmswe** [comment]
美国之音无论全局还是智能代理，都上不去，换别的工具OK。

**Comment by SciUnivMoring** [comment]
> 用事实说话，美国之音无论全局还是智能代理，都上不去，换别的工具OK。

这种情况确定不是节点的问题吗

**Comment by SciUnivMoring** [comment]
> 当代理规则为绕过局域网和大陆时，右键托盘选择切换全局模式后，全局无效。

如果你的代理规则设为了全局, 并不是意味着所有的网络流量都会通过代理. 

请看图理解

![判断流程](https://user-images.githubusercontent.com/31263957/59566112-024f0680-908e-11e9-91c0-19b02f03cbf5.png)


> 程序请求访问网站手动设置本地代理1080时，pac规则与选择的代理规则不符

如果一个程序进行了这样的设置, 那么该程序所有流量都会直接走代理, 而不会经过上图的判断过程

**Comment by jzmswe** [comment]
> > 用事实说话，美国之音无论全局还是智能代理，都上不去，换别的工具OK。
> 
> 这种情况确定不是节点的问题吗

同一节点，上别的网站没问题，不能上美国之音。

**Comment by reki-cool** [comment]
这个版本确实有问题，不过它对于订阅链接的格式，进行了优化，现在的情况是，能识别更多的订阅链接，但是上网反而有问题了，应该是某处逻辑问题吧

**Comment by badboy0** [comment]
> > 当代理规则为绕过局域网和大陆时，右键托盘选择切换全局模式后，全局无效。
> 
> 如果你的代理规则设为了全局, 并不是意味着所有的网络流量都会通过代理.
> 
> 请看图理解
> 
> ![判断流程](https://user-images.githubusercontent.com/31263957/59566112-024f0680-908e-11e9-91c0-19b02f03cbf5.png)
> 
> > 程序请求访问网站手动设置本地代理1080时，pac规则与选择的代理规则不符
> 
> 如果一个程序进行了这样的设置, 那么该程序所有流量都会直接走代理, 而不会经过上图的判断过程

感谢大佬无私分享！

**Comment by Qixingchen** [comment]
程序设定了代理,将流量重定向至代理端口后,还将进行代理规则判断  
相关解释:  
代理规则是在代理端口后进行判断的  
系统代理模式判断为代理后会将流量重定向至代理端口.
