### ISSUE TITLE
Releases page 404

### ISSUE THREAD

**Issue by hqzxzwb** [shadowsocksrr/shadowsocksr-csharp#26]
The `releases` reference in Readme.md seems to be out of date.

**Comment by AspirinGeyer** [comment]
Here is the right link: [https://github.com/shadowsocksrr/shadowsocksr-csharp/releases](https://github.com/shadowsocksrr/shadowsocksr-csharp/releases)

**Comment by Akkariiin** [comment]
Use the project release page instead.
