### ISSUE TITLE
我现在是无法访问Google

### ISSUE THREAD

**Issue by flous-firm** [shadowsocksrr/shadowsocksr-csharp#260]
只有谷歌的搜索和facebook不能访问，其他包括谷歌的账号都是访问正常的

**Comment by pseudobeing** [comment]
我也遇到的相同的问题

**Comment by shenthought** [comment]
我也是，Google和Facebook无法访问，一直在找原因

**Comment by SSdeng** [comment]
我把代理规则改为全局就可以正常访问google了，你们试试

**Comment by wangrush** [comment]
不能访问google是运营商的问题，UDP上对DNS的污染。我这边移动的网，不管用什么DNS，都会强制解析到国内的一个IP，所以按照绕过大陆的规则永远都不会走ssr。

**Comment by pseudobeing** [comment]
然而我就旧的版本就没有这个问题

**Comment by enximi** [comment]
4.9.2谷歌不能访问，4.9.0没有问题

**Comment by yangxu770409504** [comment]
我是无法访问GoogleVideo.com这个域名，看起来可能是DNS污染导致的。在chrome浏览器用omega proxy，SSRR切换到全局也没有用/

**Comment by SakuraSauce** [comment]
> 我把代理规则重新排列就可以可以正常访问google了，你们试试

我的4.9.2全部改成全局也没用

**Comment by flous-firms** [comment]
> 只有谷歌的搜索和facebook不能访问，其他包括谷歌的账号都是访问正常的

**Comment by flous-firms** [comment]
> 我也是，Google和Facebook无法访问，一直在找原因

**Comment by flous-firms** [comment]
好吧自己地址的问题，和软件还是没太大关系~
