### ISSUE TITLE
facebook page loaded with only text

### ISSUE THREAD

**Issue by FangRay** [shadowsocksrr/shadowsocksr-csharp#263]
facebook  只能显示 文字，没有图片和排版； facebook loaded with only text, no pics and rich formats, should i add some new rules in the PC app setting? Thanks.

**Comment by FangRay** [comment]
sorry for the issue, i just take a research at the issues before, then downgrade to 4.0, all the problems gone.  
anticipate for the 4.3 :) Thank you

**Comment by Akkariiin** [comment]
press F5 , you will get the full color facebook

if you dont want press F5, you need change a more expensive server
