### ISSUE TITLE
please give me you QQ

### ISSUE THREAD

**Issue by zhangMaZhi** [shadowsocksrr/shadowsocksr-csharp#264]
请私信我 客服联系方式 微信 或者QQ  网站经常挂掉 我需要最近能用的网站

Please remove all above then write down your issue

**Comment by Akkariiin** [comment]
my qq is 123456

**Comment by zhangMaZhi** [comment]
QQ：764877628




------------------ 原始邮件 ------------------
发件人: "Akkariiin"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 晚上7:26
收件人: "shadowsocksrr/shadowsocksr-csharp"<shadowsocksr-csharp@noreply.github.com>;
抄送: "我爱笑"<764877628@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [shadowsocksrr/shadowsocksr-csharp] please give me you QQ (#264)




Closed #264.
