### ISSUE TITLE
V4.9.2 没有打包EXE文件

### ISSUE THREAD

**Issue by YouZhengChuan** [shadowsocksrr/shadowsocksr-csharp#267]
![image](https://user-images.githubusercontent.com/3882312/61168555-94a9d380-a582-11e9-961c-d949b2d14fb7.png)

**Comment by Akkariiin** [comment]
![2019-07-27 19_41_24-Window](https://user-images.githubusercontent.com/30503034/61993969-db311f00-b0a6-11e9-86a2-68d95ed7bf29.png)
