### ISSUE TITLE
v4.9.2 对 ipv6 网站无法代理

### ISSUE THREAD

**Issue by gwy15** [shadowsocksrr/shadowsocksr-csharp#268]
# 问题描述
v4.9.2 无法访问 ipv6 only 的网站，如 [北邮人](https://bt.byr.cn)，[ipv6地址查看](https://ipv6.whatismyip.com/) 等。

用 python 提示是 Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))，chrome 提示是 ERR_EMPTY_RESPONSE

使用 v4.9.0 时，可以正常访问。

# 使用环境
客户端系统windows 10 1903，客户端只有ipv4环境，ssr服务器有 ipv6 环境。

**Comment by Akkariiin** [comment]
服务器配置中的dns_ipv6是true吗？

**Comment by gwy15** [comment]
> 服务器配置中的dns_ipv6是true吗？

不是我的服务器，不清楚服务器配置

**Comment by xuezhichao19970719** [comment]
> 服务器配置中的dns_ipv6是真的吗？

访问ins无法加载图片  报错：
[2019-07-28 00:21:31] [Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.Connect()
   在 Shadowsocks.Controller.ProxyAuthHandler.RspHttpHandshakeReceive()
   在 Shadowsocks.Controller.ProxyAuthHandler.HandshakeReceive()

似乎也是ipv6的问题？  win10 1903 客户端4.9.2  本地网络环境只有ipv4

**Comment by burningalive** [comment]
同遇到了楼主的问题

**Comment by merry200603** [comment]
一直都是正常的，可能是你本地ipv6不通吧，可以检查下

**Comment by merry200603** [comment]
一直都是正常的，可能是你本地ipv6不通吧，可以检查下；本地可以考虑使用6to4，或者隧道，另外北邮人是封禁了不少ip的访问权限的

还有，国内多数运营商已经大范围普及ipv6了，可以考虑更换支持ipv6的路由

**Comment by gwy15** [comment]
> 一直都是正常的，可能是你本地ipv6不通吧，可以检查下；本地可以考虑使用6to4，或者隧道，另外北邮人是封禁了不少ip的访问权限的
> 
> 还有，国内多数运营商已经大范围普及ipv6了，可以考虑更换支持ipv6的路由

我想你没看懂我在说什么……这不是我本地有没有原生ipv6的问题，是
+ 同样的浏览器、目标网站、代理设置、服务器的情况下
+ v4.9.2 无法代理，v4.9.0 可以代理

这并不是我有没有原生ipv6的问题。

**Comment by jlfsdtc** [comment]
+1 version 4.9.0 正常运行,4.9.2 IP6都会失败

**Comment by Akkariiin** [comment]
如果你在ipv6.test-ipv6.com中没有获得10分，请检查相应问题
在配置正常的情况下，ipv6.test-ipv6.com是可以获得满分的

**Comment by Akkariiin** [comment]
如果涉及到DNS相关问题，请检查如下位置：

* 服务器是否可以使用IPv6，在服务器上解析DNS时返回内容是否包含IPv6地址
* 服务器上是否可以访问IPv6 only 网站，是否可以直接连接IPv6地址，是否可以ping通IPv6地址
* 客户端 选项设置->DNS ，这里是否填写了正确且可靠的DNS服务器地址，如不确定请填入 ```1.0.0.1```
* 浏览器代理设置上是否已经启用了 ```Send DNS through SOCKS5 proxy``` 、```启用socks5时代理DNS查询``` 诸如此类的设置
