### ISSUE TITLE
Add information

### ISSUE THREAD

**Issue by baimafeima** [shadowsocksrr/shadowsocksr-csharp#27]
Could you add the following information:
1. Provide a description in the GitHub title. When pinning your repository, no information is shown. 
2. Provide information regarding the differences between shadowsocks and shadowsocksrr. 
3. Do your tarball releases work with Linux-based operating systems?

**Comment by Akkariiin** [comment]
1 May do these things in the future
2 In some view, ss and ssr(r) are different . Like the c and c++ language. Only listen similar.
3 maybe no. I don't test it.
