### ISSUE TITLE
过期续费问题

### ISSUE THREAD

**Issue by zzhn6** [shadowsocksrr/shadowsocksr-csharp#271]
因为过期导致无法打开https://my.imssx.org/index.php地址进行续费，一直提示访问的网站不安全，希望能够帮我续费下，我这边可以提供账号和密码，续费后我可以转账给你。谢谢！！！
![image](https://user-images.githubusercontent.com/29200763/61678691-27423380-ad36-11e9-9dd6-8f0d847855c9.png)

**Comment by Qixingchen** [comment]
请仔细阅读 issue 模板 不要发布无关信息
