### ISSUE TITLE
4.9.0以上版本无法访问google.com

### ISSUE THREAD

**Issue by challyee** [shadowsocksrr/shadowsocksr-csharp#296]
一样的节点，在4.9.0里面可以访问goole.com，在9.1及9.2版本中无法访问google.com，但是可以访问google.com.hk，以及其他一些谷歌相关网站

**Comment by nowind** [comment]
同出现问题,   在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first) ,目测部分网络环境dns污染返回null的ipaddress

**Comment by jeromeli002** [comment]
c我也这样地 还是用回4.9.0了

**Comment by Akkariiin** [comment]
请确定一下DNS相关设置是否正确
