### ISSUE TITLE
密码不能留空

### ISSUE THREAD

**Issue by Josie915** [shadowsocksrr/shadowsocksr-csharp#3]
SS密码不能留空，留空就不能保存，有些SS就是共享的，没有密码空白的，可是它提示不能确定保存

**Comment by Josie915** [comment]
SSRRv4.8.0，
系统WIN10.64位

**Comment by Josie915** [comment]
SSRRv4.8.0，
系统WIN10.64位

**Comment by Akkariiin** [comment]
改好了，你可以试试

**Comment by Josie915** [comment]
不对呀，没变呀。是不是一定要打个空格键才行啊

**Comment by Josie915** [comment]
ShadowsocksR-win-4.8.0.rar

released this Aug 8, 2017 · 2 commits to master since this release

**Comment by Akkariiin** [comment]
你有编译嘛？

**Comment by Akkariiin** [comment]
要不你等下一个版本发布？或者自己开VS2017编译一个？

**Comment by Josie915** [comment]
好，那我等下一个版本吧

**Comment by AspirinGeyer** [comment]
SS 密码留空那不就是裸跑了么 0.0

**Comment by Josie915** [comment]
因为我用的是共享的SS，它是没密码的，我也不清楚

**Comment by Josie915** [comment]
因为我用的是共享的SS，它是没密码的，我也不清楚

**Comment by Akkariiin** [comment]
@AspirinGeyer 密码过短的话会使用由generator从输入的密码生成新的key作为密码。长度不够的问题不用考虑，但是安全性就保证不了了。
