### ISSUE TITLE
4.9.2，4.9.3版本無法訪問台灣政府相關網站

### ISSUE THREAD

**Issue by hsly109** [shadowsocksrr/shadowsocksr-csharp#301]
[Error] System.NullReferenceException: 未将对象引用设置到对象的实例。
在 Shadowsocks.Util.Utils.QueryDns(String host, String dns_servers, Boolean IPv6_first)
在 Shadowsocks.Controller.Socks5Forwarder.IsHandle(Byte[] firstPacket, Int32 length, Socket socket)
在 Shadowsocks.Controller.Socks5Forwarder.Handle(Byte[] firstPacket, Int32 length, Socket socket, String local_sendback_protocol)
全部都是此類錯誤，log顯示遠端伺服器查詢比如www.mofa.gov.tw沒有回應
本地網路介面卡更改為非中國的dns server就可以正常，比如1111或者8888
退回到4.9.0版本解析也正常

**Comment by hsly109** [comment]
也檢視過 nightly version版本的4.9.3，問題依舊，暫時先rollback到4.9.0版本了

**Comment by bajisama** [comment]
@hsly109  哪有4.9.3 最新的不是4.9.2么

**Comment by nssrgsa** [comment]
民国朋友也用SSR吗
