### ISSUE TITLE
windows client error: clientPostDecrypt data error. 

### ISSUE THREAD

**Issue by pytimer** [shadowsocksrr/shadowsocksr-csharp#303]
在用shadowsocksR的windows客户端的时候，遇到一个问题，导致无法访问服务端。在之前是可以的，最近两天无法访问，但是mac和android的客户端没有问题，说明服务端应该是好的，只是windows的客户端问题。

## version
4.8.0 、4.8.1 和4.9.2都尝试过

method是chacha20

## log

查看客户端日志，有一条错误日志: Error proxy server xxxx clientPostDecrypt data error. 

想知道是什么问题，看网上说是libsodium的问题，不知道是不是这个原因，如果是有没有怎么在windows上安装这个的步骤，不太懂。谢谢

**Comment by Akkariiin** [comment]
之前可以现在不行，先检查网络环境

**Comment by pytimer** [comment]
我在家里的windows10上试了下，是可以的。但是公司的windows7不可以，是因为网络的问题吗？

**Comment by newpost** [comment]
@pytimer  问题解决了吗

**Comment by pytimer** [comment]
应该是公司的windows电脑问题，目前是正常了
