### ISSUE TITLE
SSR电脑版问题，请帮忙看看是什么问题吧。

### ISSUE THREAD

**Issue by kimanlo** [shadowsocksrr/shadowsocksr-csharp#31]
电脑环境：WIN10 64位
SSR版本：4.8/4.8.1
描述：
在4.8的时候，我更新了最新版本的QQ输入法（5.7版）后，SSR自动关闭，查看电脑系统日志发现以下描述。在QQ输入法 4.6版本的时候并没有出现，只在4.7的版本出现这个问题。

![捕获.PNG](https://ooo.0o0.ooo/2017/11/19/5a113ce644b70.png)
![捕获2.PNG](https://i.loli.net/2017/11/19/5a113ce644b76.png)
![捕获3.PNG](https://i.loli.net/2017/11/19/5a113ce6993b3.png)

**Comment by Akkariiin** [comment]
这个问题理论上是QQ输入法的ime设计问题导致的。
紫光拼音和微软拼音以前好像也出现过类似的问题导致Firefox崩溃。

<hr/>

建议更换输入法，或者给QQ输入法提issue。
国产软件导致SSR无法使用的问题恕这里不会给予处理。
