### ISSUE TITLE
官网登陆访问不了了

### ISSUE THREAD

**Issue by gfandyr** [shadowsocksrr/shadowsocksr-csharp#315]
vpn不可用，同时https://ssrcloud.net/user/shop无法访问了

**Comment by SaylorTl** [comment]
同样的问题，https://ssrcloud.net与https://ssrcloud.org都访问不了

**Comment by Burningtissue** [comment]
> 同样的问题，[https://ssrcloud.net与https://ssrcloud.org都访问不了](https://ssrcloud.net%E4%B8%8Ehttps://ssrcloud.org%E9%83%BD%E8%AE%BF%E9%97%AE%E4%B8%8D%E4%BA%86)



> vpn不可用，同时[https://ssrcloud.net/user/shop无法访问了](https://ssrcloud.net/user/shop%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E4%BA%86)

这里发的SSR软件的问题，和机场有什么关系？我寻思一个机场的网站咋个就成了SSR软件的官网了？

**Comment by Burningtissue** [comment]
> vpn不可用，同时[https://ssrcloud.net/user/shop无法访问了](https://ssrcloud.net/user/shop%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E4%BA%86)



> 同样的问题，[https://ssrcloud.net与https://ssrcloud.org都访问不了](https://ssrcloud.net%E4%B8%8Ehttps://ssrcloud.org%E9%83%BD%E8%AE%BF%E9%97%AE%E4%B8%8D%E4%BA%86)

是我没搞懂吗？这里应该发的都是SSR软件的问题。SSR是一个软件，你们发的是个机场，怎么一个机场官网就成了SSR软件的官网了？

**Comment by Akkariiin** [comment]
这里就是软件的官网，你能发issue就说明你能上官网，至于其他的网站是怎么回事那不关我事
