### ISSUE TITLE
release 解压失败

### ISSUE THREAD

**Issue by dexterque** [shadowsocksrr/shadowsocksr-csharp#316]
![image](https://user-images.githubusercontent.com/10069761/66746098-7b7f2e80-eeb3-11e9-827f-9d76c2af020b.png)

**Comment by yfdyh000** [comment]
文件大小是多少？你的网络不行，下载失败了，下载提供是亚马逊aws服务器，国内大多要翻。

**Comment by dexterque** [comment]
> 文件大小是多少？你的网络不行，下载失败了，下载提供是亚马逊aws服务器，国内大多要翻。

谢谢啦 用外网下 还是不行 最近小飞机一直好好的 突然电脑版本不能用 手机上还可以 很奇怪 换了几个客户端都不行

**Comment by justjump** [comment]
用7zip
