### ISSUE TITLE
Please add shasum in release page

### ISSUE THREAD

**Issue by snowman** [shadowsocksrr/shadowsocksr-csharp#334]

**Comment by sigvids** [comment]
**ShadowsocksR-win-4.9.2.zip**

- SHA1: 8837754BF28657F3D9CB65F6158D6E1C7D5512F2
- SHA256: E3F6860AEFF0F45DB52F74C0060A657D59C2436CCFCBA3ED534E1E01AD5212D3

**ShadowsocksR-win-4.9.0.zip**

- SHA1: C4DAE562BE431D80CFF3266AF6F6FA95B3C4304E
- SHA256: 6F3A6CFD099D37492B1AC6EA3D504ACC6D4C2948C9CC99DE59D7488EF18BF6B1
