### ISSUE TITLE
Lack of documentation on how to set up client for SSR server

### ISSUE THREAD

**Issue by jfthuong** [shadowsocksrr/shadowsocksr-csharp#335]
Hi,

I have a server and a SSR uri  (*ssr://MTcyLjI0.....*).

I have not found how to do the set up of the client to connect to my server.

Looking forward any hint. I am currently using version 4.9.0.

Thanks

**Comment by sigvids** [comment]
https://signaturevideos.blogspot.com/2019/11/windows-shadowsocksr-client.html
