### ISSUE TITLE
可以加入 aes-256-gcm 協議嗎？

### ISSUE THREAD

**Issue by delphinuz** [shadowsocksrr/shadowsocksr-csharp#34]
server版有這協議，但需要client也支援。

android已詢問過了，不知csharp版是否比較有機會先加入？

謝謝。

**Comment by AkaneAkaza** [comment]
server没有这个协议

**Comment by delphinuz** [comment]
我自己重新編譯新版libsodium，就有支援。

**Comment by AkaneAkaza** [comment]
并不支援，只是写在那里，根本不能使用

**Comment by Akkariiin** [comment]
SSRR不会添加SS的新版协议ADAE的支持。
SSRR推荐使用ChaCha20和XChaCha20这两种加密。

**Comment by Just2co** [comment]
@Akkariiin 请给我安利下xchacha20 xsalsa20是什么鬼？跟chacha20有什么区别？IV校验位数不一样还是？

**Comment by Akkariiin** [comment]
@Just2co 

<hr/>
XChaCha20 it self:
https://jedisct1.gitbooks.io/libsodium/content/advanced/xchacha20.html

 

> XChaCha20 is a variant of ChaCha20 with an extended nonce, allowing random nonces to be safe.
>
> XChaCha20 doesn't require any lookup tables and avoids the possibility of timing attacks.
>
>Internally, XChaCha20 works like a block cipher used in counter mode. It uses the HChaCha20 hash function to derive a subkey and a subnonce from the original key and extended nonce, and a dedicated 64-bit block counter to avoid incrementing the nonce after each block.
>
>XChaCha20 is generally recommended over plain ChaCha20 due to its extended nonce size, and its comparable performance. However, XChaCha20 is currently not widely implemented outside the libsodium library, due to the absence of formal specification.

<hr/>
When use XChaCha20 on ADAE mode, And compared with other function:
https://jedisct1.gitbooks.io/libsodium/content/secret-key_cryptography/aead.html  

 

>**Limitations**
>
Construction | Max bytes for a single (key,nonce) | Max bytes for a single key
-- | -- | --
AES256-GCM | ~ 64 GB | ~ 350 GB (for ~16 KB long messages)
ChaCha20-Poly1305 | No practical limits (~ 2^64 bytes) | Up to 2^64* messages, no practical total size limits
ChaCha20-Poly1305-IETF | 256 GB | Up to 2^64* messages, no practical total size limits
XChaCha20-Poly1305-IETF | No practical limits (~ 2^64 bytes) | Up to 2^64* messages, no practical total size limits

>**Nonces**
>
Construction | Safe options to choose a nonce
-- | --
AES256-GCM | Counter, permutation
ChaCha20-Poly1305 | Counter, permutation
ChaCha20-Poly1305-IETF | Counter, permutation
XChaCha20-Poly1305-IETF | Counter, permutation, **random, Hk(random ‖ m)**

>**TL;DR: which one should I use?**
>XChaCha20-Poly1305-IETF is the safest choice.

>**XChaCha20-Poly1305**
>
>XChaCha20-Poly1305 applies the construction described in Daniel Bernstein's Extending the Salsa20 nonce paper to the ChaCha20 cipher in order to extend the nonce size to 192-bit.
>
>This extended nonce size **allows random nonces to be safely used**, and also facilitates the construction of misuse-resistant schemes.

<hr/>
https://jedisct1.gitbooks.io/libsodium/content/secret-key_cryptography/chacha20-poly1305.html

>**Variants**

>libsodium implements three versions of the ChaCha20-Poly1305 construction:
>
>*    The original construction can safely encrypt up to 2^64 messages with the same key (even more with most protocols), without any practical limit to the size of a message (up to 2^64 bytes for a 128-bit tag).
>*    The IETF variant. It can safely encrypt a pratically unlimited number of messages, but individual messages cannot exceed 64*(2^32)-64 bytes (approximatively 256 GB).
>*    The XChaCha20 variant, introduced in libsodium 1.0.12. It can safely encrypt a practically unlimited number of messages of any sizes, and random nonces are safe to use.
>
>The first two variants are fully interoperable with other crypto libaries. The XChaCha20 variant is currently only implemented in libsodium, but is the recommended option if interoperability is not a concern.


<hr/>

简单来说，使用XChaCha20的时候，你不需要担心同一个加密密钥使用时间过长而导致的问题，也不需要担心随机数发生器不够随机带来的问题。XChaCha20理论上可以加密无限多的数据，而不管是ChaCha20还是ChaCha20-IETF都限制了理论上安全的数据加密数量(256 GB)。
XChaCha20对使用环境的要求比其他算法更低一些，变相的说，即使使用者太久没有更换密钥导致使用同一个密钥加密了太多数据，或随机数发生器出现问题或计数器循环了一圈带来的nonce重复发生，都不会像其他算法那样导致加密被破解。并且这也是libsodium库的推荐算法。唯一的缺陷应该就是现在暂时只有libsodium实现了XChaCha20吧？

**Comment by Just2co** [comment]
@Akkariiin 感谢答复，看懂了，也就是说更安全了。对CPU的资源消耗呢？另外，很多SS的加密算法，SSRR并不支持，可否考虑也加入进来，做到兼容？

**Comment by Akkariiin** [comment]
**SSRR不会支持SS的ADAE系列加密算法**

因为SS在使用ADAE加密算法时，实际上是改用了新版本的SS协议，使用新的包格式，而不仅仅是如从前那样简单地替换了包内部地数据加密算法

SS使用基于ADAE加密算法的新的SS协议带来的好处是彻底解决中间人/重放攻击，附带的效果是新SS协议的包特性与以前的SS协议不同，从而导致现有的能够精确识别非基于ADAE的旧的SS协议的各种方法失效
从这一点上来说推荐使用SS的用户尽可能不再使用非ADAE加密，不管是CPU计算力消耗提高还是延迟增加都不是不更换到ADAE的理由，毕竟网速慢一点不会死人的，但用户被封IP和被喝茶才是致命的【笑
同样的不在使用了SS/R的机器上使用国产软件也是基于同样的道理
这么简单的道理为什么就有这么多想不明白的人呢？

而相对而言，SSR从破娃folk出来的时候就专注一个创建更多的协议和混淆插件以便降低协议特征被针对的可能。并且SSR的现代协议/混淆都自带防重放攻击的特性，也不需要SS的新的基于ADAE的协议提供这些特性

故SSR的用户在选择时只要选择最新的协议簇和推荐的加密算法再加上适当的混淆即可

<hr/>

@Just2co  以上

**Comment by Just2co** [comment]
@Akkariiin 懂你说的意思，SS现在进步很大。我的意思是，很多热心网友分享的新版SS连接，SSR甚至SSRR都无法兼容连接，因为加密方式的原因。在AEAD加密协议没加入SS之前，SSR是可以用SS的连接的，现在反而不行了。所以手机上就要安装两个客户端，感觉不是很有必要。如果SSRR加入SS新的加密协议，就会好一些，这里并没有说哪个软件好，哪个软件不好的意思，哪怕是无界，自由门，都有它们存在的伟大价值。

**Comment by Akkariiin** [comment]
给SSRR加入SS的新协议需要不少改动，而SSR本身就非常复杂，所以为了实现这个需求的所需的工作量会很大
而现在SSRR没有足够的人手，甚至安卓端的F协议的支持现在一直拖延着，更不可能为了一个可有可无的兼容性问题来消耗宝贵的人力
综上所述，给SSRR添加ADAE支持是不必要且暂时不可能的
倒是我记得glzjin大佬之前有做一个魔改版PY端可以同时支持SSR和SS新协议，但是那个版本有严重的内存泄漏问题，不知道现在修好没有
好像glzjin大佬最近也比较忙，很少见他出现

另外，我一直在呼吁更多人来给SSRR贡献代码，可是为什么只见提issue的人而不见提PR的人呢？

<hr/>

@Just2co

**Comment by Akkariiin** [comment]
另外，从某种意义上来说，SS和SSR的关系就像是C和C++的关系一样
虽然在名字上看起来相似，在某些情况下也可以互相兼容，但是实际上两者已经发展成了完全不同的两个东西，所以请各位不要发PR来问为什么SSR不支持SS的某个特性了

为什么大家不反过来给SS提issue要求SS支持SSR的特性呢？如果SS拥有SSR的全部特性还做得比SSR更加好，那岂不是大家都去用SS就好了吗？

<hr/>

我觉得相对SS而言，SSR开发者，不管是我还是破娃，都算是比较好说话的那种吧？难道就因为好说话所以才由这么多麻烦么？果然鲁迅说得好，人善被人欺马善被人骑么？古人诚不欺我。

![“我没说过”——鲁迅](http://img.mp.itc.cn/upload/20170310/2f3f3c124a314170a3a98967379b2415_th.jpg)

【笑

**Comment by Prisma-illya** [comment]
SSR完全没有必要去支持SS的一些特性了，完全可以开始发展自己的特性
至于楼上那几位，如果你们有能力的话 —— Fork过去，然后开始你的表演

<hr>
Akkariiin是我见过最活跃的SSR开发者了
<br>
有Issues必回
<br>
<br>
<img src="http://ww3.sinaimg.cn/large/0060lm7Tly1fmhdo28wmoj30hs0hs74r.jpg" width="128"></img>

**Comment by Rictusempra** [comment]
@Prisma-illya 在公共场合能不能留点节操。。。

**Comment by Just2co** [comment]
@Akkariiin 大佬，你问了个问题，为何大把提issue的，不见提PR的，就我个人来讲，目前正在疯狂自学编程中，我也想编，可惜不会编啊，像以前，连在这里提问都不会操作的。PS：软件工程师这几年的工资真是高，好羡慕啊！

**Comment by Akkariiin** [comment]
@yuexiafeic Android客户端所使用的libev客户端所内嵌的libsodium密码学库过旧，但开发者这边暂时没有足够的精力来升级，间接导致Android客户端短时间内无法支持Xchacha20
很抱歉~

**Comment by ntgeralt** [comment]
我想说，ios的小火箭只有xchacha20-ietf-poly1305, 没xchacha20。另外ssr的tls几乎会被精确识别，GCP只要开TLS  ip活不过一星期。所以真的不知道哪些是过时了

**Comment by redapple0204** [comment]
> 我想说，ios的小火箭只有xchacha20-ietf-poly1305，另外ssr的tls几乎会被精确识别，GCP只要开ssr 443 TLS ip活不过一星期。所以真的不知道哪些是过时了

@ntgeralt 你该不会是混淆和加密没选好吧

**Comment by Akkariiin** [comment]
@ntgeralt GCP跑了4个机器，全都是80-httpsimple 443-tls 8080-httppost ， 2018全年都没有出现ban IP，只是偶尔会网络质量变差
所以不存在这个问题

**Comment by ntgeralt** [comment]
@Akkariiin i mean obfs tls1.2.

**Comment by ocswor** [comment]
> @yuexiafeic Android客户端所使用的libev客户端所内嵌的libsodium密码学库过旧，但开发者这边暂时没有足够的精力来升级，间接导致Android客户端短时间内无法支持Xchacha20
> 很抱歉~

把ss中关于加密的部分直接拷贝到ssr中，就可以了吧，我用ios中小火箭测试解密，加密都没有问题。貌似不是很难吧，我想问下这种直接拷贝使用的方法有啥隐患没有？

**Comment by paradiseduo** [comment]
> > @yuexiafeic Android客户端所使用的libev客户端所内嵌的libsodium密码学库过旧，但开发者这边暂时没有足够的精力来升级，间接导致Android客户端短时间内无法支持Xchacha20
> > 很抱歉~
> 
> 把ss中关于加密的部分直接拷贝到ssr中，就可以了吧，我用ios中小火箭测试解密，加密都没有问题。貌似不是很难吧，我想问下这种直接拷贝使用的方法有啥隐患没有？

小火箭不开源，不排除他们自己重新实现一套的可能
