### ISSUE TITLE
解压后没有config.json文件

### ISSUE THREAD

**Issue by TGW555** [shadowsocksrr/shadowsocksr-csharp#341]
于是我在别的网站搜到代码，自己创建了一个config.json文件，SSR可以正常使用了，就是不知道安全不安全。
   代码如下

  {
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "udp": true 
      }
    },
    {
      "port": 8080,
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy-vmess",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "456456", 
            "port": 456,
            "users": [
              {
            
                "id": "546464",
                "alterId": 64
              }
            ]
          }
        ]
      }
    },
    {
      "tag": "direct",
      "settings": {},
      "protocol": "freedom"
    }
  ],
  "dns": {
    "server": [
      "8.8.8.8",
      "1.1.1.1"
    ],
    
    "clientIp": "203.208.40.63"
  },
  
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "domain": [
          
          "cnblogs.com"
        ],
        "outboundTag": "proxy-vmess"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ]
      }
    ]
  }
}

**Comment by isKevinTrue** [comment]
Config.json is generated the first time it is started. The config.json you sent is invalid to SSR.

**Comment by TGW555** [comment]
> Config.json is generated the first time it is started. The config.json you sent is invalid to SSR.

但是它确实是我的SSR正常工作了。first time Config.json 并没有生成。我自己创建的

**Comment by Akkariiin** [comment]
点击保存就会重写Config.json
