### ISSUE TITLE
windows10 17046兼容性问题

### ISSUE THREAD

**Issue by ZhangqianStudio** [shadowsocksrr/shadowsocksr-csharp#36]
软件版本：4.9.0
系统版本： Windows 10
OS 版本：17046.rs_prerelease.171118-1403
问题症状：直接打开 ShadowsocksR-donet4.0.exe，系统托盘未出现小飞机图标且任务管理器未找到ShadowsocksR进程。以管理员权限打开同一程序，托盘仍旧未出现小飞机图标且资源管理器停止响应。

**Comment by AspirinGeyer** [comment]
收到，我们会尽快处理。

**Comment by Akkariiin** [comment]
4.8.0会出现这个问题吗？

**Comment by AspirinGeyer** [comment]
@ZhangqianStudio @Akkariiin 我前天将系统升级到 `17046.rs_prerelease.171118-1403`， 并没能重现楼主描述的问题（`4.8.0`, `4.8.1`, `4.9.0` 都测试过）。所以需要楼主补充更多信息：
1. 是不是新装的系统？
2. 请核对软件签名，确保下载的软件没有损坏。
3. 有没有安装各类国产软件，包括但不限于 360、金山毒霸、腾讯电脑管家、QQ 和搜狗拼音？

在之前观察中，有报告（但没有直接的证据）显示上述软件**可能**导致 SSR 不能正常运行。

**Comment by Prisma-illya** [comment]
你说的这个问题我之前也遇到过，可能是因为SSR目录没有写入权限或者是被设置为只读了，可能是由于杀毒软件保护原因禁止了SSR目录写入 ( 我之前是把SSR目录手动设置为只读，导致无法启动

**Comment by ZhangqianStudio** [comment]
问题已解决
更多信息：
1.不是新装系统。是由17025升级上来的。
2.经核对 软件未损坏
3.仅安装了lingoes，网易云音乐，TIM，迅雷这四款国产软件。未安装任何第三方杀毒软件
问题原因：
软件目录在系统盘ProgramFiles文件夹下，应该就是@Prisma-illya 老哥说的写入问题。更改软件目录后问题解决。
