### ISSUE TITLE
PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by botord** [shadowsocksrr/shadowsocksr-csharp#365]
操作系统win10,64位，浏览器firefox，插件是SwitchyOmega
节点可以在iOS和路由器正常访问，但是在Windows的SSR客户端配置后，命中gfwlist规则后报错,报错内容为:
----------------------------------------------------------------------------
建立安全连接失败

连接到 www.google.com 时发生错误。PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。
----------------------------------------------------------------------------
怀疑：是否是操作系统更新了.net framework引起的? 因为以前并没有出现过这个问题
尝试更新SSR客户端为最新的release版(以前用的是2018年的旧版本),仍然出现这个报错

谢谢各位

**Comment by Akkariiin** [comment]
网络问题
换个好(贵)点的服务器就没有这个问题了
