### ISSUE TITLE
软件帮助和文档网址错误

### ISSUE THREAD

**Issue by vicentory** [shadowsocksrr/shadowsocksr-csharp#366]
软件界面帮助里-关于的链接未指向本网址，打开wiki文档也未指向本网址文档，建议修改
![image](https://user-images.githubusercontent.com/10493597/73665059-6f75e180-46db-11ea-9824-3dad104f57d7.png)

**Comment by Akkariiin** [comment]
嗯，感谢提醒，其实是有意这么干的，不想让太多用机场的小白跑来填充issue
