### ISSUE TITLE
疫情期间vpn无法使用

### ISSUE THREAD

**Issue by peachzhuanyong** [shadowsocksrr/shadowsocksr-csharp#369]
疫情期间我的vpn 挂了，什么时候恢复，我的是ShadowsocksR-dotnet4.0

**Comment by Luminooous** [comment]
这是你机场的问题，墙变高了

**Comment by peachzhuanyong** [comment]
> 这是你机场的问题，墙变高了

我组长他的梯子没挂，他的是自己搭的，他说挂了是技术问题，但是他在肝论文，浙大博士不是说着玩的。。。我买的加速度的vpn是花了钱的，好难受啊。。。

**Comment by digdeep126** [comment]
我用腾讯云香港的服务器搭建的，疫情期间确实挂了，连IP也封掉一次，最后换了一个IP，目前还是无法使用....

**Comment by digdeep126** [comment]
换了 v2rayN 好了，但是速度比较慢
