### ISSUE TITLE
请问有没有可以正常退出SSR客户端的脚本或者cmd命令

### ISSUE THREAD

**Issue by StephenBen** [shadowsocksrr/shadowsocksr-csharp#370]
你好，我发现SSR客户端如果在关闭Win10系统之前没有退出的话，在重新登录Win10系统后需要重新打开客户端网络才能恢复正常，否则无法正常连接网络，而我不想设置客户端开机启动，因为我并不 是任何时候都需要代理。
    我尝试过用taskkill /f /im命令去结束进程，但是好像进程结束之后网络还是没有恢复正常。
    请问有没有正常退出客户端恢复正常网络的脚本或者命令，如果有的话我就可以添加一个关机之前执行这个脚本的计划任务。
备注：客户端版本win-4.9.0

**Comment by Akkariiin** [comment]
原因出在退出时没有清空掉系统代理设置
如果想要使用脚本杀掉进程，可以在进程退出之后使用指令关闭系统代理设置来解决
