### ISSUE TITLE
怎么知道哪条订阅失败，然后删除他

### ISSUE THREAD

**Issue by qhdhjb** [shadowsocksrr/shadowsocksr-csharp#375]
添加了几个订阅，但更新订阅时部分成功，个别提示失败，不显示失败的名称，不知道哪个订阅存在问题，无法删除失败的订阅。请指教怎么知道哪个订阅存在问题?

**Comment by qzhsjz** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        自己不翻墙的情况下浏览器访问一下不就知道了？

    在2020年2月12日 20:44，qhdhjb<notifications@github.com> 写道： 


添加了几个订阅，但更新订阅时部分成功，个别提示失败，不显示失败的名称，不知道哪个订阅存在问题，无法删除失败的订阅。请指教怎么知道哪个订阅存在问题?

**Comment by qhdhjb** [comment]
@qzhsjz 感谢帮助，会了
