### ISSUE TITLE
推荐一个好用的SSR服务，以备不时之需~

### ISSUE THREAD

**Issue by chumuye** [shadowsocksrr/shadowsocksr-csharp#40]
推荐一个自用的shadowsocks SS/SSR服务商，一直在用，速度杠杠的价格优惠低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523

**Comment by chumuye** [comment]
东西不贵，省去到处找账号的麻烦，省下的时间就是金钱！

**Comment by Prisma-illya** [comment]
我都是自己搭服务器的，用的阿里云，至今也没封

**Comment by chumuye** [comment]
自己搭一个月也要30左右吧，阿里云还是别用了，网上发点啥都被共匪知道了~
