### ISSUE TITLE
建议打开客户端时默认不显示最右侧的图片

### ISSUE THREAD

**Issue by ssrpanel** [shadowsocksrr/shadowsocksr-csharp#41]
建议打开客户端时默认不显示最右侧的图片（就是破娃那个图）...

**Comment by Prisma-illya** [comment]
哈，破娃酱这么可爱，我觉得留着比较好...
只是感觉上面那行 Click the 'Link' text box 有点多余了，如果没有那行字应该更美观...

**Comment by Akkariiin** [comment]
在某些情况下默认是不会显示右边二维码所在的整个半边的。
至于为什么有的时候又会显示，这是一个迷【笑

这个问题无伤大雅。所以不会修改。如果你喜欢的话，可以自行修改。
源码就在那里。【笑

**Comment by JohnnyWatson93** [comment]
不能赞同更多，实在是很难看……
