### ISSUE TITLE
连不上

### ISSUE THREAD

**Issue by 454832841** [shadowsocksrr/shadowsocksr-csharp#417]
刚安装好的时候能连上，但是过几天再用就连不上了，什么设置也没改啊，怎么弄

**Comment by LTHPKBTE** [comment]
你的节点确认还健在吗

**Comment by LTHPKBTE** [comment]
确认一下节点正不正常

**Comment by 454832841** [comment]
节点正常啊，能ping通

**Comment by LTHPKBTE** [comment]
我大把节点能ping通用不了=-= 问题是目前那个服务器到底还在不在运行ssr的服务？还是不是之前那个服务器？

**Comment by 454832841** [comment]
怎么知道它是不是在运行SSR的服务

**Comment by LTHPKBTE** [comment]
你是在用谁的节点，默认自带的？

**Comment by 454832841** [comment]
默认自带的不行，我就选了一个台湾宜兰的，也不行

**Comment by LTHPKBTE** [comment]
买的？还是在自带列表里选的？
自带列表那你是真敢，自带那几个都不稳，而且速度还不如分享节点

**Comment by bb33bb** [comment]
一般都不会有问题。我也用的这个。

**Comment by 454832841** [comment]
是买的套餐啊，给的那个默认的连不上我才用列表里的，都不行。前几天还好好地，这几天就突然都不能用了

**Comment by LTHPKBTE** [comment]
自带列表的我全用不了，买的和分享节点倒是没事
你试试这个
ssr://NDUuMTM1LjEzNC4xODU6MjU2MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dhelo1Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSUWcmZ3JvdXA9VEc1amJpNXZjbWM

**Comment by LTHPKBTE** [comment]
顺便问下你是怎么判断“节点无法连接”的？

**Comment by 454832841** [comment]
不知道是不是节点无法连接，不是判断，是上不了网，具体什么原因我不知道

**Comment by LTHPKBTE** [comment]
那打开服务器-服务器连接统计 然后打开浏览器，看看你连接的节点有没有连接数，有就是代理成功了，然后再看延迟一栏，有连接数的情况下延迟显示为 - 一般来说服务器就是挂了

**Comment by 454832841** [comment]
所有的连接数都是0

**Comment by 454832841** [comment]
你上面给我发的ssr那个链接怎么更新到服务器上

**Comment by LTHPKBTE** [comment]
复制之后选择“从剪切板批量导入ssr://连接...."

**Comment by LTHPKBTE** [comment]
连接数只要看目前的节点，重新打开浏览器，然后上GitHub，看看有没有连接数
真的没的话那就是代理失败或者你浏览器不理会代理

**Comment by 454832841** [comment]
有一个日本和美国的有链接数了

**Comment by LTHPKBTE** [comment]
延迟自己看，-就是挂了
其他的不说了，要休息的嘛

**Comment by 454832841** [comment]
延迟倒是没挂，但是还是连不上

**Comment by 454832841** [comment]
上不了网

**Comment by LTHPKBTE** [comment]
怎么上不了

**Comment by 454832841** [comment]
访问谷歌访问不了

**Comment by 454832841** [comment]
现在链接数又都变0了

**Comment by LTHPKBTE** [comment]
浏览器用的啥？代理模式换成全局试试

**Comment by 454832841** [comment]
谷歌浏览器

**Comment by 454832841** [comment]
代理模式本来就是全局的啊

**Comment by 454832841** [comment]
怎么办啊

**Comment by 454832841** [comment]
怎么办理退款啊

**Comment by 454832841** [comment]
找到问题了，是谷歌浏览器的原因，其他浏览器可以

**Comment by LTHPKBTE** [comment]
打开浏览器设置，看看有没有代理这一项，设成跟随系统看看（我是Firefox，chrome可能不一样）

**Comment by ZiYun-nh** [comment]
感谢，我也是chrome的原因。。。
