### ISSUE TITLE
请求发布到Windows Store

### ISSUE THREAD

**Issue by WenqiangXie** [shadowsocksrr/shadowsocksr-csharp#42]
请问是否以转置应用的形式发布到Windows Store呢？现在Windows Store也支持Win32应用，也有很多应用上架了商城，带来了更多的方便，并让更多的人接触到好软件。同时，也解决了安全性问题，避免被恶意修改。

**Comment by Akkariiin** [comment]
基于与不会发布到Google Play一样的理由，也不会发布到Windows Store
