### ISSUE TITLE
SSR客户端问题

### ISSUE THREAD

**Issue by lanalanlan** [shadowsocksrr/shadowsocksr-csharp#439]
我使用了ShadowsocksR-dotnet2.0，开启全局代理后，再次开机使用电脑时，浏览器无法使用网络，包括IE以及chrome，均显示远程计算机或设备将不接受连接，尝试了常规解决这个问题的方法，均无法使用浏览器，网络设置无法关闭代理，我尝试开启SSR之后又能使用了，但只要没有开启SSR就无法使用浏览器，控制面板无法找到SSR将其卸载，我不能一直开启SSR使用电脑，所以麻烦你们告知我解决办法，谢谢
[debug.log](https://github.com/shadowsocksrr/shadowsocksr-csharp/files/5362714/debug.log)

**Comment by PualFrank6** [comment]
用4.0呗
