### ISSUE TITLE
对以前提过的UI问题的初步修复

### ISSUE THREAD

**Issue by 0orange** [shadowsocksrr/shadowsocksr-csharp#44]
这是一个很菜的编程爱好者提的Issues....
早些时候曾提过在“编辑服务器”中重复点击“删除”按钮之后发生的错误。
但是貌似没有得到注意和修复。
所以这个很菜的爱好者尝试解决了这个问题...
https://github.com/0orange/shadowsocksr-csharp/commit/2708942e13aa01e99a05c5618d98be88d33904a0

**Comment by Akkariiin** [comment]
make an PR?

**Comment by 0orange** [comment]
好吧，可以认为我是一个爱好者在乱折腾。。。

**Comment by AspirinGeyer** [comment]
不要在意细节，感谢你的贡献 ~~
