### ISSUE TITLE
关于win10新版本下不退出软件关机开机后影响上网的问题

### ISSUE THREAD

**Issue by a3946** [shadowsocksrr/shadowsocksr-csharp#47]
Win10ltsb最新正式版本下，选用pac模式或者全局模式，不退出软件直接关机，开机后会出现ie无法正常打开网页的情况，查看局域网设置，使用自动配置脚本或为lan使用代理服务器仍然勾选。记得以前不会这样，求解。

**Comment by Prisma-illya** [comment]
正常，进程还没有将代理设置改回来就被强制结束了，导致代理仍然指向127.0.0.1
关机之前退出SSR，养成好习惯

**Comment by a3946** [comment]
记得以前不存在这个问题啊 也可能是我没注意 感谢

**Comment by wang93wei** [comment]
> 正常，进程还没有将代理设置改回来就被强制结束了，导致代理仍然指向127.0.0.1
> 关机之前退出SSR，养成好习惯

正常情况下，关机时，系统不会给程序发送 WM_QUERYENDSESSION 这条消息么，是代理系统先被系统关掉了导致的无法进行后续操作么？
