### ISSUE TITLE
pac报错

### ISSUE THREAD

**Issue by SeptemberZero** [shadowsocksrr/shadowsocksr-csharp#486]
选择pac时就会弹出
![1](https://user-images.githubusercontent.com/95155440/148011993-ef543433-7333-46ed-888c-0b04b2009d92.png)
![2](https://user-images.githubusercontent.com/95155440/148012119-c0cd888e-53e0-4bec-8d7e-8eda8c21650c.png)

**Comment by codejam-cn** [comment]
I met the same problem

**Comment by IChocolateI0v0** [comment]
我也是

**Comment by yuwenlong** [comment]
@IChocolateI0v0 @SeptemberZero @festone000 升到最新版 4.9.2 就好了

**Comment by yangy996** [comment]
> @IChocolateI0v0 @SeptemberZero @festone000 升到最新版 4.9.2 就好了

升级了也不好使
