### ISSUE TITLE
“绕过局域网和大陆” 功能对部分大陆网站造成了难言的影响（内详）

### ISSUE THREAD

**Issue by Fezreal** [shadowsocksrr/shadowsocksr-csharp#49]
系统版本win10
ssr版本4.8.0 设置如下:
系统代理模式：全局模式
PAC: 绕过大陆IP（慎用）
代理规则：绕过局域网和大陆
chrome stable最新版本 ，chrome没有任何扩展和应用，是新装的。 （和浏览器没关系，我用IE，火狐都能得出一样的结果）
-----
http://www.x3cn.com/
http://www.x3cn.com/thread-1052458-1-1.html
开了ssr并保持如上设置后， 访问这个网站的速度可以说是爆卡。
关了ssr， 秒开。

真的想不通为什么，我的代理规则选的是‘绕过局域网和大陆’， 按理来说，这个网站被判断为china，应该不受ssr影响才对的啊。

**Comment by Fezreal** [comment]
如果各位重现不了问题， 我可以录个视频。。
我这里是100%能重现，问题定位得很清楚。

**Comment by AspirinGeyer** [comment]
网站 IP 是 `59.37.88.154`，运营商是**广东-佛山-电信**，是么？

**Comment by Prisma-illya** [comment]
我在本地按照你的配置测试了一下，访问速度和没挂SSR一样快，可能是因为你的PAC文件问题？

**Comment by Fezreal** [comment]
@AspirinGeyer  IP是219.135.56.14 是广东佛山电信的。

**Comment by Fezreal** [comment]
@Prisma-illya  PAC是点击 ‘绕过大陆IP（慎用）’ 后，SSR自动更新下来的。

**Comment by Prisma-illya** [comment]
那么你可以尝试录个视频上传到youtube，然后回复到这里

**Comment by Fezreal** [comment]
@Prisma-illya
 录好了，请看。
https://mega.nz/#!RyA3FKzb!5qCS-VlcH88H7aa6038P2a222HEXoDT2qaLSXRWGCTk

**Comment by Prisma-illya** [comment]
这是我按照你的设置在本地测试的结果
https://mega.nz/#!ND4BGZDR!wJFAjFy_RLZJyu4oOW3Kc2iWf27Xq0UTVWT3iwAcQKA
但是我开启了负载均衡，并且是4.9.0版本的SSR
建议你试下更新到最新版本，如果有多个服务器试下开启负载均衡？

**Comment by Fezreal** [comment]
系统代理模式选： 全局模式   就会不正常
选直连和PAC都是正常的。

**Comment by Prisma-illya** [comment]
全局模式所有流量都会走SSR的
但是我切全局模式也能打开，就是速度慢一点，可能是服务器原因？我用的是自建的香港节点

**Comment by Fezreal** [comment]
当设置为：全局模式+绕过局域网和大陆IP 的时候， 访问x3cn.com不应该会受到代理服务器的影响，这应该是个BUG了

**Comment by allenchennnn** [comment]
点击 ‘绕过大陆IP（慎用）’ 后，SSR自动更新下来的PAC，是下载了某个地址的文件呢，还是通过apnic自动生成的？生成的PAC文件里带的域名白名单好像是多此一举啊？

**Comment by Fezreal** [comment]
@allenchennnn  你好， 请看https://mega.nz/#!RyA3FKzb!5qCS-VlcH88H7aa6038P2a222HEXoDT2qaLSXRWGCTk ，效果很清楚

**Comment by allenchennnn** [comment]
@Fezreal 首先，我提的问题，跟你的问题毫无关系。
至于你的问题，可以把整个SSR文件夹发我看下。

**Comment by ncs19960831** [comment]
也许你需要试试tracert

**Comment by dou4cc** [comment]
如果isp检测到你翻墙，你的国内网速也会跟着受影响。

**Comment by dou4cc** [comment]
测试时得清空服务器

**Comment by 0orange** [comment]
这看起来并不是程序的问题，而是你的设置导致了你主贴上面的结果。

但是我使用如下配置
       系统代理模式：全局模式
      代理规则：绕过局域网和大陆
访问百度，查IP是我VPS的IP
很神奇

**Comment by Justsoos** [comment]
首先你应该打开你的流量统计窗口，用你的 不走代理的 pac 方式访问此网站，看看是否【此时】有流量从 SSR 服务器走，再讨论深入问题。

**Comment by Fezreal** [comment]
![shadowsocksr-win-4 8 0](https://user-images.githubusercontent.com/6703674/35860683-e22aafba-0b7f-11e8-80c2-b3a007bfa3a3.jpg)
这是我的程序包，请把后缀改为7z

而且我[这个视频](https://mega.nz/#!RyA3FKzb!5qCS-VlcH88H7aa6038P2a222HEXoDT2qaLSXRWGCTk)的操作， 应该算是相当的标准而且清晰了吧。

**Comment by Fezreal** [comment]
@0orange 
![image](https://user-images.githubusercontent.com/6703674/35860925-e2f6ba1e-0b80-11e8-905f-9354a2397b11.png)

**Comment by Justsoos** [comment]
先排除一些别的问题，比如 CDN 的问题，myip.ipip.net 是高春辉作的非常精确的 IP 地址库，当你用美国 IP访问，他提供服务的服务器地址，就是美国当地 IP ：

> IP and website location: myip.ipip.net
> IP address104.24.21.50Host nameIP range104.18.56.0-
> 104.28.48.255 CIDRISPCloudflareOrganizationCloudflare, Inc.Country United States of America (US) | 
> IP range | 104.18.56.0-104.28.48.255 CIDR
> ISP | Cloudflare
> Organization | Cloudflare, Inc.
> Country | United States of America (US)

通过 pac 访问类似定位，想要查出你的网络出口是在哪里的服务，是会闹美国和中国误会的。这和dns有很大关系。

**Comment by Fezreal** [comment]
@Justsoos 我访问myip.ipip.net显示的确实是我本地的IP没错。

**Comment by Jingyu-Yan** [comment]
@Akkariiin 
我使用全局模式+绕过局域网和大陆的这种模式，本地测试我的php页面会无法访问(http://localhost:9880/index.php和http://127.0.0.1:9880/index.php都不行，但是127.0.0.1是ping通的)，ssr的日志如下
[2018-05-19 10:45:35] [Info] Direct connect localhost:9880
[2018-05-19 10:45:36] [Error] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:9880
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar)

但是如果使用PAC模式+更新PAC为绕过大陆常见域名列表，就能正常访问，并且是没有日志输出的

**Comment by Justsoos** [comment]
如果所有问题都不像是问题，那就是你的 ssr 服务器的问题。
去 https://free-ss.site 领几个免费账号再试试。
别人都没问题，只有你有问题，那这其实不是问题

**Comment by wangrush** [comment]
我用其他作者的ssr也遇到了同样的问题
系统代理模式设置全局
无论使用任何代理规则，查ip都是VPS的ip，似乎代理规则并没有生效

但是这个4.9.0版本没有这个现象，只是用绕过局域网和大陆不能访问google，但那是google自己的事

**Comment by VictorAlexanderMa** [comment]
我这边经过多次实验，将系统代理模式设置为PAC模式，PAC为绕过大陆IP，代理规则为绕过局域网和大陆最佳。否则Win10下的UWP APP如天气，邮箱等都会无法连接。如此设置的话，不影响Win10的UWP APP正常使用且各浏览器均能正常翻墙。telegram桌面端能够自动使用系统代理，但如果需要使用tor browser的话，需要单独配置为本地代理才行。在此设置方案下，可以查看到，系统的IP已经变更为了VPS的IP。

**Comment by Justsoos** [comment]
@VictorAlexanderMa 你的case可能是dns污染导致，换国内无污染dns测过才知道。而且最近很复杂，微软和谷歌服务器与dns在国内外指来指去，dns也乱

**Comment by Snylonue** [comment]
我这边好像也有类似问题，但是不知道是不是自己配置问题  
使用的是用SwitchyOmega导出pac功能生成的pac，用来代理 `googleapis.com`  
会导致部分国内外网站(尤其是Google)访问不稳定，加载时间很长但不显示连接超时  
开启了负载均衡功能  
pac文件：  
[pac.txt](https://github.com/shadowsocksrr/shadowsocksr-csharp/files/3169026/pac.txt)

**Comment by Prurite** [comment]
是否可能是dns问题？如果dns请求通过ssr发送了，则可能国内网站被解析到国外访问缓慢甚至被墙的cdn，而此时按照PAC文件该网站不会被代理，故影响访问速度

**Comment by Snylonue** [comment]
有可能是dns的问题，一些通过hosts的域名似乎不受影响。另外，shadowrocket也有这个问题。

**Comment by WaniRain** [comment]
能问一下，我ssr使用PAC模式绕过局域网和大陆，能打开google但是ytb显示没有网络连接，twittr和ins也都登录不了，但是如果全责全局模式就可以了。

**Comment by Fezreal** [comment]
没想到我在2018年还发过这样的帖子。。。。。。。。

在windows上建议各位用Clash for Windows，好用多了。

**Comment by Aminoacid1226** [comment]
> 能问一下，我ssr使用PAC模式绕过局域网和大陆，能打开google但是ytb显示没有网络连接，twittr和ins也都登录不了，但是如果全责全局模式就可以了。

我也遇到了类似的问题，请问解决了吗？
