### ISSUE TITLE
develop 下好像有 bug ？端口复用会链接不上。。。

### ISSUE THREAD

**Issue by laincat** [shadowsocksrr/shadowsocksr-csharp#5]
"remarks" : "中继接入",
"id" : "Xxxxxxxx",
"server" : "地址",
"server_port" : 443,
"server_udp_port" : 0,
"password" : "密码",
"method" : "none",
"protocol" : "auth_chain_a",
"protocolparam" : "xxxxx:密码",
"obfs" : "plain",
"obfsparam" : "intl.aliyun.com",
"remarks_base64" : "xxxxxxxx",
"group" : "端口复用",
"enable" : true,
"udp_over_tcp" : false

大概的配置是这样。。。

而非端口复用就能正常：

加密方式 chacha20
协议插件 auth_sha1_v4
混淆插件 tls1.2_ticket_auth

=======================================

再而 Master 下的版本是正常的。。。

**Comment by laincat** [comment]
话说 libsodium 1.0.14 了。。。

**Comment by Akkariiin** [comment]
端口复用是什么特性？

上面的配置不是auth_chain_a/plain/none么
为什么下面又说auth_sha1_v4/tls1.2_ticket_auth/chacha20呢？

<hr/>

libsodium待会儿就升，只是libev那边暂时没法升

**Comment by laincat** [comment]
这是端口复用的 配置 出处。
https://breakwa11.blogspot.hk/2017/01/shadowsocksr-mu.html

===

两种配置在同一服务端及客户端（Master）能正常使用。而在 develop 下 出现了无法使用端口复用的配置，而一般配置能正常。

**Comment by laincat** [comment]
（从配置来看，不应该有问题。。。这些东西应该跟服务端来管理有关，不知道跟 protocolparam 这个有没有关系？

**Comment by Akkariiin** [comment]
哦，单端口多用户啊，auth_chain_*没实现这个

**Comment by candy2107** [comment]
个人认为新协议不要搞多用户,
上个版本的前车之鉴是开多用户,惹怒了一些卖ss的人,导致开发者被查水表

**Comment by laincat** [comment]
…不知道何出此言，反正肯定不是因为这个原因。

**Comment by Akkariiin** [comment]
暂时不要用新版，我要回滚
libsodium所在的dll项目库版本好像搞错了，漏了一些接口

**Comment by laincat** [comment]
好的…目前我也就测试着玩。
