### ISSUE TITLE
4.9源码本地调试，无法正常启动

### ISSUE THREAD

**Issue by ssrpanel** [shadowsocksrr/shadowsocksr-csharp#52]
---------------------------
Microsoft Visual Studio
---------------------------
由于缺少调试目标“C:\Users\Administrator\Desktop\shadowsocksr-csharp-4.9.0\shadowsocksr-csharp-4.9.0\test\bin\Debug\test.dll”，Visual Studio 无法开始调试。请生成项目并重试，或者相应地设置 OutputPath 和 AssemblyName 属性，使其指向目标程序集的正确位置。
---------------------------
确定   
---------------------------

呃呃呃，实在不懂，求指教

**Comment by AspirinGeyer** [comment]
我个人没有遇到过这类问题，所以没办法给出太多帮助。
从错误信息来看，似乎 “生成” 一次可以解决问题。
