### ISSUE TITLE
请问，能否加入chacha-ietf-poly1305和aes-xxx-gcm系列加密方式

### ISSUE THREAD

**Issue by ssrpanel** [shadowsocksrr/shadowsocksr-csharp#53]
如题，谢谢

aes-128-gcm
aes-192-gcm
aes-256-gcm
chacha-ietf-poly1305

**Comment by AspirinGeyer** [comment]
正如你所见到的，这并不是一件很容易的事情。
参见 [这个 Issue](https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/34) 中 @Akkariiin 对 AEAD 系列算法的说明，以及我们为什么**不会**在 SSR 中添加对 AEAD 算法的支持。

**Comment by ssrpanel** [comment]
sorry，
