### ISSUE TITLE
4.9版本订阅服务器，和从剪切板导入服务器失败问题

### ISSUE THREAD

**Issue by wowsonsun** [shadowsocksrr/shadowsocksr-csharp#56]
**4.9版本**订阅服务器时会订阅失败，如下图
![TIM截图20180115105804.jpg](https://i.loli.net/2018/01/15/5a5c1b689b119.jpg)
且从剪切板导入链接也会报错。错误信息如下图。
![TIM截图20180115105014.jpg](https://i.loli.net/2018/01/15/5a5c1b3ec24d9.jpg)
以上操作，在**4.4.6版**本都可以正常使用，并无失败和错误信息。

> 

> 是否是ssr链接的生成有改动造成的

**Comment by Kisesy** [comment]
现在解base64的地方都是用的 DecodeUrlSafeBase64 这类的函数，但是网上有些地址是用的标准base64编码来编码，所以出错了。把解base64的函数写的兼容性高一些应该能解决

**Comment by AspirinGeyer** [comment]
**二维码/链接** 这一块是一个历史遗留问题，最早设计的时候把 `Base64` 后面的 `padding` 去掉了，然后 C# 客户端在这块还比较严格（不能有 `padding`）。可以参考 [这份文档](https://github.com/shadowsocksrr/shadowsocks-rss/wiki/SSR-QRcode-scheme) 。

建议手动解码一条链接，看看是不是链接生成的有问题（有 `padding` 什么的），我刚开始用 SSR 的时候也遇到过这个问题，检查后发现是链接生成的有问题。

**Comment by wowsonsun** [comment]
应该是base64的问题了，我使用的base64尾部是带有两个等号的。而我用4.4.6版本导进去，再复制出来的base64尾部是没有两个等号的，且这时可以把链接导入4.9版本
