### ISSUE TITLE
可否加入访问来源

### ISSUE THREAD

**Issue by ssrpanel** [shadowsocksrr/shadowsocksr-csharp#58]
因为当通过代理访问网站时，对于网站来说，请求头部信息中带有如下（假设本地端口1080）
Remote Address:127.0.0.1:1080

网站屏蔽代理访问，则可以直接限制127.0.0.1这个IP

**Comment by ssrpanel** [comment]
可否自定义，或者带入随机remote address

**Comment by kasuganosoras** [comment]
除非将SSR变成高匿代理，否则一样可以通过判断X-Forwarded-For来确定客户端是否使用了代理

**Comment by Justsoos** [comment]
ssr/ss 本身就是高匿代理。并不存在你们说的问题

**Comment by AspirinGeyer** [comment]
这件事情不是 SOCKS5 代理应该做的事情，它也没有能力去修改包的内容。
