### ISSUE TITLE
作者，你好，看到麻烦你抽时间回复一下

### ISSUE THREAD

**Issue by qydm** [shadowsocksrr/shadowsocksr-csharp#6]
![img_0182](https://user-images.githubusercontent.com/31095150/31063364-ed78386c-a764-11e7-88d9-9e7dc87c9d30.JPG)

服务器IP那一栏，我填了好几个IP,因为其他的配置端口都一样，请问这样可以吗，还是必须要一个一个单独填写，麻烦回复一下

**Comment by yiding-he** [comment]
楼主你要的是负载均衡的功能，这个已经有了。应该不会再开发这种重复的功能了。

**Comment by Akkariiin** [comment]
需要单独填写

你喜欢的话，可以打开配置文件，然后，复制/粘贴
