### ISSUE TITLE
梯子突然无法使用

### ISSUE THREAD

**Issue by pourer** [shadowsocksrr/shadowsocksr-csharp#61]
梯子无法翻墙成功

**Comment by kasuganosoras** [comment]
提这个Issue之前，请先确认：
1.你的SSR版本是最新的吗
2.你的SSR服务器版本是最新的吗
3.你的SSR服务器可用/在线吗
4.你所使用的运营商是否屏蔽了你的SSR服务器IP？

如果不能解决问题，你可以尝试：
1.升级你的SSR
2.如果是你自己搭建的SSR服务器，升级你的SSR服务端版本
3.更换一个节点再试试
