### ISSUE TITLE
请求支持aes-128-gcm、chacha20-ietf-poly1305等新加密方式

### ISSUE THREAD

**Issue by 523860169** [shadowsocksrr/shadowsocksr-csharp#63]
如题

**Comment by wenliyang** [comment]
https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/53

**Comment by AspirinGeyer** [comment]
正如你所见到的，这并不是一件很容易的事情。
参见 [这个 Issue](https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/34) 中 @Akkariiin 对 AEAD 系列算法的说明，以及我们为什么**不会**在 SSR 中添加对 AEAD 算法的支持。
