### ISSUE TITLE
建议能加密配置文件

### ISSUE THREAD

**Issue by codejam1024** [shadowsocksrr/shadowsocksr-csharp#64]
是否加密配置文件，防止国产软件扫描获取信息，感觉安全点

**Comment by kasuganosoras** [comment]
为什么要用国产杀软呢 ( 笑

**Comment by Akkariiin** [comment]
我记得有加密功能的呀...试试设置客户端密码.

**Comment by Junming-Chen** [comment]
微信已经开始搞事情了

![image](https://user-images.githubusercontent.com/25316415/58785160-90030e80-8617-11e9-82ad-85f807e148d1.png)
