### ISSUE TITLE
最近大量SSR被墙 是否已经被精确识别？

### ISSUE THREAD

**Issue by huohu4399** [shadowsocksrr/shadowsocksr-csharp#66]
最近哀鸿遍野   各大VPS服务商都有大量ip被封   ss和ssr都有挂的   是天朝已经能精确识别特征了么？

**Comment by iseeyo** [comment]
都挂了。。。貌似aead_aes_256_gcm协议还可以使用。。。

**Comment by Prisma-illya** [comment]
你们这样乱传消息是要负泽任的，民白吗
挂了多半是IP地址被运营商屏蔽，这种情况只能换服务器
我就在用aes_256_cfb，auth_chain_b，tls1.2_ticket_auth，香港阿里云自建节点
<img src="http://phpmc.oss-cn-shanghai.aliyuncs.com/cdnfiles/images/20180128001902.jpg">

**Comment by huohu4399** [comment]
什么叫乱传消息？   现在就是很多被封  而且肯定是墙的问题   难道这么多服务商一起商量好了屏蔽？    你用阿里云建   也不怕查水表？ @Prisma-illya

**Comment by birdofprey** [comment]
国内 云叔叔们会定期去复制数据

**Comment by kasuganosoras** [comment]
阿里云搭SSR怕啥，阿里云能识别SSR流量？要是阿里云都能识别了，GFW还识别不出来？完全就是瞎操心

**Comment by Justsoos** [comment]
阿里监控云服务器内进程，端口，甚至流量内容，不是新闻了。同学不要太天真。

**Comment by kasuganosoras** [comment]
就是他那个监控插件嘛，他要依赖那个插件才能监控你的进程，我早就删了

**Comment by Justsoos** [comment]
你以为你删了那个你以为是监控插件，你就是 IDC 的加州之王了吗？ 虚拟机底层你看不到进程的玩法有的是。

我这里指出的是，你认为 阿里 IDC 与 GFW处在同一个监控位置，是完全错误的。云服务器拥有你所有流量和计算的窥视能力。

**Comment by kasuganosoras** [comment]
而且我建来就是自用的，又不是搭来卖的，日常连接数量就1，阿里云会闲到来管？他们要查也是查那些日常连接上百上千的IP，个人小用户他们才没这时间去管那么多，低调点就好

**Comment by kasuganosoras** [comment]
就算被查到了顶多就删机器警告什么的，大不了就去其他地方再租就好了，没多大事

**Comment by Justsoos** [comment]
好吧，你终于可以用最牛皮的无赖脸皮对付阿里云，对付党妈了，你歪楼，你赢了。（手动笑晕

**Comment by kasuganosoras** [comment]
<img src="http://phpmc.oss-cn-shanghai.aliyuncs.com/cdnfiles/images/20180128152959.png">不过还是感谢你的提醒，中国移动已经盯上我的阿里云了，两个月之前就在全国范围屏蔽了我阿里云的IP，等过段时间我还是换谷歌云吧

**Comment by birdofprey** [comment]
出门要穿衣服。也要使用常用数据类门牌号。

**Comment by Justsoos** [comment]
我其实已经上面说了，开机场的也不都是弱智，有人卧底购买大机场的账号，然后举报所有 IP，可能是最近这次事件的真实情况。
如果的确如此，和精准识别协议一毛钱关系都没有。

**Comment by kasuganosoras** [comment]
是的，所以有条件还是自己搭比较安全，尽量用国外云，我用阿里云只是贪方便，阿里云主要还是用来搭frp内网穿透的，因为免备案，还可以用来搭个SSR偶尔翻墙用

**Comment by jasonliul** [comment]
以前逢年过节是宰狗的, 百万狗ip献给党.... 现在狗没了...

只好宰几只便宜小雕祭祖, 连续几天看一群祥林妈哭的~~~ 秀才们编造一对裹脚神话.

宰宰就习惯了~~ :)

**Comment by Justsoos** [comment]
现在依然如此，叫杀鸡儆狗
话说，没了你们折腾 FQ，GFW相应工作人员都要丢工作，一年百亿GDP因此无踪影。你，很重要的

**Comment by huodaye** [comment]
我的阿里云ssr已经发了警告，就在前几天。。。

**Comment by naverdo** [comment]
阿里云硅谷及香港节点ssr稳定使用中。我想说的是，只可能钓鱼机场，散户杀不过来的。手动无奈

**Comment by Akkariiin** [comment]
SSR(R)这么多不同的加密/混淆/协议，在理论上就不存在方法可以精确地将SSR(R)的所有协议与非SSR(R)的所有协议区分开

所以担心是否SSR(R)被精确识别，不如考虑一下哪个加密/混淆/协议的组合比较不容易被识别出来

**Comment by huohu4399** [comment]
所以  大佬   已经来了  说下哪个协议最好呢？  给个推荐 @Akkariiin

**Comment by Akkariiin** [comment]
我现在自用的是 auth_chain + chacha20 + plain
@huohu4399

**Comment by huohu4399** [comment]
谢谢  希望有朝一日   也能为社区做贡献   其实虽然SSR是免费的  但也可以设置一个捐款   每个人使用的   捐一块（天朝就人多）   这样  没有足够能力编程的  也可以支持社区

**Comment by Akkariiin** [comment]
我也很想接受捐款呀~
但是捐款会泄露开发者身份，所以在找到安全的捐款渠道之前暂时无法接受捐款。 @huohu4399

**Comment by huohu4399** [comment]
可以考虑paypal   隔壁有项目  就是用的paypal  有需求翻墙   有稳定工作的   捐个10刀   不成问题（VPS都要几百块一年） @Akkariiin    当然安全第一

**Comment by kasuganosoras** [comment]
比特币或许是个很好的捐赠方式

**Comment by Akkariiin** [comment]
@huohu4399 paypal能反查路径，正在考虑礼品卡什么的..
数字货币不是很感冒..而且操作不慎一样可以受到追踪...

**Comment by iMusi** [comment]
捐款可以借鉴电信诈骗的那些手段，嘿嘿

**Comment by Justsoos** [comment]
@Akkariiin  不知道门罗币么？。。。专门用来隐匿支付。。。好吧，都是卖毒品的在用，哈。

**Comment by huohu4399** [comment]
要死了  在瓦工的年付VPS   换了两个ip  都被封了   最近这个只撑了半天   为什么能这么准确的被扫到？  难道是因为用的瓦工自带的一键安装（页面命令行太难用）？  里面是默认tls1.2_ticket_auth混淆 不能改  现在有钱也难出去   到底怎么回事啊？

**Comment by Justsoos** [comment]
不要自作多情了，是大佬们在修仙，至少2个月，甚至会半年以上。所以 …… 忍着吧

**Comment by huohu4399** [comment]
白名单的节奏？

**Comment by Justsoos** [comment]
互联网已经成为经济核心实体，白名单是不可能的，那意味着国家紧急状态，意味着大资本家们的核心利益受损，所以那是不可能发生的。。。 但让小屁民们 FQ 成本激增是完全可以做到的。

**Comment by huohu4399** [comment]
如果狠了心  土共一直维持这样的修仙状态   那我们这不是永远翻不出去了？   其实也算是被克制了吧   要是能做到土共投入再多钱   也封不住就好了  自由无价

**Comment by huohu4399** [comment]
还一个  用 ipv6是否是一个办法   ipv6地址那么多  应该封不过来   但我试了下（vultr家的 自带ipv6）   速度极其慢   也不知道是我配置问题还是ipv6不够普及

**Comment by Justsoos** [comment]
GFW 的存在，是一个 “精英化逼迫” 过程，不是一句两句能解释的现象，这个国家的最大权力在精英手中，精英可以通过各种手段免墙。比如，你可以设想精英们闲得无聊，打飞机去美国上个网，或者健身直播……  不断提高翻墙成本，即过滤非精英，留下无知屁民的一个时代特征明确的手段。

**Comment by Justsoos** [comment]
最好还是翻墙之后，多学习使用google，目前大陆基本没有真 ipv6，都是在 GFW 监视之下的真 ipv4，不要幻想某党和精英们不知道你可以这么悄悄的偷鸡，打枪的不要。

**Comment by dou4cc** [comment]
@Justsoos 精英化逼迫的党内民主时代已经过去。

**Comment by birdofprey** [comment]
事实证明以盈利为目的的VPN就是一种邪恶。它本身就不是为了网络自由

**Comment by huohu4399** [comment]
神逻辑 @birdofprey

**Comment by Justsoos** [comment]
精英不需要对屁民释放民主，精英们也不希望对绿教释放民主，精英们认为对中国人需要管起来，精英们要搞新帝国主义，来攫取最大化 “维稳” 利益。美国二战后成为全世界资本避难所，原因绝不是自由，而是其在西方世界对抗苏联帝国主义，之后对抗恐怖主义，对抗地方冲突，美国表现出来的世界警察的维稳能力，因此美国成为全球资本强力吸铁石，利益最大化。纽约时报最近评论不错，全世界都有威权化倾向。中国也在搞新帝国主义，国内高压维稳，是第一步，老话说了，攘外必先安内 @dou4cc

**Comment by IAMBADCODER** [comment]
你们是你们口中的精英吧，这么熟练。

**Comment by flyp1028** [comment]
我已经两次被墙了，不知道到底什么情况，是精准定位还是错杀1000


2018-03-01 1:38 GMT+08:00 IAMBADCODER <notifications@github.com>:

**Comment by sblig** [comment]
http://27yun.vip/aff.php?aff=55
偶然遇见，挺方便的

**Comment by huohu4399** [comment]
天下大赦  可喜可贺  我搬瓦工的ip出狱了   不过应该只是服务商被盯上了   我在冷门服务商搭建的就一直好好的   SSR本身没问题  目前五个VPS都正常使用   谢谢破娃酱等等社区大佬们一直的努力

**Comment by mqcing** [comment]
我的banwagong上 酸酸乳也被q了， 妈的我就一个人用。。我招谁惹谁了。。

**Comment by Xtract78** [comment]
最近一周Bandwagon上被墙了3个IP....换不起了啊。就自己在YouTube上看看视频，还都是科技内容

**Comment by jasonliul** [comment]
一键导入, 二维码, 订阅...
这些方便懒蛋的玩意是祸害, 使用图片或文字[严防爬虫]试试~~~

**Comment by irvingow** [comment]
今天上午突然跪了, ip没被封但是tcp数据过不来, 之前一年多都好好的, 怎么突然又出了问题

**Comment by Justsoos** [comment]
退订本主题了，如此翻墙技术已经成了巫婆神汉，神秘超自然力量，阴毛论与反G咒骂，外行低俗话题。

**Comment by kasuganosoras** [comment]
最近发现一个套路，稳得一批，因为 Minecraft 这个游戏的服务器运行在 25565 端口，我就魔改了一个游戏用的反向代理 BungeeCord，做一个判断，当传入的连接不是游戏的协议时，自动转发给 127.0.0.1:23333，也就是 SSR 的运行端口，然后再 iptables 做规则屏蔽外部访问 23333，剩下的正常游戏流量则转发给真正的游戏服务器。
这样的话，可以通过 25565 端口进入游戏，还可以用这个端口连接 SSR，降低被审查几率，就算被查到了也会认为这只是个游戏服务器，稳得一批，我的 Vultr 机器和另一家服务商租的机器至今没被封过。
提示下：推荐去租一些没有名气的服务商，越偏门的越好，这样被重点监控的几率越小。

**Comment by kasuganosoras** [comment]
然后就是，GFW 新的一种屏蔽模式，你能 Ping 通，但是任何 TCP 连接都无法建立，具体可以看我 blog 上的一篇文章，上个月还出现了几次全部国外网站无法打开的情况，V2EX 很多人都表示遇到了这个情况，有人推断应该是 GFW 新的屏蔽模式，根据协议来屏蔽的。

**Comment by DNrover** [comment]
> 天下大赦 可喜可贺 我搬瓦工的ip出狱了 不过应该只是服务商被盯上了 我在冷门服务商搭建的就一直好好的 SSR本身没问题 目前五个VPS都正常使用 谢谢破娃酱等等社区大佬们一直的努力

破娃早就停止ssr项目了。。。

**Comment by acfrr** [comment]
说一个我的发现，不太懂原理。但是我被墙的banwagong可以通过配合FinalSpeed的方式继续翻，单独用被墙，SSH也没法用。但配合FinalSpeed用却可以看4K，就是延迟稍高一点。我用另一台翻墙重新装的SSR和FinalSpeed垂死挣扎一下却发现能用，你们试试。

**Comment by hhecoder** [comment]
> 说一个我的发现，不太懂原理。但是我被墙的banwagong可以通过配合FinalSpeed的方式继续翻，单独用被墙，SSH也没法用。但配合FinalSpeed用却可以看4K，就是延迟稍高一点。我用另一台翻墙重新装的SSR和FinalSpeed垂死挣扎一下却发现能用，你们试试。刚看了上面的回答GFW新屏蔽方式只屏蔽TCP，然后FinalSpeed把 TCP 包装成 UDP来运作的，然后就通了？我的猜测。

3q. 成功，我又复活了

**Comment by r98522608** [comment]
應該不是協議被擋
小弟gcp + ssr 自建的
換個ＩＰ 
又生龍活虎了

**Comment by matou2** [comment]
若若的问一下，啥叫SSR,菜鸟报道

**Comment by bibichuan** [comment]
谷歌云用了快一年了，最后几天被封了，换了个ip，不太稳定。我就上谷歌，从不反党，反社会主义，我还是相信这个国家的，相信社会主义的，相信共产党的，为啥还是不放过我。只是因为百度做的广告太多了，根本用不了啊，所以才翻墙的。

**Comment by Xtract78** [comment]
> 谷歌云用了快一年了，最后几天被封了，换了个ip，不太稳定。我就上谷歌，从不反党，反社会主义，我还是相信这个国家的，相信社会主义的，相信共产党的，为啥还是不放过我。只是因为百度做的广告太多了，根本用不了啊，所以才翻墙的。

应该跟放不放过没啥关系……可能只是运气不好。我去年初开始用搬瓦工，前面一直很好，但是7，8两个月内连续被封4个IP，后面又都好了。帮同事弄的搬瓦工，用的还是自带一键安装的那种，从去年10月份到现在一直安然无恙。

**Comment by WontStop** [comment]
运营商也是很大一个问题，使用移动流量访问代理一直没有问题，但是使用铁通就经常出现代理无法访问的情况，很多时候第一次能访问，再刷新就无法访问了。

**Comment by adu4862** [comment]
目前任然在使用SSR,基本上几天到十几天之间会被封一个ip,最近发现上youtube后,会被迅速封ip

**Comment by Akkariiin** [comment]
我的12个自用的服务器全都一直没有问题
有问题请问服务提供商

另外，世界加钱可得
