### ISSUE TITLE
Visual Studio 2017 15.5.5打开代码发现错误(有图)

### ISSUE THREAD

**Issue by 0orange** [shadowsocksrr/shadowsocksr-csharp#67]
![qq 20180127212310](https://user-images.githubusercontent.com/34394536/35472364-b1453e8a-03a8-11e8-8f4a-37fa923c7fa7.jpg)
更新了一把VS。。发生了编译问题

**Comment by Akkariiin** [comment]
it fixed on https://github.com/shadowsocksrr/shadowsocksr-csharp/pull/78 , thank you~
