### ISSUE TITLE
能否更新一下，添加两个加密方式

### ISSUE THREAD

**Issue by dozen007** [shadowsocksrr/shadowsocksr-csharp#68]
aes-128-gcm
chacha20-ietf-poly1305

**Comment by AspirinGeyer** [comment]
正如你所见到的，这并不是一件很容易的事情。
参见 [这个 Issue](https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/34) 中 @Akkariiin 对 AEAD 系列算法的说明，以及我们为什么**不会**在 SSR 中添加对 AEAD 算法的支持。
