### ISSUE TITLE
new encryption method

### ISSUE THREAD

**Issue by CGQAQ** [shadowsocksrr/shadowsocksr-csharp#73]
Please do support new method "chacha20-ietf-poly1305" 
thank you

**Comment by CGQAQ** [comment]
fuck   chacha20-ietf,,,,,,,different name
![image](https://user-images.githubusercontent.com/15936231/35723828-acd22196-0836-11e8-8bfd-35d294420c30.png)
hand change to below, it works,
![image](https://user-images.githubusercontent.com/15936231/35723836-b3a6ecae-0836-11e8-9f2f-d0177060d32e.png)

thank you for continuing to maintain SSR

**Comment by CGQAQ** [comment]
not really, 
I just retry it, I am wrong
chacha20-ietf is not short for chacha20-ietf-poly1305
Please add it

**Comment by Akkariiin** [comment]
no -poly1305
it's ADAE mode.

reason on there : https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/34

**Comment by CGQAQ** [comment]
but ss have it

**Comment by CGQAQ** [comment]
![qq 20180203141850](https://user-images.githubusercontent.com/15936231/35763730-44781454-08ed-11e8-9c35-f0e31130652a.png)
look this
