### ISSUE TITLE
绕过局域网和大陆 使用的是哪个文件来判断？

### ISSUE THREAD

**Issue by wjk199511140034** [shadowsocksrr/shadowsocksr-csharp#75]
#########################
不好意思，疑问有点多哈
#########################
更新pac为 绕过大陆ip 和 绕过gfw 的源在哪里呢？打开pac文件头看了一下，好像是使用的破娃酱以前写的地址列表，貌似已经半年多没更新了
代理规则里面的 绕过局域网和大陆 使用的本地文件是哪个？更新源又是哪个呢？
###########################
还有，浏览器代理如果写pac(http://127.0.0.1:1080/pac)判断的话，是先由pac判断之后再交给代理规则判断，还是pac判断之后直接代理呢？
说的有点乱，我画个图吧

请求网址---->pac判断---->代理规则判断---->代理
　　　　　　　　|　　　　　　　|
　　　　　　　直连 　　　　　直连

请求网址---->pac判断---->代理
　　　　　　　　|                          
　　　　　　　直连                    
#############################
我为什么关心这个问题呢，是因为一开始我都直接写socks5，127.0.0.1:1080，结果看日志好多Direct connect XXXXX:80，造成日志很长，看的我眼花缭乱
后来写成PAC，http://127.0.0.1:1080/pac，日志里面只有connect XXXXX:80，明显简洁了，然而实际体验好像比直接写sockst5，127.0.0.1:1080打开网页要慢些

**Comment by Akkariiin** [comment]
现在的源在这里
https://github.com/shadowsocksrr/breakwa11.github.io/tree/master/ssr

**Comment by lan542662** [comment]
> 现在的源在这里
> https://github.com/shadowsocksrr/breakwa11.github.io/tree/master/ssr

请教一个问题，全局中的自定义(192.168.xxx是direct)或者绕过局域网都不能访问局域网的打印机设置，但是直连或者pac却可以访问。
