### ISSUE TITLE
开着PAC模式和全局模式没区别

### ISSUE THREAD

**Issue by zhenlinhgs** [shadowsocksrr/shadowsocksr-csharp#79]
正常我们不配置帐号的时候，开着PAC模式是可以开国内网页的，这个版本不配置帐号，切换成PAC也开不了国内的网络，配置帐号个线路上面，开着PAC模式，搜索IP确是我们的代理IP，不是我们的本地IP，不知道这个不是不BUG

**Comment by im0qianqian** [comment]
你需要更新一下 PAC，使用 GFWlist 就可以了
