### ISSUE TITLE
shadowsocksrr

### ISSUE THREAD

**Issue by LUIGILINWEICHENG** [shadowsocksrr/shadowsocksr-csharp#8]
ShadowsocksR-win-4.8.0 
Connected to the server, but not on Google.
Just wait for the information, so help me.

**Comment by qijiangh** [comment]
Help what? Could you provide some more information?

**Comment by LUIGILINWEICHENG** [comment]
ShadowsocksR-win-4.8.0   
I use this software, as usual, connected to the server, but Google, pinterest these sites do not go. I saw the software diary that I couldn't connect




------------------ 原始邮件 ------------------
发件人: "qijiangh";<notifications@github.com>;
发送时间: 2017年10月16日(星期一) 下午4:03
收件人: "shadowsocksrr/shadowsocksr-csharp"<shadowsocksr-csharp@noreply.github.com>;
抄送: "浮生一梦"<395243789@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocksrr/shadowsocksr-csharp] shadowsocksrr (#8)




Help what? Could you provide some more information?

**Comment by Akkariiin** [comment]
so, what about your server config? server version? and what config you are using ?

**Comment by LUIGILINWEICHENG** [comment]
Wingy, can't you use it, you know?




------------------ 原始邮件 ------------------
发件人: "Akkariiin";<notifications@github.com>;
发送时间: 2017年11月4日(星期六) 晚上7:54
收件人: "shadowsocksrr/shadowsocksr-csharp"<shadowsocksr-csharp@noreply.github.com>;
抄送: "浮生一梦"<395243789@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocksrr/shadowsocksr-csharp] shadowsocksrr (#8)




Closed #8.

**Comment by Akkariiin** [comment]
so, what's your server config? server version? and what config you are using ?
you dont give me more info, i cannot to diagnose your issue. 
so, close this issue until who give more info to let this issue valuable .

**Comment by LUIGILINWEICHENG** [comment]
Here's the thing: I bought SSR on the wingy website and I can't use it now. Can you share the new SSR to me?









------------------ 原始邮件 ------------------
发件人: "Akkariiin";<notifications@github.com>;
发送时间: 2017年11月4日(星期六) 晚上10:49
收件人: "shadowsocksrr/shadowsocksr-csharp"<shadowsocksr-csharp@noreply.github.com>;
抄送: "浮生一梦"<395243789@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocksrr/shadowsocksr-csharp] shadowsocksrr (#8)




so, what's your server config? server version? and what config you are using ?
 you dont give me more info, i cannot to diagnose your issue.
 so, close this issue until who give more info to let this issue valuable .

**Comment by LUIGILINWEICHENG** [comment]
Here's the thing: I bought SSR on the wingy website and I can't use it now. Can you share the new SSR to me?


------------------ 原始邮件 ------------------
发件人: "Akkariiin";<notifications@github.com>;
发送时间: 2017年11月4日(星期六) 晚上10:49
收件人: "shadowsocksrr/shadowsocksr-csharp"<shadowsocksr-csharp@noreply.github.com>;
抄送: "浮生一梦"<395243789@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocksrr/shadowsocksr-csharp] shadowsocksrr (#8)




so, what's your server config? server version? and what config you are using ?
 you dont give me more info, i cannot to diagnose your issue.
 so, close this issue until who give more info to let this issue valuable .

**Comment by LUIGILINWEICHENG** [comment]
The software version I'm using now is ShadowsocksR-win-4.8.0





------------------ 原始邮件 ------------------
发件人: "Akkariiin";<notifications@github.com>;
发送时间: 2017年11月4日(星期六) 晚上10:49
收件人: "shadowsocksrr/shadowsocksr-csharp"<shadowsocksr-csharp@noreply.github.com>;
抄送: "浮生一梦"<395243789@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocksrr/shadowsocksr-csharp] shadowsocksrr (#8)




so, what's your server config? server version? and what config you are using ?
 you dont give me more info, i cannot to diagnose your issue.
 so, close this issue until who give more info to let this issue valuable .

**Comment by Akkariiin** [comment]
@LUIGILINWEICHENG you can find the newest release on the project release page.
