### ISSUE TITLE
建议在下一版本加入，切换服务器时，断开与之前服务器的所有连接！

### ISSUE THREAD

**Issue by shido520** [shadowsocksrr/shadowsocksr-csharp#81]
如题
建议在下一版本加入，在不使用负载均衡的时候，切换服务器时，断开与之前服务器的所有连接！

**Comment by bitkylin** [comment]
#82 这个新的特性我已经添加进去了，简单测试了一下，体验挺好，达到了我的预期目标，哈哈，就看老大 @Akkariiin 是否接受我的 PR 了。

**Comment by dna1982** [comment]
完全没必要 自己双击一下就断开了
自动断开反而不够灵活。

**Comment by bitkylin** [comment]
@dna1982 双击哪里会断开呢？

**Comment by qhfls** [comment]
@dna1982 同问，双击哪里？

**Comment by dna1982** [comment]
双击“连接”。好几种TAB双击都有对应的功能，自己多试试。

**Comment by hxzmm** [comment]
@bitkylin 试用了一下你的代码，很好用，这下就方便多了，不用每次去点断开连接

**Comment by bitkylin** [comment]
@hxzmm 谢谢

**Comment by wxlg1117** [comment]
@dna1982,双击“连接”。好几种TAB双击都有对应的功能，自己多试试>>>求截图,到底是双击哪? SSR GUI上哪有单独的 连接 俩个中文字?
