### ISSUE TITLE
SSRR(SSR)的tls1.2_ticket_(fast)auth可能存在问题

### ISSUE THREAD

**Issue by railjty** [shadowsocksrr/shadowsocksr-csharp#85]
![image](https://user-images.githubusercontent.com/30927889/36637437-cf40ef40-1a16-11e8-93ed-9b2fcc2b1994.png)
这是我自己在局域网测试tls1.2_ticket_(fast)auth的时候，发现wireshark不能识别为TLS流量（截图用了原版SSR-python服务器+原版SSR C#4.7,但SSRR-dev分支+SSRRC#4.9也是一样的）
![image](https://user-images.githubusercontent.com/30927889/36637481-9cd36aa0-1a17-11e8-8052-7df4e5e8cba1.png)
![image](https://user-images.githubusercontent.com/30927889/36637507-25bd4656-1a18-11e8-9929-70bd57307814.png)
这是正常的Session Ticket流量（截图ip为https://imququ.com/ ,  使用浏览器IE11来测试TLS）
Wireshark Build:
![image](https://user-images.githubusercontent.com/30927889/36637521-7b3c7b42-1a18-11e8-8933-cd7567ba20a6.png)
右下的SSTAP，SOCKSCAP64与此无关，我直接用了SSR（R）的SOCK5代理

**Comment by AkaneAkaza** [comment]
改端口为443

**Comment by railjty** [comment]
好的我试下

**Comment by railjty** [comment]
可以用，但我想的是在其他port上伪装，另外可否加入TLS1.3 1/0-RTT的混淆呢？这更快也更难识别(直接ticket容易被统计发现，1.3的0rtt不会)

**Comment by railjty** [comment]
我指的是第一次连接服务器先1个rtt，之后全0个rtt(同时更新psk)
