### ISSUE TITLE
关于订阅功能的一点小建议。

### ISSUE THREAD

**Issue by WayChan** [shadowsocksrr/shadowsocksr-csharp#88]
首先订阅的时候，如果单纯的修改订阅地址，更新订阅之后会发现旧的地址未被清除，需要再次执行一次订阅。调试发现
MenuViewController.cs 第422-425行
if (lastGroup == null)
{
    lastGroup = curGroup;
}
判断未生效。改成
if (String.IsNullOrEmpty(lastGroup))
{
    lastGroup = curGroup;
}
正常。建议可以修复该功能。

**Comment by Akkariiin** [comment]
感谢~

**Comment by WayChan** [comment]
@Akkariiin 是否可以考虑添加订阅地址或者编辑订阅地址之后，点击确定的时候进行一次订阅更新？

**Comment by AspirinGeyer** [comment]
从 master 的代码看已修复，故 Close。
