### ISSUE TITLE
使用浏览器下载文件时，上传速度满载

### ISSUE THREAD

**Issue by wowsonsun** [shadowsocksrr/shadowsocksr-csharp#90]
**4.9版本在下载文件时，上传速度会飙满，想知道这里是在上传什么= =**
![TIM截图20180320174200.jpg](https://i.loli.net/2018/03/20/5ab0d785d4041.jpg)

**Comment by GoogleGFW** [comment]
那是你本机的流量，从SSR到被代理的软件。

**Comment by ncs19960831** [comment]
题外话，360，祝你好运

**Comment by wowsonsun** [comment]
题外话，谢谢你的关心

**Comment by wowsonsun** [comment]
@GoogleGFW  谢谢回答

**Comment by Akkariiin** [comment]
这个是把本地回环loopback流量也算到里面了，理论上一个设计正常的网络监控程序是应该区分这两种流量的。

---

另外，建议不要在具有科学上网功能的设备上使用360等国产“安全”软件，勿谓言之不预也~
