### ISSUE TITLE
混淆 无法连接

### ISSUE THREAD

**Issue by mkzxcvbnm** [shadowsocksrr/shadowsocksr-csharp#92]
使用最新4.9版本的ssr客户端 服务器设置obfs后客户端使用相同混淆会无法连接 
客户端设置成plain才可以使用 
tls1.2_ticket_auth
tls1.2_ticket_fastauth
都试过不行 一般是什么原因？

**Comment by mkzxcvbnm** [comment]
混淆参数设置成cloudflare.com 或者留空 都试过也不行

**Comment by Akkariiin** [comment]
请确认服务器端obfs是否设置成功

详细信息请查看服务器端log

**Comment by mkzxcvbnm** [comment]
谢谢 大佬
...奇怪了 昨天刚装好混淆没法用 今天试了下居然又好了 没法还原当时的状况了
那端时间的日志
![image](https://user-images.githubusercontent.com/16659155/38123448-a1120c88-340d-11e8-8d86-a4da21bfabd8.png)
顺便问下
1.服务器装的tls1.2_ticket_fastauth_compatible 客户端现在tls1.2_ticket_fastauth 和 tls1.2_ticket_auth这两个都可以用 他们是不是本质没什么区别?
2.文档里说到协议参数 “支持服务端自定义参数，参数为10进制整数，表示最大客户端同时使用数。”
那么客户端里的协议参数又有什么用呢？
3.文档里说到混合的参数 “客户端支持自定义参数，参数为SNI，即发送host名称的字段  服务端暂不支持自定义参数”
这个参数是伪装的客户端发送的请求还是服务器返回的？客户端里是设置国外域名比较好吗？ 我查了半天也没搞懂 网上也没例子 都是留空的  麻烦大神介绍一下 谢谢

**Comment by mkzxcvbnm** [comment]
还有文档 协议里 “auth_sha1_v4” 写的不建议 我本来想换auth_chain_*的 但是他们好像都不向下兼容 我手机里的软件没法设置协议这些 我电脑用的比较多 手机偶尔用 所有想装能向下兼容的协议 请问这个协议有什么问题嘛 为什么不建议？
auth_chain_* 里c,d...等等的有什么区别？ 网上好像查不到 文档只有a和b的

**Comment by Akkariiin** [comment]
use https://github.com/shadowsocksrr/shadowsocksr-android/releases

**Comment by mkzxcvbnm** [comment]
我的是IOS的 我知道换软件就可以不考虑向下兼容 但是IOS不越狱的话能用的软件基本都要用国外的账号才能下 有点麻烦 
这个问题无所谓 我手机用的少 偶尔用手机查个资料什么的会用一下而已 所以嫌麻烦就没弄。

只是刚装好ShadowsocksR的时候不管怎么弄 重装了几遍 试过几种不同的混淆 都连不上 很奇怪 才来这提问的 谁知道今天它自己好了 我后来什么都没调

**Comment by mkzxcvbnm** [comment]
又出现了
![image](https://user-images.githubusercontent.com/16659155/38181202-2c01d5be-3664-11e8-8aab-94822b7984ca.png)

**Comment by AspirinGeyer** [comment]
iOS 用 auth_chain_a/b 就好了。至少现阶段够用的。
至于时好时坏这个问题，重启一下服务器试试？给我的感觉有点像有进程没有关闭掉。

**Comment by mkzxcvbnm** [comment]
恩 时好时坏的 坏的时候我就直接关掉混淆用 就是很奇怪不知道什么原因
