### ISSUE TITLE
建议修改pac订阅地址

### ISSUE THREAD

**Issue by liwenjie119** [shadowsocksrr/shadowsocksr-csharp#93]
逗比的pac，https://softs.fun/Other/pac.txt  还在更新，然后有个脚本
https://github.com/ToyoDAdoubi/doubi/blob/master/pac_get.sh

**Comment by SciUnivMoring** [comment]
首先，新的pac官方更新地址是：
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
这个如果你直接下载后打开txt文件查看，会发现是乱码（需要经过转换才变成明文pac）
**而SSR本身在更新pac的时候，是会经过一个转换过程，转换之后变成了pac.txt里的明文内容**.

ssr4.7版因为用的是旧的pac更新地址，导致无法更新pac**（4.8版本开始已经换成了新的官方地址，所以可以正常更新pac）**，**所以逗比就发布了一个备用更新地址，其实就是从那个官方地址来的，并且已经经过了转换，直接就是明文，是直接把pac.txt下载下来然后放到SSR目录里的**
你发这个Issues的时候，逗比云是softs.fun，而现在已经变成softs.loan了

**Comment by ferristale** [comment]
明白了，其实主要是ssrr里更新的pac文件里没有更新日期和新版权信息，都还是破娃以前的信息，所以会产生“这个pac会不会是旧的”这样的错觉，我刚用逗比的和软件更新的文件做了对比，两者是一样的，没问题

**Comment by JackJCSN** [comment]
何不提供一个设定项目，当官方源发生问题时，可由用户自行修改而不需要等待版本更新呢？

**Comment by dh53128** [comment]
> 首先，pac官方更新地址： https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt （以前是另一个地址，后来失效了，才变成现在这个地址） 这个如果你直接下载后打开txt文件查看，会发现是乱码（需要经过转换才变成明文pac） **而SSR本身在更新pac的时候，自带一个转换过程，转换之后变成了pac.txt里的明文内容**.
> 
> ssr4.7版因为用的是旧的pac更新地址，导致无法更新pac，**而从4.8版本开始已经换成了新的地址，所以可以正常更新pac**
> 
> **逗比发布的pac下载地址是作为备用的（注意是“下载地址”而不是“更新地址”），其实也是从那个官方地址来的，并且已经经过了转换，直接就是明文，使用方式是直接把pac.txt下载下来然后放到SSR目录里，而不能让SSR自动更新pac时用这个地址去更新，因为SSR自带的转换过程会把已经转好的明文又转换一遍**
> 
> 逗比的pac其实是出于这样一种考虑：由于SSR的更新pac的地址写死在源代码里，如果哪天pac更新地址发生了变化，就需要修改源代码里的地址然后重新编译（4.7版本里用的旧地址所以无法更新pac，4.8就换了新地址），而pac更新地址如果发生了变化，作为用户，肯定就是等作者编译一个新版本，而在等待的这段时间里，逗比会从新的更新地址获取pac，经过转换后提供给大家，你就可以通过“下载逗比的pac.txt放到SSR目录里”这种方式来更新pac
> 
> 另外，逗比云的域名也会变，你发这个Issues的时候，逗比云是softs.fun，而现在已经变成softs.loan了 既然官方的地址会变，逗比云的地址也会变，为何不用官方的呢

能否通过hosts更改指向而更新呢
