### ISSUE TITLE
win10启动报错

### ISSUE THREAD

**Issue by Lstoryc** [shadowsocksrr/shadowsocksr-csharp#95]
如下文：

===
[2018-04-02 10:11:06] [Error] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
[2018-04-02 10:11:06] [Error] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
===

**Comment by ncs19960831** [comment]
如果最近安装了补丁之后出现了这个问题请将补丁卸掉

**Comment by AspirinGeyer** [comment]
安装了哪个补丁？

**Comment by ncs19960831** [comment]
应该是.NET的更新补丁，具体的记不清楚了

**Comment by AspirinGeyer** [comment]
重新看了一眼错误信息，感觉是你的参数有问题。是不是 IP 地址格式不对或者端口号写错了？
