### ISSUE TITLE
开了全局，国内的网页都打不开，比如淘宝百度那些，之前不会，就这几天才这样

### ISSUE THREAD

**Issue by zhenlinhgs** [shadowsocksrr/shadowsocksr-csharp#96]
为什么前段时间我SSR用的好好的，但是这两天，发现开了全局之后，国内的网页都打不开的，只能开国外的网页，之前不会，就这两天才这样，这是为什么

**Comment by AspirinGeyer** [comment]
大概率原因是你的服务器提供商的回程线路出了一些小问题。

**Comment by zhenlinhgs** [comment]
嗯，是线路的问题，非常感谢您的回复
