### ISSUE TITLE
[功能需求]chacha20-ietf-poly1305加密支持

### ISSUE THREAD

**Issue by PaTTeeL** [shadowsocksrr/shadowsocksr-csharp#97]
貌似客户端一直没有支持chacha20-ietf-poly1305的加密方式，现在好多SS服务器都改成仅支持AES-xxx-GCM或者chacha20-ietf-poly1305了，现在正在混用SSR和SS服务器，所以请问能否增加chacha20-ietf-poly1305加密模式的支持？
另：google了一下，貌似chacha20-ietf和chacha20-ietf-poly1305是不一样的吧？Poly1305增加了消息认证码机制？

**Comment by AspirinGeyer** [comment]
正如你所见到的，这并不是一件很容易的事情。
参见 [这个 Issue](https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/34) 中 @Akkariiin 对 AEAD 系列算法的说明，以及我们为什么**不会**在 SSR 中添加对 AEAD 算法的支持。
